// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderGetBadgePointsLimitsIn uint16 = 1371

// UserGetBadgePointLimitsInPacket — Request the point limits for badge achievement levels
type UserGetBadgePointLimitsInPacket struct {
}

func (p *UserGetBadgePointLimitsInPacket) HeaderID() uint16 { return HeaderGetBadgePointsLimitsIn }

func (p *UserGetBadgePointLimitsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserGetBadgePointLimitsIn(r *codec.Reader) (*UserGetBadgePointLimitsInPacket, error) {
	p := &UserGetBadgePointLimitsInPacket{}
	return p, nil
}

const HeaderRequestabadgeIn uint16 = 3077

// UserRequestBadgeInPacket — Request a specific promotional or achievement badge
type UserRequestBadgeInPacket struct {
	RequestCode string
}

func (p *UserRequestBadgeInPacket) HeaderID() uint16 { return HeaderRequestabadgeIn }

func (p *UserRequestBadgeInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.RequestCode)
	return nil
}

func DecodeUserRequestBadgeIn(r *codec.Reader) (*UserRequestBadgeInPacket, error) {
	p := &UserRequestBadgeInPacket{}
	var err error
	if p.RequestCode, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetisbadgerequestfulfilledIn uint16 = 1364

// UserCheckBadgeRequestInPacket — Check whether a badge request code has been fulfilled
type UserCheckBadgeRequestInPacket struct {
	RequestCode string
}

func (p *UserCheckBadgeRequestInPacket) HeaderID() uint16 { return HeaderGetisbadgerequestfulfilledIn }

func (p *UserCheckBadgeRequestInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.RequestCode)
	return nil
}

func DecodeUserCheckBadgeRequestIn(r *codec.Reader) (*UserCheckBadgeRequestInPacket, error) {
	p := &UserCheckBadgeRequestInPacket{}
	var err error
	if p.RequestCode, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderAchievementListIn uint16 = 219

// UserAchievementListInPacket — Achievement list
type UserAchievementListInPacket struct {
}

func (p *UserAchievementListInPacket) HeaderID() uint16 { return HeaderAchievementListIn }

func (p *UserAchievementListInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserAchievementListIn(r *codec.Reader) (*UserAchievementListInPacket, error) {
	p := &UserAchievementListInPacket{}
	return p, nil
}

const HeaderAchievementResolutionOpenIn uint16 = 359

// UserAchievementResolutionOpenInPacket — Achievement resolution open
type UserAchievementResolutionOpenInPacket struct {
}

func (p *UserAchievementResolutionOpenInPacket) HeaderID() uint16 { return HeaderAchievementResolutionOpenIn }

func (p *UserAchievementResolutionOpenInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserAchievementResolutionOpenIn(r *codec.Reader) (*UserAchievementResolutionOpenInPacket, error) {
	p := &UserAchievementResolutionOpenInPacket{}
	return p, nil
}

const HeaderTalentTrackGetLevelIn uint16 = 2127

// UserTalentTrackGetLevelInPacket — Talent track get level
type UserTalentTrackGetLevelInPacket struct {
}

func (p *UserTalentTrackGetLevelInPacket) HeaderID() uint16 { return HeaderTalentTrackGetLevelIn }

func (p *UserTalentTrackGetLevelInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserTalentTrackGetLevelIn(r *codec.Reader) (*UserTalentTrackGetLevelInPacket, error) {
	p := &UserTalentTrackGetLevelInPacket{}
	return p, nil
}

const HeaderResetresolutionachievementmessageIn uint16 = 3144

// UserResetresolutionachievementmessageInPacket — Resetresolutionachievementmessage
type UserResetresolutionachievementmessageInPacket struct {
}

func (p *UserResetresolutionachievementmessageInPacket) HeaderID() uint16 { return HeaderResetresolutionachievementmessageIn }

func (p *UserResetresolutionachievementmessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserResetresolutionachievementmessageIn(r *codec.Reader) (*UserResetresolutionachievementmessageInPacket, error) {
	p := &UserResetresolutionachievementmessageInPacket{}
	return p, nil
}

const HeaderHelperTalentTrackIn uint16 = 196

// ModerationHelperTalentTrackInPacket — Helper talent track
type ModerationHelperTalentTrackInPacket struct {
}

func (p *ModerationHelperTalentTrackInPacket) HeaderID() uint16 { return HeaderHelperTalentTrackIn }

func (p *ModerationHelperTalentTrackInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeModerationHelperTalentTrackIn(r *codec.Reader) (*ModerationHelperTalentTrackInPacket, error) {
	p := &ModerationHelperTalentTrackInPacket{}
	return p, nil
}

const HeaderGetusergameachievementsmessageIn uint16 = 389

// GamesGetusergameachievementsmessageInPacket — Getusergameachievementsmessage
type GamesGetusergameachievementsmessageInPacket struct {
}

func (p *GamesGetusergameachievementsmessageInPacket) HeaderID() uint16 { return HeaderGetusergameachievementsmessageIn }

func (p *GamesGetusergameachievementsmessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGetusergameachievementsmessageIn(r *codec.Reader) (*GamesGetusergameachievementsmessageInPacket, error) {
	p := &GamesGetusergameachievementsmessageInPacket{}
	return p, nil
}

const HeaderGetgameachievementsmessageIn uint16 = 2399

// GamesGetgameachievementsmessageInPacket — Getgameachievementsmessage
type GamesGetgameachievementsmessageInPacket struct {
}

func (p *GamesGetgameachievementsmessageInPacket) HeaderID() uint16 { return HeaderGetgameachievementsmessageIn }

func (p *GamesGetgameachievementsmessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGetgameachievementsmessageIn(r *codec.Reader) (*GamesGetgameachievementsmessageInPacket, error) {
	p := &GamesGetgameachievementsmessageInPacket{}
	return p, nil
}

const HeaderBadgePointLimitsOut uint16 = 2501

// UserBadgePointLimitsOutPacket — Deliver point thresholds for badge achievement levels
type UserBadgePointLimitsOutPacket struct {
	AchievementCount int32
}

func (p *UserBadgePointLimitsOutPacket) HeaderID() uint16 { return HeaderBadgePointLimitsOut }

func (p *UserBadgePointLimitsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.AchievementCount)
	return nil
}

func DecodeUserBadgePointLimitsOut(r *codec.Reader) (*UserBadgePointLimitsOutPacket, error) {
	p := &UserBadgePointLimitsOutPacket{}
	var err error
	if p.AchievementCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderBadgeRequestFulfilledOut uint16 = 2998

// UserBadgeRequestFulfilledOutPacket — Report whether a promotional badge request was fulfilled
type UserBadgeRequestFulfilledOutPacket struct {
	RequestCode string
	Fulfilled bool
}

func (p *UserBadgeRequestFulfilledOutPacket) HeaderID() uint16 { return HeaderBadgeRequestFulfilledOut }

func (p *UserBadgeRequestFulfilledOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.RequestCode)
	w.WriteBool(p.Fulfilled)
	return nil
}

func DecodeUserBadgeRequestFulfilledOut(r *codec.Reader) (*UserBadgeRequestFulfilledOutPacket, error) {
	p := &UserBadgeRequestFulfilledOutPacket{}
	var err error
	if p.RequestCode, err = r.ReadString(); err != nil { return nil, err }
	if p.Fulfilled, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderAchievementresolutionsOut uint16 = 66

// UserAchievementresolutionsOutPacket — Achievementresolutions
type UserAchievementresolutionsOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 int32
}

func (p *UserAchievementresolutionsOutPacket) HeaderID() uint16 { return HeaderAchievementresolutionsOut }

func (p *UserAchievementresolutionsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteInt32(p.Field3)
	return nil
}

func DecodeUserAchievementresolutionsOut(r *codec.Reader) (*UserAchievementresolutionsOutPacket, error) {
	p := &UserAchievementresolutionsOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderAchievementListOut uint16 = 305

// UserAchievementListOutPacket — Achievement list
type UserAchievementListOutPacket struct {
}

func (p *UserAchievementListOutPacket) HeaderID() uint16 { return HeaderAchievementListOut }

func (p *UserAchievementListOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserAchievementListOut(r *codec.Reader) (*UserAchievementListOutPacket, error) {
	p := &UserAchievementListOutPacket{}
	return p, nil
}

const HeaderTalentTrackLevelUpOut uint16 = 638

// UserTalentTrackLevelUpOutPacket — Talent track level up
type UserTalentTrackLevelUpOutPacket struct {
	Field1 string
	Field2 int32
	Field3 int32
}

func (p *UserTalentTrackLevelUpOutPacket) HeaderID() uint16 { return HeaderTalentTrackLevelUpOut }

func (p *UserTalentTrackLevelUpOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteInt32(p.Field3)
	return nil
}

func DecodeUserTalentTrackLevelUpOut(r *codec.Reader) (*UserTalentTrackLevelUpOutPacket, error) {
	p := &UserTalentTrackLevelUpOutPacket{}
	var err error
	if p.Field1, err = r.ReadString(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderAchievementresolutioncompletedOut uint16 = 740

// UserAchievementresolutioncompletedOutPacket — Achievementresolutioncompleted
type UserAchievementresolutioncompletedOutPacket struct {
	Field1 string
	Field2 string
}

func (p *UserAchievementresolutioncompletedOutPacket) HeaderID() uint16 { return HeaderAchievementresolutioncompletedOut }

func (p *UserAchievementresolutioncompletedOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Field1)
	w.WriteString(p.Field2)
	return nil
}

func DecodeUserAchievementresolutioncompletedOut(r *codec.Reader) (*UserAchievementresolutioncompletedOutPacket, error) {
	p := &UserAchievementresolutioncompletedOutPacket{}
	var err error
	if p.Field1, err = r.ReadString(); err != nil { return nil, err }
	if p.Field2, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderAchievementNotificationOut uint16 = 806

// UserAchievementNotificationOutPacket — Achievement notification
type UserAchievementNotificationOutPacket struct {
}

func (p *UserAchievementNotificationOutPacket) HeaderID() uint16 { return HeaderAchievementNotificationOut }

func (p *UserAchievementNotificationOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserAchievementNotificationOut(r *codec.Reader) (*UserAchievementNotificationOutPacket, error) {
	p := &UserAchievementNotificationOutPacket{}
	return p, nil
}

const HeaderTalentTrackLevelOut uint16 = 1203

// UserTalentTrackLevelOutPacket — Talent track level
type UserTalentTrackLevelOutPacket struct {
	Field1 string
	Field2 int32
	Field3 int32
}

func (p *UserTalentTrackLevelOutPacket) HeaderID() uint16 { return HeaderTalentTrackLevelOut }

func (p *UserTalentTrackLevelOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteInt32(p.Field3)
	return nil
}

func DecodeUserTalentTrackLevelOut(r *codec.Reader) (*UserTalentTrackLevelOutPacket, error) {
	p := &UserTalentTrackLevelOutPacket{}
	var err error
	if p.Field1, err = r.ReadString(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserAchievementScoreOut uint16 = 1968

// UserUserAchievementScoreOutPacket — User achievement score
type UserUserAchievementScoreOutPacket struct {
}

func (p *UserUserAchievementScoreOutPacket) HeaderID() uint16 { return HeaderUserAchievementScoreOut }

func (p *UserUserAchievementScoreOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserUserAchievementScoreOut(r *codec.Reader) (*UserUserAchievementScoreOutPacket, error) {
	p := &UserUserAchievementScoreOutPacket{}
	return p, nil
}

const HeaderAchievementProgressedOut uint16 = 2107

// UserAchievementProgressedOutPacket — Achievement progressed
type UserAchievementProgressedOutPacket struct {
}

func (p *UserAchievementProgressedOutPacket) HeaderID() uint16 { return HeaderAchievementProgressedOut }

func (p *UserAchievementProgressedOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserAchievementProgressedOut(r *codec.Reader) (*UserAchievementProgressedOutPacket, error) {
	p := &UserAchievementProgressedOutPacket{}
	return p, nil
}

const HeaderAchievementresolutionprogressOut uint16 = 3370

// UserAchievementresolutionprogressOutPacket — Achievementresolutionprogress
type UserAchievementresolutionprogressOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 string
	Field4 int32
	Field5 int32
	Field6 int32
}

func (p *UserAchievementresolutionprogressOutPacket) HeaderID() uint16 { return HeaderAchievementresolutionprogressOut }

func (p *UserAchievementresolutionprogressOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteString(p.Field3)
	w.WriteInt32(p.Field4)
	w.WriteInt32(p.Field5)
	w.WriteInt32(p.Field6)
	return nil
}

func DecodeUserAchievementresolutionprogressOut(r *codec.Reader) (*UserAchievementresolutionprogressOutPacket, error) {
	p := &UserAchievementresolutionprogressOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadString(); err != nil { return nil, err }
	if p.Field4, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field5, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field6, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGameachievementsOut uint16 = 1689

// GamesGameachievementsOutPacket — Gameachievements
type GamesGameachievementsOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 int32
	Field4 int32
	Field5 string
	Field6 int32
}

func (p *GamesGameachievementsOutPacket) HeaderID() uint16 { return HeaderGameachievementsOut }

func (p *GamesGameachievementsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteInt32(p.Field3)
	w.WriteInt32(p.Field4)
	w.WriteString(p.Field5)
	w.WriteInt32(p.Field6)
	return nil
}

func DecodeGamesGameachievementsOut(r *codec.Reader) (*GamesGameachievementsOutPacket, error) {
	p := &GamesGameachievementsOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field4, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field5, err = r.ReadString(); err != nil { return nil, err }
	if p.Field6, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGameCenterAchievementsOut uint16 = 2265

// GamesGameCenterAchievementsOutPacket — Game center achievements
type GamesGameCenterAchievementsOutPacket struct {
}

func (p *GamesGameCenterAchievementsOutPacket) HeaderID() uint16 { return HeaderGameCenterAchievementsOut }

func (p *GamesGameCenterAchievementsOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGameCenterAchievementsOut(r *codec.Reader) (*GamesGameCenterAchievementsOutPacket, error) {
	p := &GamesGameCenterAchievementsOutPacket{}
	return p, nil
}

const HeaderHelperTalentTrackOut uint16 = 3406

// ModerationHelperTalentTrackOutPacket — Helper talent track
type ModerationHelperTalentTrackOutPacket struct {
}

func (p *ModerationHelperTalentTrackOutPacket) HeaderID() uint16 { return HeaderHelperTalentTrackOut }

func (p *ModerationHelperTalentTrackOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeModerationHelperTalentTrackOut(r *codec.Reader) (*ModerationHelperTalentTrackOutPacket, error) {
	p := &ModerationHelperTalentTrackOutPacket{}
	return p, nil
}

