// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderUserSettingsCameraIn uint16 = 1461

// UserSettingsCameraInPacket — Toggle camera-follow-avatar mode
type UserSettingsCameraInPacket struct {
	CameraFollow bool
}

func (p *UserSettingsCameraInPacket) HeaderID() uint16 { return HeaderUserSettingsCameraIn }

func (p *UserSettingsCameraInPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.CameraFollow)
	return nil
}

func DecodeUserSettingsCameraIn(r *codec.Reader) (*UserSettingsCameraInPacket, error) {
	p := &UserSettingsCameraInPacket{}
	var err error
	if p.CameraFollow, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderRequestCameraConfigurationIn uint16 = 796

// SessionRequestCameraConfigurationInPacket — Request camera configuration
type SessionRequestCameraConfigurationInPacket struct {
}

func (p *SessionRequestCameraConfigurationInPacket) HeaderID() uint16 { return HeaderRequestCameraConfigurationIn }

func (p *SessionRequestCameraConfigurationInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSessionRequestCameraConfigurationIn(r *codec.Reader) (*SessionRequestCameraConfigurationInPacket, error) {
	p := &SessionRequestCameraConfigurationInPacket{}
	return p, nil
}

const HeaderRenderRoomThumbnailIn uint16 = 1982

// SessionRenderRoomThumbnailInPacket — Render room thumbnail
type SessionRenderRoomThumbnailInPacket struct {
}

func (p *SessionRenderRoomThumbnailInPacket) HeaderID() uint16 { return HeaderRenderRoomThumbnailIn }

func (p *SessionRenderRoomThumbnailInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSessionRenderRoomThumbnailIn(r *codec.Reader) (*SessionRenderRoomThumbnailInPacket, error) {
	p := &SessionRenderRoomThumbnailInPacket{}
	return p, nil
}

const HeaderPublishPhotoIn uint16 = 2068

// SessionPublishPhotoInPacket — Publish photo
type SessionPublishPhotoInPacket struct {
}

func (p *SessionPublishPhotoInPacket) HeaderID() uint16 { return HeaderPublishPhotoIn }

func (p *SessionPublishPhotoInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSessionPublishPhotoIn(r *codec.Reader) (*SessionPublishPhotoInPacket, error) {
	p := &SessionPublishPhotoInPacket{}
	return p, nil
}

const HeaderPurchasePhotoIn uint16 = 2408

// SessionPurchasePhotoInPacket — Purchase photo
type SessionPurchasePhotoInPacket struct {
}

func (p *SessionPurchasePhotoInPacket) HeaderID() uint16 { return HeaderPurchasePhotoIn }

func (p *SessionPurchasePhotoInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSessionPurchasePhotoIn(r *codec.Reader) (*SessionPurchasePhotoInPacket, error) {
	p := &SessionPurchasePhotoInPacket{}
	return p, nil
}

const HeaderUpdateRoomThumbnailIn uint16 = 2468

// RoomUpdateRoomThumbnailInPacket — Update room thumbnail
type RoomUpdateRoomThumbnailInPacket struct {
}

func (p *RoomUpdateRoomThumbnailInPacket) HeaderID() uint16 { return HeaderUpdateRoomThumbnailIn }

func (p *RoomUpdateRoomThumbnailInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomUpdateRoomThumbnailIn(r *codec.Reader) (*RoomUpdateRoomThumbnailInPacket, error) {
	p := &RoomUpdateRoomThumbnailInPacket{}
	return p, nil
}

const HeaderPhotoCompetitionIn uint16 = 3959

// SessionPhotoCompetitionInPacket — Photo competition
type SessionPhotoCompetitionInPacket struct {
}

func (p *SessionPhotoCompetitionInPacket) HeaderID() uint16 { return HeaderPhotoCompetitionIn }

func (p *SessionPhotoCompetitionInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSessionPhotoCompetitionIn(r *codec.Reader) (*SessionPhotoCompetitionInPacket, error) {
	p := &SessionPhotoCompetitionInPacket{}
	return p, nil
}

const HeaderCallForHelpFromPhotoIn uint16 = 2492

// ModerationCallForHelpFromPhotoInPacket — Call for help from photo
type ModerationCallForHelpFromPhotoInPacket struct {
}

func (p *ModerationCallForHelpFromPhotoInPacket) HeaderID() uint16 { return HeaderCallForHelpFromPhotoIn }

func (p *ModerationCallForHelpFromPhotoInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeModerationCallForHelpFromPhotoIn(r *codec.Reader) (*ModerationCallForHelpFromPhotoInPacket, error) {
	p := &ModerationCallForHelpFromPhotoInPacket{}
	return p, nil
}

const HeaderCameraSnapshotOut uint16 = 463

// SessionCameraSnapshotOutPacket — Camera snapshot
type SessionCameraSnapshotOutPacket struct {
	Field1 string
	Field2 int32
}

func (p *SessionCameraSnapshotOutPacket) HeaderID() uint16 { return HeaderCameraSnapshotOut }

func (p *SessionCameraSnapshotOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeSessionCameraSnapshotOut(r *codec.Reader) (*SessionCameraSnapshotOutPacket, error) {
	p := &SessionCameraSnapshotOutPacket{}
	var err error
	if p.Field1, err = r.ReadString(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderThumbnailUpdateResultOut uint16 = 1927

// SessionThumbnailUpdateResultOutPacket — Thumbnail update result
type SessionThumbnailUpdateResultOutPacket struct {
	Field1 int32
	Field2 int32
}

func (p *SessionThumbnailUpdateResultOutPacket) HeaderID() uint16 { return HeaderThumbnailUpdateResultOut }

func (p *SessionThumbnailUpdateResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeSessionThumbnailUpdateResultOut(r *codec.Reader) (*SessionThumbnailUpdateResultOutPacket, error) {
	p := &SessionThumbnailUpdateResultOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderCameraPublishStatusOut uint16 = 2057

// SessionCameraPublishStatusOutPacket — Camera publish status
type SessionCameraPublishStatusOutPacket struct {
	Field1 bool
	Field2 int32
	Field3 string
}

func (p *SessionCameraPublishStatusOutPacket) HeaderID() uint16 { return HeaderCameraPublishStatusOut }

func (p *SessionCameraPublishStatusOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteString(p.Field3)
	return nil
}

func DecodeSessionCameraPublishStatusOut(r *codec.Reader) (*SessionCameraPublishStatusOutPacket, error) {
	p := &SessionCameraPublishStatusOutPacket{}
	var err error
	if p.Field1, err = r.ReadBool(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderCameraPurchaseOkOut uint16 = 2783

// SessionCameraPurchaseOkOutPacket — Camera purchase ok
type SessionCameraPurchaseOkOutPacket struct {
}

func (p *SessionCameraPurchaseOkOutPacket) HeaderID() uint16 { return HeaderCameraPurchaseOkOut }

func (p *SessionCameraPurchaseOkOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSessionCameraPurchaseOkOut(r *codec.Reader) (*SessionCameraPurchaseOkOutPacket, error) {
	p := &SessionCameraPurchaseOkOutPacket{}
	return p, nil
}

const HeaderThumbnailStatusOut uint16 = 3595

// SessionThumbnailStatusOutPacket — Thumbnail status
type SessionThumbnailStatusOutPacket struct {
	Field1 bool
	Field2 bool
}

func (p *SessionThumbnailStatusOutPacket) HeaderID() uint16 { return HeaderThumbnailStatusOut }

func (p *SessionThumbnailStatusOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.Field1)
	w.WriteBool(p.Field2)
	return nil
}

func DecodeSessionThumbnailStatusOut(r *codec.Reader) (*SessionThumbnailStatusOutPacket, error) {
	p := &SessionThumbnailStatusOutPacket{}
	var err error
	if p.Field1, err = r.ReadBool(); err != nil { return nil, err }
	if p.Field2, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderCameraStorageUrlOut uint16 = 3696

// SessionCameraStorageUrlOutPacket — Camera storage url
type SessionCameraStorageUrlOutPacket struct {
	Field1 string
}

func (p *SessionCameraStorageUrlOutPacket) HeaderID() uint16 { return HeaderCameraStorageUrlOut }

func (p *SessionCameraStorageUrlOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Field1)
	return nil
}

func DecodeSessionCameraStorageUrlOut(r *codec.Reader) (*SessionCameraStorageUrlOutPacket, error) {
	p := &SessionCameraStorageUrlOutPacket{}
	var err error
	if p.Field1, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderInitCameraOut uint16 = 3878

// SessionInitCameraOutPacket — Init camera
type SessionInitCameraOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 int32
}

func (p *SessionInitCameraOutPacket) HeaderID() uint16 { return HeaderInitCameraOut }

func (p *SessionInitCameraOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteInt32(p.Field3)
	return nil
}

func DecodeSessionInitCameraOut(r *codec.Reader) (*SessionInitCameraOutPacket, error) {
	p := &SessionInitCameraOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

