// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderRecyclerPrizesIn uint16 = 398

// EconomyRecyclerPrizesInPacket — Recycler prizes
type EconomyRecyclerPrizesInPacket struct {
}

func (p *EconomyRecyclerPrizesInPacket) HeaderID() uint16 { return HeaderRecyclerPrizesIn }

func (p *EconomyRecyclerPrizesInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeEconomyRecyclerPrizesIn(r *codec.Reader) (*EconomyRecyclerPrizesInPacket, error) {
	p := &EconomyRecyclerPrizesInPacket{}
	return p, nil
}

const HeaderGetCraftableProductsIn uint16 = 633

// EconomyCraftableProductsInPacket — Get craftable products
type EconomyCraftableProductsInPacket struct {
}

func (p *EconomyCraftableProductsInPacket) HeaderID() uint16 { return HeaderGetCraftableProductsIn }

func (p *EconomyCraftableProductsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeEconomyCraftableProductsIn(r *codec.Reader) (*EconomyCraftableProductsInPacket, error) {
	p := &EconomyCraftableProductsInPacket{}
	return p, nil
}

const HeaderGetCraftingRecipeIn uint16 = 1173

// EconomyCraftingRecipeInPacket — Get crafting recipe
type EconomyCraftingRecipeInPacket struct {
}

func (p *EconomyCraftingRecipeInPacket) HeaderID() uint16 { return HeaderGetCraftingRecipeIn }

func (p *EconomyCraftingRecipeInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeEconomyCraftingRecipeIn(r *codec.Reader) (*EconomyCraftingRecipeInPacket, error) {
	p := &EconomyCraftingRecipeInPacket{}
	return p, nil
}

const HeaderCraftSecretIn uint16 = 1251

// EconomyCraftSecretInPacket — Craft secret
type EconomyCraftSecretInPacket struct {
}

func (p *EconomyCraftSecretInPacket) HeaderID() uint16 { return HeaderCraftSecretIn }

func (p *EconomyCraftSecretInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeEconomyCraftSecretIn(r *codec.Reader) (*EconomyCraftSecretInPacket, error) {
	p := &EconomyCraftSecretInPacket{}
	return p, nil
}

const HeaderRecyclerStatusIn uint16 = 1342

// EconomyRecyclerStatusInPacket — Recycler status
type EconomyRecyclerStatusInPacket struct {
}

func (p *EconomyRecyclerStatusInPacket) HeaderID() uint16 { return HeaderRecyclerStatusIn }

func (p *EconomyRecyclerStatusInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeEconomyRecyclerStatusIn(r *codec.Reader) (*EconomyRecyclerStatusInPacket, error) {
	p := &EconomyRecyclerStatusInPacket{}
	return p, nil
}

const HeaderRecyclerItemsIn uint16 = 2771

// EconomyRecyclerItemsInPacket — Recycler items
type EconomyRecyclerItemsInPacket struct {
}

func (p *EconomyRecyclerItemsInPacket) HeaderID() uint16 { return HeaderRecyclerItemsIn }

func (p *EconomyRecyclerItemsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeEconomyRecyclerItemsIn(r *codec.Reader) (*EconomyRecyclerItemsInPacket, error) {
	p := &EconomyRecyclerItemsInPacket{}
	return p, nil
}

const HeaderGetCraftingRecipesAvailableIn uint16 = 3086

// EconomyCraftingRecipesAvailableInPacket — Get crafting recipes available
type EconomyCraftingRecipesAvailableInPacket struct {
}

func (p *EconomyCraftingRecipesAvailableInPacket) HeaderID() uint16 { return HeaderGetCraftingRecipesAvailableIn }

func (p *EconomyCraftingRecipesAvailableInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeEconomyCraftingRecipesAvailableIn(r *codec.Reader) (*EconomyCraftingRecipesAvailableInPacket, error) {
	p := &EconomyCraftingRecipesAvailableInPacket{}
	return p, nil
}

const HeaderItemExchangeRedeemIn uint16 = 3115

// FurnitureItemExchangeRedeemInPacket — Item exchange redeem
type FurnitureItemExchangeRedeemInPacket struct {
}

func (p *FurnitureItemExchangeRedeemInPacket) HeaderID() uint16 { return HeaderItemExchangeRedeemIn }

func (p *FurnitureItemExchangeRedeemInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureItemExchangeRedeemIn(r *codec.Reader) (*FurnitureItemExchangeRedeemInPacket, error) {
	p := &FurnitureItemExchangeRedeemInPacket{}
	return p, nil
}

const HeaderCraftIn uint16 = 3591

// EconomyCraftInPacket — Craft
type EconomyCraftInPacket struct {
}

func (p *EconomyCraftInPacket) HeaderID() uint16 { return HeaderCraftIn }

func (p *EconomyCraftInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeEconomyCraftIn(r *codec.Reader) (*EconomyCraftInPacket, error) {
	p := &EconomyCraftInPacket{}
	return p, nil
}

const HeaderRecyclerFinishedOut uint16 = 468

// EconomyRecyclerFinishedOutPacket — Recycler finished
type EconomyRecyclerFinishedOutPacket struct {
	Field1 int32
	Field2 int32
}

func (p *EconomyRecyclerFinishedOutPacket) HeaderID() uint16 { return HeaderRecyclerFinishedOut }

func (p *EconomyRecyclerFinishedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeEconomyRecyclerFinishedOut(r *codec.Reader) (*EconomyRecyclerFinishedOutPacket, error) {
	p := &EconomyRecyclerFinishedOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderCraftingResultOut uint16 = 618

// EconomyCraftingResultOutPacket — Crafting result
type EconomyCraftingResultOutPacket struct {
	Field1 bool
}

func (p *EconomyCraftingResultOutPacket) HeaderID() uint16 { return HeaderCraftingResultOut }

func (p *EconomyCraftingResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.Field1)
	return nil
}

func DecodeEconomyCraftingResultOut(r *codec.Reader) (*EconomyCraftingResultOutPacket, error) {
	p := &EconomyCraftingResultOutPacket{}
	var err error
	if p.Field1, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderCraftableProductsOut uint16 = 1000

// EconomyCraftableProductsOutPacket — Craftable products
type EconomyCraftableProductsOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 string
}

func (p *EconomyCraftableProductsOutPacket) HeaderID() uint16 { return HeaderCraftableProductsOut }

func (p *EconomyCraftableProductsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteString(p.Field3)
	return nil
}

func DecodeEconomyCraftableProductsOut(r *codec.Reader) (*EconomyCraftableProductsOutPacket, error) {
	p := &EconomyCraftableProductsOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderCraftingRecipesAvailableOut uint16 = 2124

// EconomyCraftingRecipesAvailableOutPacket — Crafting recipes available
type EconomyCraftingRecipesAvailableOutPacket struct {
	Field1 int32
	Field2 bool
}

func (p *EconomyCraftingRecipesAvailableOutPacket) HeaderID() uint16 { return HeaderCraftingRecipesAvailableOut }

func (p *EconomyCraftingRecipesAvailableOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteBool(p.Field2)
	return nil
}

func DecodeEconomyCraftingRecipesAvailableOut(r *codec.Reader) (*EconomyCraftingRecipesAvailableOutPacket, error) {
	p := &EconomyCraftingRecipesAvailableOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderCraftingRecipeOut uint16 = 2774

// EconomyCraftingRecipeOutPacket — Crafting recipe
type EconomyCraftingRecipeOutPacket struct {
	Field1 int32
}

func (p *EconomyCraftingRecipeOutPacket) HeaderID() uint16 { return HeaderCraftingRecipeOut }

func (p *EconomyCraftingRecipeOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	return nil
}

func DecodeEconomyCraftingRecipeOut(r *codec.Reader) (*EconomyCraftingRecipeOutPacket, error) {
	p := &EconomyCraftingRecipeOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRecyclerPrizesOut uint16 = 3164

// EconomyRecyclerPrizesOutPacket — Recycler prizes
type EconomyRecyclerPrizesOutPacket struct {
}

func (p *EconomyRecyclerPrizesOutPacket) HeaderID() uint16 { return HeaderRecyclerPrizesOut }

func (p *EconomyRecyclerPrizesOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeEconomyRecyclerPrizesOut(r *codec.Reader) (*EconomyRecyclerPrizesOutPacket, error) {
	p := &EconomyRecyclerPrizesOutPacket{}
	return p, nil
}

const HeaderRecyclerStatusOut uint16 = 3433

// EconomyRecyclerStatusOutPacket — Recycler status
type EconomyRecyclerStatusOutPacket struct {
	Field1 int32
	Field2 int32
}

func (p *EconomyRecyclerStatusOutPacket) HeaderID() uint16 { return HeaderRecyclerStatusOut }

func (p *EconomyRecyclerStatusOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeEconomyRecyclerStatusOut(r *codec.Reader) (*EconomyRecyclerStatusOutPacket, error) {
	p := &EconomyRecyclerStatusOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

