//go:generate go run ../../tools/protogen -spec ../../vendor/pixel-protocol/spec/protocol.yaml -out .

// Package protocol contains generated packet structs and codec methods.
// Code generated by protogen. DO NOT EDIT.
package protocol
