// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderFurniturePlaceIn uint16 = 1258

// FurniturePlaceInPacket — Place a furniture item from inventory into the room
type FurniturePlaceInPacket struct {
	ItemId int32
	X int32
	Y int32
	Direction int32
}

func (p *FurniturePlaceInPacket) HeaderID() uint16 { return HeaderFurniturePlaceIn }

func (p *FurniturePlaceInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.X)
	w.WriteInt32(p.Y)
	w.WriteInt32(p.Direction)
	return nil
}

func DecodeFurniturePlaceIn(r *codec.Reader) (*FurniturePlaceInPacket, error) {
	p := &FurniturePlaceInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.X, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Y, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Direction, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurniturePickupIn uint16 = 3456

// FurniturePickupInPacket — Pick up a furniture item from the room
type FurniturePickupInPacket struct {
	Type int32
	ItemId int32
}

func (p *FurniturePickupInPacket) HeaderID() uint16 { return HeaderFurniturePickupIn }

func (p *FurniturePickupInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Type)
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurniturePickupIn(r *codec.Reader) (*FurniturePickupInPacket, error) {
	p := &FurniturePickupInPacket{}
	var err error
	if p.Type, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureFloorUpdateIn uint16 = 248

// FurnitureFloorUpdateInPacket — Move or rotate a floor item in the room
type FurnitureFloorUpdateInPacket struct {
	ItemId int32
	X int32
	Y int32
	Direction int32
}

func (p *FurnitureFloorUpdateInPacket) HeaderID() uint16 { return HeaderFurnitureFloorUpdateIn }

func (p *FurnitureFloorUpdateInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.X)
	w.WriteInt32(p.Y)
	w.WriteInt32(p.Direction)
	return nil
}

func DecodeFurnitureFloorUpdateIn(r *codec.Reader) (*FurnitureFloorUpdateInPacket, error) {
	p := &FurnitureFloorUpdateInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.X, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Y, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Direction, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureWallUpdateIn uint16 = 168

// FurnitureWallUpdateInPacket — Move a wall item to a new position
type FurnitureWallUpdateInPacket struct {
	ItemId string
	WallPosition string
}

func (p *FurnitureWallUpdateInPacket) HeaderID() uint16 { return HeaderFurnitureWallUpdateIn }

func (p *FurnitureWallUpdateInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.ItemId)
	w.WriteString(p.WallPosition)
	return nil
}

func DecodeFurnitureWallUpdateIn(r *codec.Reader) (*FurnitureWallUpdateInPacket, error) {
	p := &FurnitureWallUpdateInPacket{}
	var err error
	if p.ItemId, err = r.ReadString(); err != nil { return nil, err }
	if p.WallPosition, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemDimmerSettingsIn uint16 = 2813

// FurnitureGetDimmerSettingsInPacket — Request the dimmer preset configuration
type FurnitureGetDimmerSettingsInPacket struct {
	ItemId int32
}

func (p *FurnitureGetDimmerSettingsInPacket) HeaderID() uint16 { return HeaderItemDimmerSettingsIn }

func (p *FurnitureGetDimmerSettingsInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureGetDimmerSettingsIn(r *codec.Reader) (*FurnitureGetDimmerSettingsInPacket, error) {
	p := &FurnitureGetDimmerSettingsInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemDimmerSaveIn uint16 = 1648

// FurnitureSaveDimmerInPacket — Save a dimmer preset configuration
type FurnitureSaveDimmerInPacket struct {
	EffectId int32
	Color int32
	Brightness int32
	BackgroundOnly int32
}

func (p *FurnitureSaveDimmerInPacket) HeaderID() uint16 { return HeaderItemDimmerSaveIn }

func (p *FurnitureSaveDimmerInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.EffectId)
	w.WriteInt32(p.Color)
	w.WriteInt32(p.Brightness)
	w.WriteInt32(p.BackgroundOnly)
	return nil
}

func DecodeFurnitureSaveDimmerIn(r *codec.Reader) (*FurnitureSaveDimmerInPacket, error) {
	p := &FurnitureSaveDimmerInPacket{}
	var err error
	if p.EffectId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Color, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Brightness, err = r.ReadInt32(); err != nil { return nil, err }
	if p.BackgroundOnly, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemDimmerToggleIn uint16 = 2296

// FurnitureToggleDimmerInPacket — Toggle the dimmer on or off
type FurnitureToggleDimmerInPacket struct {
	ItemId int32
}

func (p *FurnitureToggleDimmerInPacket) HeaderID() uint16 { return HeaderItemDimmerToggleIn }

func (p *FurnitureToggleDimmerInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureToggleDimmerIn(r *codec.Reader) (*FurnitureToggleDimmerInPacket, error) {
	p := &FurnitureToggleDimmerInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderWiredOpenIn uint16 = 768

// FurnitureOpenWiredInPacket — Open a wired furniture item for editing
type FurnitureOpenWiredInPacket struct {
	ItemId int32
}

func (p *FurnitureOpenWiredInPacket) HeaderID() uint16 { return HeaderWiredOpenIn }

func (p *FurnitureOpenWiredInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureOpenWiredIn(r *codec.Reader) (*FurnitureOpenWiredInPacket, error) {
	p := &FurnitureOpenWiredInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderWiredTriggerSaveIn uint16 = 1520

// FurnitureSaveWiredTriggerInPacket — Save wired trigger configuration
type FurnitureSaveWiredTriggerInPacket struct {
	ItemId int32
	Delay int32
	SelectedItems []int32
	TriggerTypeId int32
	TriggerData string
}

func (p *FurnitureSaveWiredTriggerInPacket) HeaderID() uint16 { return HeaderWiredTriggerSaveIn }

func (p *FurnitureSaveWiredTriggerInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.Delay)
	w.WriteListInt32(p.SelectedItems)
	w.WriteInt32(p.TriggerTypeId)
	w.WriteString(p.TriggerData)
	return nil
}

func DecodeFurnitureSaveWiredTriggerIn(r *codec.Reader) (*FurnitureSaveWiredTriggerInPacket, error) {
	p := &FurnitureSaveWiredTriggerInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Delay, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SelectedItems, err = r.ReadListInt32(); err != nil { return nil, err }
	if p.TriggerTypeId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.TriggerData, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderWiredConditionSaveIn uint16 = 3203

// FurnitureSaveWiredConditionInPacket — Save wired condition configuration
type FurnitureSaveWiredConditionInPacket struct {
	ItemId int32
	SelectedItems []int32
	ConditionTypeId int32
	ConditionData string
}

func (p *FurnitureSaveWiredConditionInPacket) HeaderID() uint16 { return HeaderWiredConditionSaveIn }

func (p *FurnitureSaveWiredConditionInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteListInt32(p.SelectedItems)
	w.WriteInt32(p.ConditionTypeId)
	w.WriteString(p.ConditionData)
	return nil
}

func DecodeFurnitureSaveWiredConditionIn(r *codec.Reader) (*FurnitureSaveWiredConditionInPacket, error) {
	p := &FurnitureSaveWiredConditionInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SelectedItems, err = r.ReadListInt32(); err != nil { return nil, err }
	if p.ConditionTypeId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ConditionData, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderWiredActionSaveIn uint16 = 2281

// FurnitureSaveWiredActionInPacket — Save wired action configuration
type FurnitureSaveWiredActionInPacket struct {
	ItemId int32
	Delay int32
	SelectedItems []int32
	ActionTypeId int32
	ActionData string
}

func (p *FurnitureSaveWiredActionInPacket) HeaderID() uint16 { return HeaderWiredActionSaveIn }

func (p *FurnitureSaveWiredActionInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.Delay)
	w.WriteListInt32(p.SelectedItems)
	w.WriteInt32(p.ActionTypeId)
	w.WriteString(p.ActionData)
	return nil
}

func DecodeFurnitureSaveWiredActionIn(r *codec.Reader) (*FurnitureSaveWiredActionInPacket, error) {
	p := &FurnitureSaveWiredActionInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Delay, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SelectedItems, err = r.ReadListInt32(); err != nil { return nil, err }
	if p.ActionTypeId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ActionData, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderWiredApplySnapshotIn uint16 = 3373

// FurnitureApplyWiredSnapshotInPacket — Apply a wired configuration snapshot to multiple items
type FurnitureApplyWiredSnapshotInPacket struct {
	ItemId int32
}

func (p *FurnitureApplyWiredSnapshotInPacket) HeaderID() uint16 { return HeaderWiredApplySnapshotIn }

func (p *FurnitureApplyWiredSnapshotInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureApplyWiredSnapshotIn(r *codec.Reader) (*FurnitureApplyWiredSnapshotInPacket, error) {
	p := &FurnitureApplyWiredSnapshotInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurniturePostitPlaceIn uint16 = 2248

// FurniturePlacePostitInPacket — Place a post-it note on the room wall
type FurniturePlacePostitInPacket struct {
	ItemId int32
	WallPosition string
}

func (p *FurniturePlacePostitInPacket) HeaderID() uint16 { return HeaderFurniturePostitPlaceIn }

func (p *FurniturePlacePostitInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteString(p.WallPosition)
	return nil
}

func DecodeFurniturePlacePostitIn(r *codec.Reader) (*FurniturePlacePostitInPacket, error) {
	p := &FurniturePlacePostitInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.WallPosition, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurniturePostitSaveStickyPoleIn uint16 = 3283

// FurnitureSavePostitInPacket — Save the content of a post-it note
type FurnitureSavePostitInPacket struct {
	ItemId int32
	Color string
	Text string
}

func (p *FurnitureSavePostitInPacket) HeaderID() uint16 { return HeaderFurniturePostitSaveStickyPoleIn }

func (p *FurnitureSavePostitInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteString(p.Color)
	w.WriteString(p.Text)
	return nil
}

func DecodeFurnitureSavePostitIn(r *codec.Reader) (*FurnitureSavePostitInPacket, error) {
	p := &FurnitureSavePostitInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Color, err = r.ReadString(); err != nil { return nil, err }
	if p.Text, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomTonerApplyIn uint16 = 2880

// FurnitureApplyTonerInPacket — Apply background toner settings
type FurnitureApplyTonerInPacket struct {
	ItemId int32
	Enabled int32
	Hue int32
	Saturation int32
	Value int32
}

func (p *FurnitureApplyTonerInPacket) HeaderID() uint16 { return HeaderRoomTonerApplyIn }

func (p *FurnitureApplyTonerInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.Enabled)
	w.WriteInt32(p.Hue)
	w.WriteInt32(p.Saturation)
	w.WriteInt32(p.Value)
	return nil
}

func DecodeFurnitureApplyTonerIn(r *codec.Reader) (*FurnitureApplyTonerInPacket, error) {
	p := &FurnitureApplyTonerInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Enabled, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Hue, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Saturation, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Value, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMannequinSaveLookIn uint16 = 2209

// FurnitureSaveMannequinLookInPacket — Save the current avatar look to a mannequin
type FurnitureSaveMannequinLookInPacket struct {
	ItemId int32
}

func (p *FurnitureSaveMannequinLookInPacket) HeaderID() uint16 { return HeaderMannequinSaveLookIn }

func (p *FurnitureSaveMannequinLookInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureSaveMannequinLookIn(r *codec.Reader) (*FurnitureSaveMannequinLookInPacket, error) {
	p := &FurnitureSaveMannequinLookInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMannequinSaveNameIn uint16 = 2850

// FurnitureSaveMannequinNameInPacket — Save a name for a mannequin
type FurnitureSaveMannequinNameInPacket struct {
	ItemId int32
	Name string
}

func (p *FurnitureSaveMannequinNameInPacket) HeaderID() uint16 { return HeaderMannequinSaveNameIn }

func (p *FurnitureSaveMannequinNameInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteString(p.Name)
	return nil
}

func DecodeFurnitureSaveMannequinNameIn(r *codec.Reader) (*FurnitureSaveMannequinNameInPacket, error) {
	p := &FurnitureSaveMannequinNameInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Name, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetYoutubeDisplayStatusIn uint16 = 336

// FurnitureGetYoutubeStatusInPacket — Request the current YouTube display status
type FurnitureGetYoutubeStatusInPacket struct {
	ItemId int32
}

func (p *FurnitureGetYoutubeStatusInPacket) HeaderID() uint16 { return HeaderGetYoutubeDisplayStatusIn }

func (p *FurnitureGetYoutubeStatusInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureGetYoutubeStatusIn(r *codec.Reader) (*FurnitureGetYoutubeStatusInPacket, error) {
	p := &FurnitureGetYoutubeStatusInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderControlYoutubeDisplayPlaybackIn uint16 = 3005

// FurnitureControlYoutubeInPacket — Control YouTube display playback
type FurnitureControlYoutubeInPacket struct {
	ItemId int32
	Action int32
}

func (p *FurnitureControlYoutubeInPacket) HeaderID() uint16 { return HeaderControlYoutubeDisplayPlaybackIn }

func (p *FurnitureControlYoutubeInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.Action)
	return nil
}

func DecodeFurnitureControlYoutubeIn(r *codec.Reader) (*FurnitureControlYoutubeInPacket, error) {
	p := &FurnitureControlYoutubeInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Action, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderSetYoutubeDisplayPlaylistIn uint16 = 2069

// FurnitureSetYoutubePlaylistInPacket — Set the active YouTube playlist
type FurnitureSetYoutubePlaylistInPacket struct {
	ItemId int32
	PlaylistId string
}

func (p *FurnitureSetYoutubePlaylistInPacket) HeaderID() uint16 { return HeaderSetYoutubeDisplayPlaylistIn }

func (p *FurnitureSetYoutubePlaylistInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteString(p.PlaylistId)
	return nil
}

func DecodeFurnitureSetYoutubePlaylistIn(r *codec.Reader) (*FurnitureSetYoutubePlaylistInPacket, error) {
	p := &FurnitureSetYoutubePlaylistInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PlaylistId, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemDiceClickIn uint16 = 1990

// FurnitureActivateDiceInPacket — Activate a dice item to roll it
type FurnitureActivateDiceInPacket struct {
	ItemId int32
}

func (p *FurnitureActivateDiceInPacket) HeaderID() uint16 { return HeaderItemDiceClickIn }

func (p *FurnitureActivateDiceInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureActivateDiceIn(r *codec.Reader) (*FurnitureActivateDiceInPacket, error) {
	p := &FurnitureActivateDiceInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemDiceCloseIn uint16 = 1533

// FurnitureDeactivateDiceInPacket — Stop or close a dice item
type FurnitureDeactivateDiceInPacket struct {
	ItemId int32
}

func (p *FurnitureDeactivateDiceInPacket) HeaderID() uint16 { return HeaderItemDiceCloseIn }

func (p *FurnitureDeactivateDiceInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureDeactivateDiceIn(r *codec.Reader) (*FurnitureDeactivateDiceInPacket, error) {
	p := &FurnitureDeactivateDiceInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureMultistateIn uint16 = 99

// FurnitureToggleMultistateInPacket — Toggle the state of a multistate floor furniture item
type FurnitureToggleMultistateInPacket struct {
	ItemId int32
}

func (p *FurnitureToggleMultistateInPacket) HeaderID() uint16 { return HeaderFurnitureMultistateIn }

func (p *FurnitureToggleMultistateInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureToggleMultistateIn(r *codec.Reader) (*FurnitureToggleMultistateInPacket, error) {
	p := &FurnitureToggleMultistateInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureWallMultistateIn uint16 = 210

// FurnitureToggleWallMultistateInPacket — Toggle the state of a multistate wall furniture item
type FurnitureToggleWallMultistateInPacket struct {
	ItemId int32
}

func (p *FurnitureToggleWallMultistateInPacket) HeaderID() uint16 { return HeaderFurnitureWallMultistateIn }

func (p *FurnitureToggleWallMultistateInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureToggleWallMultistateIn(r *codec.Reader) (*FurnitureToggleWallMultistateInPacket, error) {
	p := &FurnitureToggleWallMultistateInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureRandomstateIn uint16 = 3617

// FurnitureToggleRandomStateInPacket — Trigger a random state change on a furniture item
type FurnitureToggleRandomStateInPacket struct {
	ItemId int32
}

func (p *FurnitureToggleRandomStateInPacket) HeaderID() uint16 { return HeaderFurnitureRandomstateIn }

func (p *FurnitureToggleRandomStateInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureToggleRandomStateIn(r *codec.Reader) (*FurnitureToggleRandomStateInPacket, error) {
	p := &FurnitureToggleRandomStateInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemStackHelperIn uint16 = 3839

// FurnitureSetStackHeightInPacket — Set the stack height of a stack-helper tile
type FurnitureSetStackHeightInPacket struct {
	ItemId int32
	Height int32
}

func (p *FurnitureSetStackHeightInPacket) HeaderID() uint16 { return HeaderItemStackHelperIn }

func (p *FurnitureSetStackHeightInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.Height)
	return nil
}

func DecodeFurnitureSetStackHeightIn(r *codec.Reader) (*FurnitureSetStackHeightInPacket, error) {
	p := &FurnitureSetStackHeightInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Height, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderOneWayDoorClickIn uint16 = 2765

// FurnitureClickOneWayDoorInPacket — Interact with a one-way door furniture item
type FurnitureClickOneWayDoorInPacket struct {
	ItemId int32
}

func (p *FurnitureClickOneWayDoorInPacket) HeaderID() uint16 { return HeaderOneWayDoorClickIn }

func (p *FurnitureClickOneWayDoorInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureClickOneWayDoorIn(r *codec.Reader) (*FurnitureClickOneWayDoorInPacket, error) {
	p := &FurnitureClickOneWayDoorInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemColorWheelClickIn uint16 = 2144

// FurnitureClickColorWheelInPacket — Interact with a color-wheel furniture item
type FurnitureClickColorWheelInPacket struct {
	ItemId int32
}

func (p *FurnitureClickColorWheelInPacket) HeaderID() uint16 { return HeaderItemColorWheelClickIn }

func (p *FurnitureClickColorWheelInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureClickColorWheelIn(r *codec.Reader) (*FurnitureClickColorWheelInPacket, error) {
	p := &FurnitureClickColorWheelInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderBuildersClubPlaceWallItemIn uint16 = 462

// FurnitureBuildersClubPlaceWallItemInPacket — Builders club place wall item
type FurnitureBuildersClubPlaceWallItemInPacket struct {
}

func (p *FurnitureBuildersClubPlaceWallItemInPacket) HeaderID() uint16 { return HeaderBuildersClubPlaceWallItemIn }

func (p *FurnitureBuildersClubPlaceWallItemInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureBuildersClubPlaceWallItemIn(r *codec.Reader) (*FurnitureBuildersClubPlaceWallItemInPacket, error) {
	p := &FurnitureBuildersClubPlaceWallItemInPacket{}
	return p, nil
}

const HeaderItemPaintIn uint16 = 711

// FurnitureItemPaintInPacket — Item paint
type FurnitureItemPaintInPacket struct {
}

func (p *FurnitureItemPaintInPacket) HeaderID() uint16 { return HeaderItemPaintIn }

func (p *FurnitureItemPaintInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureItemPaintIn(r *codec.Reader) (*FurnitureItemPaintInPacket, error) {
	p := &FurnitureItemPaintInPacket{}
	return p, nil
}

const HeaderAddJukeboxDiskIn uint16 = 753

// FurnitureAddJukeboxDiskInPacket — Add jukebox disk
type FurnitureAddJukeboxDiskInPacket struct {
}

func (p *FurnitureAddJukeboxDiskInPacket) HeaderID() uint16 { return HeaderAddJukeboxDiskIn }

func (p *FurnitureAddJukeboxDiskInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureAddJukeboxDiskIn(r *codec.Reader) (*FurnitureAddJukeboxDiskInPacket, error) {
	p := &FurnitureAddJukeboxDiskInPacket{}
	return p, nil
}

const HeaderRentableSpaceStatusIn uint16 = 872

// FurnitureRentableSpaceStatusInPacket — Rentable space status
type FurnitureRentableSpaceStatusInPacket struct {
}

func (p *FurnitureRentableSpaceStatusInPacket) HeaderID() uint16 { return HeaderRentableSpaceStatusIn }

func (p *FurnitureRentableSpaceStatusInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureRentableSpaceStatusIn(r *codec.Reader) (*FurnitureRentableSpaceStatusInPacket, error) {
	p := &FurnitureRentableSpaceStatusInPacket{}
	return p, nil
}

const HeaderBuildersClubPlaceRoomItemIn uint16 = 1051

// FurnitureBuildersClubPlaceRoomItemInPacket — Builders club place room item
type FurnitureBuildersClubPlaceRoomItemInPacket struct {
}

func (p *FurnitureBuildersClubPlaceRoomItemInPacket) HeaderID() uint16 { return HeaderBuildersClubPlaceRoomItemIn }

func (p *FurnitureBuildersClubPlaceRoomItemInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureBuildersClubPlaceRoomItemIn(r *codec.Reader) (*FurnitureBuildersClubPlaceRoomItemInPacket, error) {
	p := &FurnitureBuildersClubPlaceRoomItemInPacket{}
	return p, nil
}

const HeaderRentableExtendRentOrBuyoutFurniIn uint16 = 1071

// FurnitureRentableExtendRentOrBuyoutFurniInPacket — Rentable extend rent or buyout furni
type FurnitureRentableExtendRentOrBuyoutFurniInPacket struct {
}

func (p *FurnitureRentableExtendRentOrBuyoutFurniInPacket) HeaderID() uint16 { return HeaderRentableExtendRentOrBuyoutFurniIn }

func (p *FurnitureRentableExtendRentOrBuyoutFurniInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureRentableExtendRentOrBuyoutFurniIn(r *codec.Reader) (*FurnitureRentableExtendRentOrBuyoutFurniInPacket, error) {
	p := &FurnitureRentableExtendRentOrBuyoutFurniInPacket{}
	return p, nil
}

const HeaderGetNowPlayingIn uint16 = 1325

// FurnitureNowPlayingInPacket — Get now playing
type FurnitureNowPlayingInPacket struct {
}

func (p *FurnitureNowPlayingInPacket) HeaderID() uint16 { return HeaderGetNowPlayingIn }

func (p *FurnitureNowPlayingInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureNowPlayingIn(r *codec.Reader) (*FurnitureNowPlayingInPacket, error) {
	p := &FurnitureNowPlayingInPacket{}
	return p, nil
}

const HeaderGetJukeboxPlaylistIn uint16 = 1435

// FurnitureJukeboxPlaylistInPacket — Get jukebox playlist
type FurnitureJukeboxPlaylistInPacket struct {
}

func (p *FurnitureJukeboxPlaylistInPacket) HeaderID() uint16 { return HeaderGetJukeboxPlaylistIn }

func (p *FurnitureJukeboxPlaylistInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureJukeboxPlaylistIn(r *codec.Reader) (*FurnitureJukeboxPlaylistInPacket, error) {
	p := &FurnitureJukeboxPlaylistInPacket{}
	return p, nil
}

const HeaderRentableSpaceCancelRentIn uint16 = 1667

// FurnitureRentableSpaceCancelRentInPacket — Rentable space cancel rent
type FurnitureRentableSpaceCancelRentInPacket struct {
}

func (p *FurnitureRentableSpaceCancelRentInPacket) HeaderID() uint16 { return HeaderRentableSpaceCancelRentIn }

func (p *FurnitureRentableSpaceCancelRentInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureRentableSpaceCancelRentIn(r *codec.Reader) (*FurnitureRentableSpaceCancelRentInPacket, error) {
	p := &FurnitureRentableSpaceCancelRentInPacket{}
	return p, nil
}

const HeaderRentableExtendRentOrBuyoutStripItemIn uint16 = 2115

// FurnitureRentableExtendRentOrBuyoutStripItemInPacket — Rentable extend rent or buyout strip item
type FurnitureRentableExtendRentOrBuyoutStripItemInPacket struct {
}

func (p *FurnitureRentableExtendRentOrBuyoutStripItemInPacket) HeaderID() uint16 { return HeaderRentableExtendRentOrBuyoutStripItemIn }

func (p *FurnitureRentableExtendRentOrBuyoutStripItemInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureRentableExtendRentOrBuyoutStripItemIn(r *codec.Reader) (*FurnitureRentableExtendRentOrBuyoutStripItemInPacket, error) {
	p := &FurnitureRentableExtendRentOrBuyoutStripItemInPacket{}
	return p, nil
}

const HeaderGetUserSongDisksIn uint16 = 2304

// FurnitureUserSongDisksInPacket — Get user song disks
type FurnitureUserSongDisksInPacket struct {
}

func (p *FurnitureUserSongDisksInPacket) HeaderID() uint16 { return HeaderGetUserSongDisksIn }

func (p *FurnitureUserSongDisksInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureUserSongDisksIn(r *codec.Reader) (*FurnitureUserSongDisksInPacket, error) {
	p := &FurnitureUserSongDisksInPacket{}
	return p, nil
}

const HeaderGetSoundSettingsIn uint16 = 2388

// FurnitureSoundSettingsInPacket — Get sound settings
type FurnitureSoundSettingsInPacket struct {
}

func (p *FurnitureSoundSettingsInPacket) HeaderID() uint16 { return HeaderGetSoundSettingsIn }

func (p *FurnitureSoundSettingsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureSoundSettingsIn(r *codec.Reader) (*FurnitureSoundSettingsInPacket, error) {
	p := &FurnitureSoundSettingsInPacket{}
	return p, nil
}

const HeaderRentableGetRentOrBuyoutOfferIn uint16 = 2518

// FurnitureRentableGetRentOrBuyoutOfferInPacket — Rentable get rent or buyout offer
type FurnitureRentableGetRentOrBuyoutOfferInPacket struct {
}

func (p *FurnitureRentableGetRentOrBuyoutOfferInPacket) HeaderID() uint16 { return HeaderRentableGetRentOrBuyoutOfferIn }

func (p *FurnitureRentableGetRentOrBuyoutOfferInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureRentableGetRentOrBuyoutOfferIn(r *codec.Reader) (*FurnitureRentableGetRentOrBuyoutOfferInPacket, error) {
	p := &FurnitureRentableGetRentOrBuyoutOfferInPacket{}
	return p, nil
}

const HeaderWelcomeOpenGiftIn uint16 = 2638

// FurnitureWelcomeOpenGiftInPacket — Welcome open gift
type FurnitureWelcomeOpenGiftInPacket struct {
}

func (p *FurnitureWelcomeOpenGiftInPacket) HeaderID() uint16 { return HeaderWelcomeOpenGiftIn }

func (p *FurnitureWelcomeOpenGiftInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureWelcomeOpenGiftIn(r *codec.Reader) (*FurnitureWelcomeOpenGiftInPacket, error) {
	p := &FurnitureWelcomeOpenGiftInPacket{}
	return p, nil
}

const HeaderFurnitureGroupInfoIn uint16 = 2651

// FurnitureFurnitureGroupInfoInPacket — Furniture group info
type FurnitureFurnitureGroupInfoInPacket struct {
}

func (p *FurnitureFurnitureGroupInfoInPacket) HeaderID() uint16 { return HeaderFurnitureGroupInfoIn }

func (p *FurnitureFurnitureGroupInfoInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureFurnitureGroupInfoIn(r *codec.Reader) (*FurnitureFurnitureGroupInfoInPacket, error) {
	p := &FurnitureFurnitureGroupInfoInPacket{}
	return p, nil
}

const HeaderRentableSpaceRentIn uint16 = 2946

// FurnitureRentableSpaceRentInPacket — Rentable space rent
type FurnitureRentableSpaceRentInPacket struct {
}

func (p *FurnitureRentableSpaceRentInPacket) HeaderID() uint16 { return HeaderRentableSpaceRentIn }

func (p *FurnitureRentableSpaceRentInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureRentableSpaceRentIn(r *codec.Reader) (*FurnitureRentableSpaceRentInPacket, error) {
	p := &FurnitureRentableSpaceRentInPacket{}
	return p, nil
}

const HeaderRemoveJukeboxDiskIn uint16 = 3050

// FurnitureRemoveJukeboxDiskInPacket — Remove jukebox disk
type FurnitureRemoveJukeboxDiskInPacket struct {
}

func (p *FurnitureRemoveJukeboxDiskInPacket) HeaderID() uint16 { return HeaderRemoveJukeboxDiskIn }

func (p *FurnitureRemoveJukeboxDiskInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureRemoveJukeboxDiskIn(r *codec.Reader) (*FurnitureRemoveJukeboxDiskInPacket, error) {
	p := &FurnitureRemoveJukeboxDiskInPacket{}
	return p, nil
}

const HeaderGetSongInfoIn uint16 = 3082

// FurnitureSongInfoInPacket — Get song info
type FurnitureSongInfoInPacket struct {
}

func (p *FurnitureSongInfoInPacket) HeaderID() uint16 { return HeaderGetSongInfoIn }

func (p *FurnitureSongInfoInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureSongInfoIn(r *codec.Reader) (*FurnitureSongInfoInPacket, error) {
	p := &FurnitureSongInfoInPacket{}
	return p, nil
}

const HeaderGetOfficialSongIdIn uint16 = 3189

// FurnitureOfficialSongIdInPacket — Get official song id
type FurnitureOfficialSongIdInPacket struct {
}

func (p *FurnitureOfficialSongIdInPacket) HeaderID() uint16 { return HeaderGetOfficialSongIdIn }

func (p *FurnitureOfficialSongIdInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureOfficialSongIdIn(r *codec.Reader) (*FurnitureOfficialSongIdInPacket, error) {
	p := &FurnitureOfficialSongIdInPacket{}
	return p, nil
}

const HeaderRemoveWallItemIn uint16 = 3336

// FurnitureRemoveWallItemInPacket — Remove wall item
type FurnitureRemoveWallItemInPacket struct {
}

func (p *FurnitureRemoveWallItemInPacket) HeaderID() uint16 { return HeaderRemoveWallItemIn }

func (p *FurnitureRemoveWallItemInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureRemoveWallItemIn(r *codec.Reader) (*FurnitureRemoveWallItemInPacket, error) {
	p := &FurnitureRemoveWallItemInPacket{}
	return p, nil
}

const HeaderGetSoundMachinePlaylistIn uint16 = 3498

// FurnitureSoundMachinePlaylistInPacket — Get sound machine playlist
type FurnitureSoundMachinePlaylistInPacket struct {
}

func (p *FurnitureSoundMachinePlaylistInPacket) HeaderID() uint16 { return HeaderGetSoundMachinePlaylistIn }

func (p *FurnitureSoundMachinePlaylistInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureSoundMachinePlaylistIn(r *codec.Reader) (*FurnitureSoundMachinePlaylistInPacket, error) {
	p := &FurnitureSoundMachinePlaylistInPacket{}
	return p, nil
}

const HeaderPresentOpenPresentIn uint16 = 3558

// FurniturePresentOpenPresentInPacket — Present open present
type FurniturePresentOpenPresentInPacket struct {
}

func (p *FurniturePresentOpenPresentInPacket) HeaderID() uint16 { return HeaderPresentOpenPresentIn }

func (p *FurniturePresentOpenPresentInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurniturePresentOpenPresentIn(r *codec.Reader) (*FurniturePresentOpenPresentInPacket, error) {
	p := &FurniturePresentOpenPresentInPacket{}
	return p, nil
}

const HeaderFriendFurniConfirmLockIn uint16 = 3775

// FurnitureFriendFurniConfirmLockInPacket — Friend furni confirm lock
type FurnitureFriendFurniConfirmLockInPacket struct {
}

func (p *FurnitureFriendFurniConfirmLockInPacket) HeaderID() uint16 { return HeaderFriendFurniConfirmLockIn }

func (p *FurnitureFriendFurniConfirmLockInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureFriendFurniConfirmLockIn(r *codec.Reader) (*FurnitureFriendFurniConfirmLockInPacket, error) {
	p := &FurnitureFriendFurniConfirmLockInPacket{}
	return p, nil
}

const HeaderFurnitureAliasesIn uint16 = 3898

// FurnitureFurnitureAliasesInPacket — Furniture aliases
type FurnitureFurnitureAliasesInPacket struct {
}

func (p *FurnitureFurnitureAliasesInPacket) HeaderID() uint16 { return HeaderFurnitureAliasesIn }

func (p *FurnitureFurnitureAliasesInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureFurnitureAliasesIn(r *codec.Reader) (*FurnitureFurnitureAliasesInPacket, error) {
	p := &FurnitureFurnitureAliasesInPacket{}
	return p, nil
}

const HeaderFurnitureFloorOut uint16 = 1778

// FurnitureFloorItemsOutPacket — Deliver the full list of floor items in the room
type FurnitureFloorItemsOutPacket struct {
	OwnersCount int32
	Owners []byte // TODO: hand-implement nested decode
	ItemCount int32
	Items []byte // TODO: hand-implement nested decode
}

func (p *FurnitureFloorItemsOutPacket) HeaderID() uint16 { return HeaderFurnitureFloorOut }

func (p *FurnitureFloorItemsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OwnersCount)
	w.WriteBytes(p.Owners)
	w.WriteInt32(p.ItemCount)
	w.WriteBytes(p.Items)
	return nil
}

func DecodeFurnitureFloorItemsOut(r *codec.Reader) (*FurnitureFloorItemsOutPacket, error) {
	p := &FurnitureFloorItemsOutPacket{}
	var err error
	if p.OwnersCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Owners, err = r.ReadBytes(); err != nil { return nil, err }
	if p.ItemCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Items, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureFloorAddOut uint16 = 1534

// FurnitureFloorItemAddedOutPacket — Notify that a floor item was placed in the room
type FurnitureFloorItemAddedOutPacket struct {
	OwnerId int32
	OwnerName string
	Item []byte // TODO: hand-implement nested decode
}

func (p *FurnitureFloorItemAddedOutPacket) HeaderID() uint16 { return HeaderFurnitureFloorAddOut }

func (p *FurnitureFloorItemAddedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OwnerId)
	w.WriteString(p.OwnerName)
	w.WriteBytes(p.Item)
	return nil
}

func DecodeFurnitureFloorItemAddedOut(r *codec.Reader) (*FurnitureFloorItemAddedOutPacket, error) {
	p := &FurnitureFloorItemAddedOutPacket{}
	var err error
	if p.OwnerId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.OwnerName, err = r.ReadString(); err != nil { return nil, err }
	if p.Item, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureFloorRemoveOut uint16 = 2703

// FurnitureFloorItemRemovedOutPacket — Notify that a floor item was removed from the room
type FurnitureFloorItemRemovedOutPacket struct {
	ItemId int32
	IsExpired bool
	Delay int32
	UserId int32
}

func (p *FurnitureFloorItemRemovedOutPacket) HeaderID() uint16 { return HeaderFurnitureFloorRemoveOut }

func (p *FurnitureFloorItemRemovedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteBool(p.IsExpired)
	w.WriteInt32(p.Delay)
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeFurnitureFloorItemRemovedOut(r *codec.Reader) (*FurnitureFloorItemRemovedOutPacket, error) {
	p := &FurnitureFloorItemRemovedOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.IsExpired, err = r.ReadBool(); err != nil { return nil, err }
	if p.Delay, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureFloorUpdateOut uint16 = 3776

// FurnitureFloorItemUpdatedOutPacket — Notify that a floor item moved or changed state
type FurnitureFloorItemUpdatedOutPacket struct {
	Item []byte // TODO: hand-implement nested decode
}

func (p *FurnitureFloorItemUpdatedOutPacket) HeaderID() uint16 { return HeaderFurnitureFloorUpdateOut }

func (p *FurnitureFloorItemUpdatedOutPacket) Encode(w *codec.Writer) error {
	w.WriteBytes(p.Item)
	return nil
}

func DecodeFurnitureFloorItemUpdatedOut(r *codec.Reader) (*FurnitureFloorItemUpdatedOutPacket, error) {
	p := &FurnitureFloorItemUpdatedOutPacket{}
	var err error
	if p.Item, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemWallOut uint16 = 1369

// FurnitureWallItemsOutPacket — Deliver the full list of wall items in the room
type FurnitureWallItemsOutPacket struct {
	OwnersCount int32
	Owners []byte // TODO: hand-implement nested decode
	ItemCount int32
	Items []byte // TODO: hand-implement nested decode
}

func (p *FurnitureWallItemsOutPacket) HeaderID() uint16 { return HeaderItemWallOut }

func (p *FurnitureWallItemsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OwnersCount)
	w.WriteBytes(p.Owners)
	w.WriteInt32(p.ItemCount)
	w.WriteBytes(p.Items)
	return nil
}

func DecodeFurnitureWallItemsOut(r *codec.Reader) (*FurnitureWallItemsOutPacket, error) {
	p := &FurnitureWallItemsOutPacket{}
	var err error
	if p.OwnersCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Owners, err = r.ReadBytes(); err != nil { return nil, err }
	if p.ItemCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Items, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemWallAddOut uint16 = 2187

// FurnitureWallItemAddedOutPacket — Notify that a wall item was placed in the room
type FurnitureWallItemAddedOutPacket struct {
	OwnerId int32
	OwnerName string
	Item []byte // TODO: hand-implement nested decode
}

func (p *FurnitureWallItemAddedOutPacket) HeaderID() uint16 { return HeaderItemWallAddOut }

func (p *FurnitureWallItemAddedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OwnerId)
	w.WriteString(p.OwnerName)
	w.WriteBytes(p.Item)
	return nil
}

func DecodeFurnitureWallItemAddedOut(r *codec.Reader) (*FurnitureWallItemAddedOutPacket, error) {
	p := &FurnitureWallItemAddedOutPacket{}
	var err error
	if p.OwnerId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.OwnerName, err = r.ReadString(); err != nil { return nil, err }
	if p.Item, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemWallRemoveOut uint16 = 3208

// FurnitureWallItemRemovedOutPacket — Notify that a wall item was removed from the room
type FurnitureWallItemRemovedOutPacket struct {
	ItemId int32
	UserId int32
}

func (p *FurnitureWallItemRemovedOutPacket) HeaderID() uint16 { return HeaderItemWallRemoveOut }

func (p *FurnitureWallItemRemovedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeFurnitureWallItemRemovedOut(r *codec.Reader) (*FurnitureWallItemRemovedOutPacket, error) {
	p := &FurnitureWallItemRemovedOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemWallUpdateOut uint16 = 2009

// FurnitureWallItemUpdatedOutPacket — Notify that a wall item changed state
type FurnitureWallItemUpdatedOutPacket struct {
	Item []byte // TODO: hand-implement nested decode
}

func (p *FurnitureWallItemUpdatedOutPacket) HeaderID() uint16 { return HeaderItemWallUpdateOut }

func (p *FurnitureWallItemUpdatedOutPacket) Encode(w *codec.Writer) error {
	w.WriteBytes(p.Item)
	return nil
}

func DecodeFurnitureWallItemUpdatedOut(r *codec.Reader) (*FurnitureWallItemUpdatedOutPacket, error) {
	p := &FurnitureWallItemUpdatedOutPacket{}
	var err error
	if p.Item, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureAliasesOut uint16 = 1723

// FurnitureAliasesOutPacket — Deliver furniture alias name mappings
type FurnitureAliasesOutPacket struct {
	Count int32
	Aliases []byte // TODO: hand-implement nested decode
}

func (p *FurnitureAliasesOutPacket) HeaderID() uint16 { return HeaderFurnitureAliasesOut }

func (p *FurnitureAliasesOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Count)
	w.WriteBytes(p.Aliases)
	return nil
}

func DecodeFurnitureAliasesOut(r *codec.Reader) (*FurnitureAliasesOutPacket, error) {
	p := &FurnitureAliasesOutPacket{}
	var err error
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Aliases, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureDataOut uint16 = 2547

// FurnitureDataOutPacket — Deliver interaction data for multiple furniture items
type FurnitureDataOutPacket struct {
	UniqueId int32
	FloorItemCount int32
	FloorItems []byte // TODO: hand-implement nested decode
	WallItemCount int32
	WallItems []byte // TODO: hand-implement nested decode
}

func (p *FurnitureDataOutPacket) HeaderID() uint16 { return HeaderFurnitureDataOut }

func (p *FurnitureDataOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UniqueId)
	w.WriteInt32(p.FloorItemCount)
	w.WriteBytes(p.FloorItems)
	w.WriteInt32(p.WallItemCount)
	w.WriteBytes(p.WallItems)
	return nil
}

func DecodeFurnitureDataOut(r *codec.Reader) (*FurnitureDataOutPacket, error) {
	p := &FurnitureDataOutPacket{}
	var err error
	if p.UniqueId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FloorItemCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FloorItems, err = r.ReadBytes(); err != nil { return nil, err }
	if p.WallItemCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.WallItems, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureItemdataOut uint16 = 2202

// FurnitureItemDataUpdatedOutPacket — Notify that a single item's data changed
type FurnitureItemDataUpdatedOutPacket struct {
	ItemId int32
	DataType int32
	Data string
}

func (p *FurnitureItemDataUpdatedOutPacket) HeaderID() uint16 { return HeaderFurnitureItemdataOut }

func (p *FurnitureItemDataUpdatedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.DataType)
	w.WriteString(p.Data)
	return nil
}

func DecodeFurnitureItemDataUpdatedOut(r *codec.Reader) (*FurnitureItemDataUpdatedOutPacket, error) {
	p := &FurnitureItemDataUpdatedOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.DataType, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Data, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemStackHelperOut uint16 = 2816

// FurnitureStackHeightOutPacket — Deliver the effective stack height of a tile
type FurnitureStackHeightOutPacket struct {
	ItemId int32
	Height int32
}

func (p *FurnitureStackHeightOutPacket) HeaderID() uint16 { return HeaderItemStackHelperOut }

func (p *FurnitureStackHeightOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.Height)
	return nil
}

func DecodeFurnitureStackHeightOut(r *codec.Reader) (*FurnitureStackHeightOutPacket, error) {
	p := &FurnitureStackHeightOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Height, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureStateOut uint16 = 2376

// FurnitureStateOutPacket — Deliver the state of a furniture item (one-way door)
type FurnitureStateOutPacket struct {
	ItemId int32
	State int32
}

func (p *FurnitureStateOutPacket) HeaderID() uint16 { return HeaderFurnitureStateOut }

func (p *FurnitureStateOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.State)
	return nil
}

func DecodeFurnitureStateOut(r *codec.Reader) (*FurnitureStateOutPacket, error) {
	p := &FurnitureStateOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.State, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderItemDimmerSettingsOut uint16 = 2710

// FurnitureDimmerPresetsOutPacket — Deliver the dimmer preset configuration
type FurnitureDimmerPresetsOutPacket struct {
	PresetCount int32
	CurrentPreset int32
	Presets []byte // TODO: hand-implement nested decode
}

func (p *FurnitureDimmerPresetsOutPacket) HeaderID() uint16 { return HeaderItemDimmerSettingsOut }

func (p *FurnitureDimmerPresetsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PresetCount)
	w.WriteInt32(p.CurrentPreset)
	w.WriteBytes(p.Presets)
	return nil
}

func DecodeFurnitureDimmerPresetsOut(r *codec.Reader) (*FurnitureDimmerPresetsOutPacket, error) {
	p := &FurnitureDimmerPresetsOutPacket{}
	var err error
	if p.PresetCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.CurrentPreset, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Presets, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurnitureState2Out uint16 = 3431

// FurnitureDiceValueOutPacket — Deliver a dice roll result
type FurnitureDiceValueOutPacket struct {
	ItemId int32
	Value int32
}

func (p *FurnitureDiceValueOutPacket) HeaderID() uint16 { return HeaderFurnitureState2Out }

func (p *FurnitureDiceValueOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.Value)
	return nil
}

func DecodeFurnitureDiceValueOut(r *codec.Reader) (*FurnitureDiceValueOutPacket, error) {
	p := &FurnitureDiceValueOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Value, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderLovelockFurniFinishedOut uint16 = 770

// FurnitureLovelockFinishedOutPacket — Notify that the love lock sequence completed
type FurnitureLovelockFinishedOutPacket struct {
	ItemId int32
}

func (p *FurnitureLovelockFinishedOutPacket) HeaderID() uint16 { return HeaderLovelockFurniFinishedOut }

func (p *FurnitureLovelockFinishedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureLovelockFinishedOut(r *codec.Reader) (*FurnitureLovelockFinishedOutPacket, error) {
	p := &FurnitureLovelockFinishedOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderLovelockFurniFriendComfirmedOut uint16 = 382

// FurnitureLovelockFriendConfirmedOutPacket — Notify that the second user confirmed the love lock
type FurnitureLovelockFriendConfirmedOutPacket struct {
	ItemId int32
}

func (p *FurnitureLovelockFriendConfirmedOutPacket) HeaderID() uint16 { return HeaderLovelockFurniFriendComfirmedOut }

func (p *FurnitureLovelockFriendConfirmedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeFurnitureLovelockFriendConfirmedOut(r *codec.Reader) (*FurnitureLovelockFriendConfirmedOutPacket, error) {
	p := &FurnitureLovelockFriendConfirmedOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderLovelockFurniStartOut uint16 = 3753

// FurnitureLovelockStartOutPacket — Initiate the love lock sequence
type FurnitureLovelockStartOutPacket struct {
	ItemId int32
	InitiatorName string
	PartnerName string
}

func (p *FurnitureLovelockStartOutPacket) HeaderID() uint16 { return HeaderLovelockFurniStartOut }

func (p *FurnitureLovelockStartOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteString(p.InitiatorName)
	w.WriteString(p.PartnerName)
	return nil
}

func DecodeFurnitureLovelockStartOut(r *codec.Reader) (*FurnitureLovelockStartOutPacket, error) {
	p := &FurnitureLovelockStartOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.InitiatorName, err = r.ReadString(); err != nil { return nil, err }
	if p.PartnerName, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderFurniturePostitStickyPoleOpenOut uint16 = 2366

// FurniturePostitOpenOutPacket — Notify that a post-it sticky pole is ready for writing
type FurniturePostitOpenOutPacket struct {
	ItemId int32
	Color string
	Text string
}

func (p *FurniturePostitOpenOutPacket) HeaderID() uint16 { return HeaderFurniturePostitStickyPoleOpenOut }

func (p *FurniturePostitOpenOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteString(p.Color)
	w.WriteString(p.Text)
	return nil
}

func DecodeFurniturePostitOpenOut(r *codec.Reader) (*FurniturePostitOpenOutPacket, error) {
	p := &FurniturePostitOpenOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Color, err = r.ReadString(); err != nil { return nil, err }
	if p.Text, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderWiredActionOut uint16 = 1434

// FurnitureWiredActionOutPacket — Deliver wired action configuration
type FurnitureWiredActionOutPacket struct {
	ItemId int32
	Delay int32
	SelectedItems []int32
	ActionTypeId int32
	ActionData string
}

func (p *FurnitureWiredActionOutPacket) HeaderID() uint16 { return HeaderWiredActionOut }

func (p *FurnitureWiredActionOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.Delay)
	w.WriteListInt32(p.SelectedItems)
	w.WriteInt32(p.ActionTypeId)
	w.WriteString(p.ActionData)
	return nil
}

func DecodeFurnitureWiredActionOut(r *codec.Reader) (*FurnitureWiredActionOutPacket, error) {
	p := &FurnitureWiredActionOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Delay, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SelectedItems, err = r.ReadListInt32(); err != nil { return nil, err }
	if p.ActionTypeId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ActionData, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderWiredConditionOut uint16 = 1108

// FurnitureWiredConditionOutPacket — Deliver wired condition configuration
type FurnitureWiredConditionOutPacket struct {
	ItemId int32
	SelectedItems []int32
	ConditionTypeId int32
	ConditionData string
}

func (p *FurnitureWiredConditionOutPacket) HeaderID() uint16 { return HeaderWiredConditionOut }

func (p *FurnitureWiredConditionOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteListInt32(p.SelectedItems)
	w.WriteInt32(p.ConditionTypeId)
	w.WriteString(p.ConditionData)
	return nil
}

func DecodeFurnitureWiredConditionOut(r *codec.Reader) (*FurnitureWiredConditionOutPacket, error) {
	p := &FurnitureWiredConditionOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SelectedItems, err = r.ReadListInt32(); err != nil { return nil, err }
	if p.ConditionTypeId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ConditionData, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderWiredTriggerOut uint16 = 383

// FurnitureWiredTriggerOutPacket — Deliver wired trigger configuration
type FurnitureWiredTriggerOutPacket struct {
	ItemId int32
	Delay int32
	SelectedItems []int32
	TriggerTypeId int32
	TriggerData string
}

func (p *FurnitureWiredTriggerOutPacket) HeaderID() uint16 { return HeaderWiredTriggerOut }

func (p *FurnitureWiredTriggerOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.Delay)
	w.WriteListInt32(p.SelectedItems)
	w.WriteInt32(p.TriggerTypeId)
	w.WriteString(p.TriggerData)
	return nil
}

func DecodeFurnitureWiredTriggerOut(r *codec.Reader) (*FurnitureWiredTriggerOutPacket, error) {
	p := &FurnitureWiredTriggerOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Delay, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SelectedItems, err = r.ReadListInt32(); err != nil { return nil, err }
	if p.TriggerTypeId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.TriggerData, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderWiredOpenOut uint16 = 1830

// FurnitureWiredOpenedOutPacket — Confirm that a wired furniture item was opened
type FurnitureWiredOpenedOutPacket struct {
}

func (p *FurnitureWiredOpenedOutPacket) HeaderID() uint16 { return HeaderWiredOpenOut }

func (p *FurnitureWiredOpenedOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureWiredOpenedOut(r *codec.Reader) (*FurnitureWiredOpenedOutPacket, error) {
	p := &FurnitureWiredOpenedOutPacket{}
	return p, nil
}

const HeaderWiredRewardOut uint16 = 178

// FurnitureWiredRewardOutPacket — Deliver a wired reward result to the user
type FurnitureWiredRewardOutPacket struct {
	RewardType int32
	UniqueRewards bool
	BadgeRewards []byte // TODO: hand-implement nested decode
	PrizeRewards []byte // TODO: hand-implement nested decode
}

func (p *FurnitureWiredRewardOutPacket) HeaderID() uint16 { return HeaderWiredRewardOut }

func (p *FurnitureWiredRewardOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RewardType)
	w.WriteBool(p.UniqueRewards)
	w.WriteBytes(p.BadgeRewards)
	w.WriteBytes(p.PrizeRewards)
	return nil
}

func DecodeFurnitureWiredRewardOut(r *codec.Reader) (*FurnitureWiredRewardOutPacket, error) {
	p := &FurnitureWiredRewardOutPacket{}
	var err error
	if p.RewardType, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UniqueRewards, err = r.ReadBool(); err != nil { return nil, err }
	if p.BadgeRewards, err = r.ReadBytes(); err != nil { return nil, err }
	if p.PrizeRewards, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderWiredSaveOut uint16 = 1155

// FurnitureWiredSavedOutPacket — Confirm that wired configuration was saved
type FurnitureWiredSavedOutPacket struct {
}

func (p *FurnitureWiredSavedOutPacket) HeaderID() uint16 { return HeaderWiredSaveOut }

func (p *FurnitureWiredSavedOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureWiredSavedOut(r *codec.Reader) (*FurnitureWiredSavedOutPacket, error) {
	p := &FurnitureWiredSavedOutPacket{}
	return p, nil
}

const HeaderWiredErrorOut uint16 = 156

// FurnitureWiredErrorOutPacket — Indicate a wired configuration validation error
type FurnitureWiredErrorOutPacket struct {
	ErrorCode int32
}

func (p *FurnitureWiredErrorOutPacket) HeaderID() uint16 { return HeaderWiredErrorOut }

func (p *FurnitureWiredErrorOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ErrorCode)
	return nil
}

func DecodeFurnitureWiredErrorOut(r *codec.Reader) (*FurnitureWiredErrorOutPacket, error) {
	p := &FurnitureWiredErrorOutPacket{}
	var err error
	if p.ErrorCode, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderYoutubeControlVideoOut uint16 = 1554

// FurnitureYoutubeControlOutPacket — Relay a YouTube playback control command
type FurnitureYoutubeControlOutPacket struct {
	ItemId int32
	VideoId string
	StartAtSeconds int32
	State int32
}

func (p *FurnitureYoutubeControlOutPacket) HeaderID() uint16 { return HeaderYoutubeControlVideoOut }

func (p *FurnitureYoutubeControlOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteString(p.VideoId)
	w.WriteInt32(p.StartAtSeconds)
	w.WriteInt32(p.State)
	return nil
}

func DecodeFurnitureYoutubeControlOut(r *codec.Reader) (*FurnitureYoutubeControlOutPacket, error) {
	p := &FurnitureYoutubeControlOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.VideoId, err = r.ReadString(); err != nil { return nil, err }
	if p.StartAtSeconds, err = r.ReadInt32(); err != nil { return nil, err }
	if p.State, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderYoutubeDisplayPlaylistsOut uint16 = 1112

// FurnitureYoutubePlaylistsOutPacket — Deliver the available YouTube playlists
type FurnitureYoutubePlaylistsOutPacket struct {
	ItemId int32
	PlaylistCount int32
	Playlists []byte // TODO: hand-implement nested decode
}

func (p *FurnitureYoutubePlaylistsOutPacket) HeaderID() uint16 { return HeaderYoutubeDisplayPlaylistsOut }

func (p *FurnitureYoutubePlaylistsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteInt32(p.PlaylistCount)
	w.WriteBytes(p.Playlists)
	return nil
}

func DecodeFurnitureYoutubePlaylistsOut(r *codec.Reader) (*FurnitureYoutubePlaylistsOutPacket, error) {
	p := &FurnitureYoutubePlaylistsOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PlaylistCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Playlists, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderYoutubeDisplayVideoOut uint16 = 1411

// FurnitureYoutubeVideoOutPacket — Deliver the currently playing YouTube video info
type FurnitureYoutubeVideoOutPacket struct {
	ItemId int32
	VideoId string
	StartAtSeconds int32
	State int32
}

func (p *FurnitureYoutubeVideoOutPacket) HeaderID() uint16 { return HeaderYoutubeDisplayVideoOut }

func (p *FurnitureYoutubeVideoOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteString(p.VideoId)
	w.WriteInt32(p.StartAtSeconds)
	w.WriteInt32(p.State)
	return nil
}

func DecodeFurnitureYoutubeVideoOut(r *codec.Reader) (*FurnitureYoutubeVideoOutPacket, error) {
	p := &FurnitureYoutubeVideoOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.VideoId, err = r.ReadString(); err != nil { return nil, err }
	if p.StartAtSeconds, err = r.ReadInt32(); err != nil { return nil, err }
	if p.State, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRentableSpaceRentOkOut uint16 = 2046

// FurnitureRentableSpaceRentedOutPacket — Confirm successful rentable space rental
type FurnitureRentableSpaceRentedOutPacket struct {
}

func (p *FurnitureRentableSpaceRentedOutPacket) HeaderID() uint16 { return HeaderRentableSpaceRentOkOut }

func (p *FurnitureRentableSpaceRentedOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureRentableSpaceRentedOut(r *codec.Reader) (*FurnitureRentableSpaceRentedOutPacket, error) {
	p := &FurnitureRentableSpaceRentedOutPacket{}
	return p, nil
}

const HeaderRentableSpaceStatusOut uint16 = 3559

// FurnitureRentableSpaceStatusOutPacket — Deliver the current status of a rentable space
type FurnitureRentableSpaceStatusOutPacket struct {
	ItemId int32
	IsRented bool
	IsOwner bool
	RenterId int32
	RenterName string
}

func (p *FurnitureRentableSpaceStatusOutPacket) HeaderID() uint16 { return HeaderRentableSpaceStatusOut }

func (p *FurnitureRentableSpaceStatusOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteBool(p.IsRented)
	w.WriteBool(p.IsOwner)
	w.WriteInt32(p.RenterId)
	w.WriteString(p.RenterName)
	return nil
}

func DecodeFurnitureRentableSpaceStatusOut(r *codec.Reader) (*FurnitureRentableSpaceStatusOutPacket, error) {
	p := &FurnitureRentableSpaceStatusOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.IsRented, err = r.ReadBool(); err != nil { return nil, err }
	if p.IsOwner, err = r.ReadBool(); err != nil { return nil, err }
	if p.RenterId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RenterName, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRentableSpaceRentFailedOut uint16 = 1868

// FurnitureRentableSpaceRentFailedOutPacket — Indicate that rentable space rental failed
type FurnitureRentableSpaceRentFailedOutPacket struct {
	ErrorCode int32
}

func (p *FurnitureRentableSpaceRentFailedOutPacket) HeaderID() uint16 { return HeaderRentableSpaceRentFailedOut }

func (p *FurnitureRentableSpaceRentFailedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ErrorCode)
	return nil
}

func DecodeFurnitureRentableSpaceRentFailedOut(r *codec.Reader) (*FurnitureRentableSpaceRentFailedOutPacket, error) {
	p := &FurnitureRentableSpaceRentFailedOutPacket{}
	var err error
	if p.ErrorCode, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomRollingOut uint16 = 3207

// FurnitureRollingOutPacket — Animate items or units rolling across the floor
type FurnitureRollingOutPacket struct {
	RollerItemId int32
	RollerX int32
	RollerY int32
	RollerZ string
	MovedUnitCount int32
	Units []byte // TODO: hand-implement nested decode
	MovedItemCount int32
	Items []byte // TODO: hand-implement nested decode
	TargetX int32
	TargetY int32
}

func (p *FurnitureRollingOutPacket) HeaderID() uint16 { return HeaderRoomRollingOut }

func (p *FurnitureRollingOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RollerItemId)
	w.WriteInt32(p.RollerX)
	w.WriteInt32(p.RollerY)
	w.WriteString(p.RollerZ)
	w.WriteInt32(p.MovedUnitCount)
	w.WriteBytes(p.Units)
	w.WriteInt32(p.MovedItemCount)
	w.WriteBytes(p.Items)
	w.WriteInt32(p.TargetX)
	w.WriteInt32(p.TargetY)
	return nil
}

func DecodeFurnitureRollingOut(r *codec.Reader) (*FurnitureRollingOutPacket, error) {
	p := &FurnitureRollingOutPacket{}
	var err error
	if p.RollerItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RollerX, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RollerY, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RollerZ, err = r.ReadString(); err != nil { return nil, err }
	if p.MovedUnitCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Units, err = r.ReadBytes(); err != nil { return nil, err }
	if p.MovedItemCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Items, err = r.ReadBytes(); err != nil { return nil, err }
	if p.TargetX, err = r.ReadInt32(); err != nil { return nil, err }
	if p.TargetY, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderJukeboxSongDisksOut uint16 = 34

// FurnitureJukeboxSongDisksOutPacket — Jukebox song disks
type FurnitureJukeboxSongDisksOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 int32
	Field4 int32
}

func (p *FurnitureJukeboxSongDisksOutPacket) HeaderID() uint16 { return HeaderJukeboxSongDisksOut }

func (p *FurnitureJukeboxSongDisksOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteInt32(p.Field3)
	w.WriteInt32(p.Field4)
	return nil
}

func DecodeFurnitureJukeboxSongDisksOut(r *codec.Reader) (*FurnitureJukeboxSongDisksOutPacket, error) {
	p := &FurnitureJukeboxSongDisksOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field4, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGiftOpenedOut uint16 = 56

// FurnitureGiftOpenedOutPacket — Gift opened
type FurnitureGiftOpenedOutPacket struct {
}

func (p *FurnitureGiftOpenedOutPacket) HeaderID() uint16 { return HeaderGiftOpenedOut }

func (p *FurnitureGiftOpenedOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureGiftOpenedOut(r *codec.Reader) (*FurnitureGiftOpenedOutPacket, error) {
	p := &FurnitureGiftOpenedOutPacket{}
	return p, nil
}

const HeaderJukeboxPlaylistFullOut uint16 = 105

// FurnitureJukeboxPlaylistFullOutPacket — Jukebox playlist full
type FurnitureJukeboxPlaylistFullOutPacket struct {
}

func (p *FurnitureJukeboxPlaylistFullOutPacket) HeaderID() uint16 { return HeaderJukeboxPlaylistFullOut }

func (p *FurnitureJukeboxPlaylistFullOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureJukeboxPlaylistFullOut(r *codec.Reader) (*FurnitureJukeboxPlaylistFullOutPacket, error) {
	p := &FurnitureJukeboxPlaylistFullOutPacket{}
	return p, nil
}

const HeaderLimitedSoldOutOut uint16 = 377

// FurnitureLimitedSoldOutOutPacket — Limited sold out
type FurnitureLimitedSoldOutOutPacket struct {
}

func (p *FurnitureLimitedSoldOutOutPacket) HeaderID() uint16 { return HeaderLimitedSoldOutOut }

func (p *FurnitureLimitedSoldOutOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureLimitedSoldOutOut(r *codec.Reader) (*FurnitureLimitedSoldOutOutPacket, error) {
	p := &FurnitureLimitedSoldOutOutPacket{}
	return p, nil
}

const HeaderNowPlayingOut uint16 = 469

// FurnitureNowPlayingOutPacket — Now playing
type FurnitureNowPlayingOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 int32
	Field4 int32
	Field5 int32
}

func (p *FurnitureNowPlayingOutPacket) HeaderID() uint16 { return HeaderNowPlayingOut }

func (p *FurnitureNowPlayingOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteInt32(p.Field3)
	w.WriteInt32(p.Field4)
	w.WriteInt32(p.Field5)
	return nil
}

func DecodeFurnitureNowPlayingOut(r *codec.Reader) (*FurnitureNowPlayingOutPacket, error) {
	p := &FurnitureNowPlayingOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field4, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field5, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPlaylistSongAddedOut uint16 = 1140

// FurniturePlaylistSongAddedOutPacket — Playlist song added
type FurniturePlaylistSongAddedOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 string
	Field4 string
}

func (p *FurniturePlaylistSongAddedOutPacket) HeaderID() uint16 { return HeaderPlaylistSongAddedOut }

func (p *FurniturePlaylistSongAddedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteString(p.Field3)
	w.WriteString(p.Field4)
	return nil
}

func DecodeFurniturePlaylistSongAddedOut(r *codec.Reader) (*FurniturePlaylistSongAddedOutPacket, error) {
	p := &FurniturePlaylistSongAddedOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadString(); err != nil { return nil, err }
	if p.Field4, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderOfficialSongIdOut uint16 = 1381

// FurnitureOfficialSongIdOutPacket — Official song id
type FurnitureOfficialSongIdOutPacket struct {
	Field1 string
	Field2 int32
}

func (p *FurnitureOfficialSongIdOutPacket) HeaderID() uint16 { return HeaderOfficialSongIdOut }

func (p *FurnitureOfficialSongIdOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeFurnitureOfficialSongIdOut(r *codec.Reader) (*FurnitureOfficialSongIdOutPacket, error) {
	p := &FurnitureOfficialSongIdOutPacket{}
	var err error
	if p.Field1, err = r.ReadString(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderObjectsDataUpdateOut uint16 = 1453

// FurnitureObjectsDataUpdateOutPacket — Objects data update
type FurnitureObjectsDataUpdateOutPacket struct {
	Field1 int32
	Field2 int32
}

func (p *FurnitureObjectsDataUpdateOutPacket) HeaderID() uint16 { return HeaderObjectsDataUpdateOut }

func (p *FurnitureObjectsDataUpdateOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeFurnitureObjectsDataUpdateOut(r *codec.Reader) (*FurnitureObjectsDataUpdateOutPacket, error) {
	p := &FurnitureObjectsDataUpdateOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserFurniturePostitPlacedOut uint16 = 1501

// FurnitureUserFurniturePostitPlacedOutPacket — User furniture postit placed
type FurnitureUserFurniturePostitPlacedOutPacket struct {
}

func (p *FurnitureUserFurniturePostitPlacedOutPacket) HeaderID() uint16 { return HeaderUserFurniturePostitPlacedOut }

func (p *FurnitureUserFurniturePostitPlacedOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureUserFurniturePostitPlacedOut(r *codec.Reader) (*FurnitureUserFurniturePostitPlacedOutPacket, error) {
	p := &FurnitureUserFurniturePostitPlacedOutPacket{}
	return p, nil
}

const HeaderPlaylistOut uint16 = 1748

// FurniturePlaylistOutPacket — Playlist
type FurniturePlaylistOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 int32
	Field4 int32
	Field5 string
	Field6 string
}

func (p *FurniturePlaylistOutPacket) HeaderID() uint16 { return HeaderPlaylistOut }

func (p *FurniturePlaylistOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteInt32(p.Field3)
	w.WriteInt32(p.Field4)
	w.WriteString(p.Field5)
	w.WriteString(p.Field6)
	return nil
}

func DecodeFurniturePlaylistOut(r *codec.Reader) (*FurniturePlaylistOutPacket, error) {
	p := &FurniturePlaylistOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field4, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field5, err = r.ReadString(); err != nil { return nil, err }
	if p.Field6, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserSongDisksInventoryOut uint16 = 2602

// FurnitureUserSongDisksInventoryOutPacket — User song disks inventory
type FurnitureUserSongDisksInventoryOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 int32
}

func (p *FurnitureUserSongDisksInventoryOutPacket) HeaderID() uint16 { return HeaderUserSongDisksInventoryOut }

func (p *FurnitureUserSongDisksInventoryOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteInt32(p.Field3)
	return nil
}

func DecodeFurnitureUserSongDisksInventoryOut(r *codec.Reader) (*FurnitureUserSongDisksInventoryOutPacket, error) {
	p := &FurnitureUserSongDisksInventoryOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMysteryBoxKeysOut uint16 = 2833

// FurnitureMysteryBoxKeysOutPacket — Mystery box keys
type FurnitureMysteryBoxKeysOutPacket struct {
	Field1 string
	Field2 string
}

func (p *FurnitureMysteryBoxKeysOutPacket) HeaderID() uint16 { return HeaderMysteryBoxKeysOut }

func (p *FurnitureMysteryBoxKeysOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Field1)
	w.WriteString(p.Field2)
	return nil
}

func DecodeFurnitureMysteryBoxKeysOut(r *codec.Reader) (*FurnitureMysteryBoxKeysOutPacket, error) {
	p := &FurnitureMysteryBoxKeysOutPacket{}
	var err error
	if p.Field1, err = r.ReadString(); err != nil { return nil, err }
	if p.Field2, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderTraxSongInfoOut uint16 = 3365

// FurnitureTraxSongInfoOutPacket — Trax song info
type FurnitureTraxSongInfoOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 string
	Field4 string
	Field5 string
	Field6 int32
	Field7 string
}

func (p *FurnitureTraxSongInfoOutPacket) HeaderID() uint16 { return HeaderTraxSongInfoOut }

func (p *FurnitureTraxSongInfoOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteString(p.Field3)
	w.WriteString(p.Field4)
	w.WriteString(p.Field5)
	w.WriteInt32(p.Field6)
	w.WriteString(p.Field7)
	return nil
}

func DecodeFurnitureTraxSongInfoOut(r *codec.Reader) (*FurnitureTraxSongInfoOutPacket, error) {
	p := &FurnitureTraxSongInfoOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadString(); err != nil { return nil, err }
	if p.Field4, err = r.ReadString(); err != nil { return nil, err }
	if p.Field5, err = r.ReadString(); err != nil { return nil, err }
	if p.Field6, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field7, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderFireworkChargeDataOut uint16 = 5210

// FurnitureFireworkChargeDataOutPacket — Firework charge data
type FurnitureFireworkChargeDataOutPacket struct {
}

func (p *FurnitureFireworkChargeDataOutPacket) HeaderID() uint16 { return HeaderFireworkChargeDataOut }

func (p *FurnitureFireworkChargeDataOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureFireworkChargeDataOut(r *codec.Reader) (*FurnitureFireworkChargeDataOutPacket, error) {
	p := &FurnitureFireworkChargeDataOutPacket{}
	return p, nil
}

