// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderGame2getaccountgamestatusmessageIn uint16 = 11

// GamesGame2getaccountgamestatusmessageInPacket — Game2getaccountgamestatusmessage
type GamesGame2getaccountgamestatusmessageInPacket struct {
}

func (p *GamesGame2getaccountgamestatusmessageInPacket) HeaderID() uint16 { return HeaderGame2getaccountgamestatusmessageIn }

func (p *GamesGame2getaccountgamestatusmessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGame2getaccountgamestatusmessageIn(r *codec.Reader) (*GamesGame2getaccountgamestatusmessageInPacket, error) {
	p := &GamesGame2getaccountgamestatusmessageInPacket{}
	return p, nil
}

const HeaderPollStartIn uint16 = 109

// GamesPollStartInPacket — Poll start
type GamesPollStartInPacket struct {
}

func (p *GamesPollStartInPacket) HeaderID() uint16 { return HeaderPollStartIn }

func (p *GamesPollStartInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesPollStartIn(r *codec.Reader) (*GamesPollStartInPacket, error) {
	p := &GamesPollStartInPacket{}
	return p, nil
}

const HeaderGamesListIn uint16 = 741

// GamesGamesListInPacket — Games list
type GamesGamesListInPacket struct {
}

func (p *GamesGamesListInPacket) HeaderID() uint16 { return HeaderGamesListIn }

func (p *GamesGamesListInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGamesListIn(r *codec.Reader) (*GamesGamesListInPacket, error) {
	p := &GamesGamesListInPacket{}
	return p, nil
}

const HeaderGetweeklygamerewardwinnersIn uint16 = 1054

// GamesGetweeklygamerewardwinnersInPacket — Getweeklygamerewardwinners
type GamesGetweeklygamerewardwinnersInPacket struct {
}

func (p *GamesGetweeklygamerewardwinnersInPacket) HeaderID() uint16 { return HeaderGetweeklygamerewardwinnersIn }

func (p *GamesGetweeklygamerewardwinnersInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGetweeklygamerewardwinnersIn(r *codec.Reader) (*GamesGetweeklygamerewardwinnersInPacket, error) {
	p := &GamesGetweeklygamerewardwinnersInPacket{}
	return p, nil
}

const HeaderGame2getweeklyfriendsleaderboardIn uint16 = 1232

// GamesGame2getweeklyfriendsleaderboardInPacket — Game2getweeklyfriendsleaderboard
type GamesGame2getweeklyfriendsleaderboardInPacket struct {
}

func (p *GamesGame2getweeklyfriendsleaderboardInPacket) HeaderID() uint16 { return HeaderGame2getweeklyfriendsleaderboardIn }

func (p *GamesGame2getweeklyfriendsleaderboardInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGame2getweeklyfriendsleaderboardIn(r *codec.Reader) (*GamesGame2getweeklyfriendsleaderboardInPacket, error) {
	p := &GamesGame2getweeklyfriendsleaderboardInPacket{}
	return p, nil
}

const HeaderGame2exitgamemessageIn uint16 = 1445

// GamesGame2exitgamemessageInPacket — Game2exitgamemessage
type GamesGame2exitgamemessageInPacket struct {
}

func (p *GamesGame2exitgamemessageInPacket) HeaderID() uint16 { return HeaderGame2exitgamemessageIn }

func (p *GamesGame2exitgamemessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGame2exitgamemessageIn(r *codec.Reader) (*GamesGame2exitgamemessageInPacket, error) {
	p := &GamesGame2exitgamemessageInPacket{}
	return p, nil
}

const HeaderJoinqueuemessageIn uint16 = 1458

// GamesJoinqueuemessageInPacket — Joinqueuemessage
type GamesJoinqueuemessageInPacket struct {
}

func (p *GamesJoinqueuemessageInPacket) HeaderID() uint16 { return HeaderJoinqueuemessageIn }

func (p *GamesJoinqueuemessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesJoinqueuemessageIn(r *codec.Reader) (*GamesJoinqueuemessageInPacket, error) {
	p := &GamesJoinqueuemessageInPacket{}
	return p, nil
}

const HeaderGame2requestfullstatusupdatemessageIn uint16 = 1598

// GamesGame2requestfullstatusupdatemessageInPacket — Game2requestfullstatusupdatemessage
type GamesGame2requestfullstatusupdatemessageInPacket struct {
}

func (p *GamesGame2requestfullstatusupdatemessageInPacket) HeaderID() uint16 { return HeaderGame2requestfullstatusupdatemessageIn }

func (p *GamesGame2requestfullstatusupdatemessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGame2requestfullstatusupdatemessageIn(r *codec.Reader) (*GamesGame2requestfullstatusupdatemessageInPacket, error) {
	p := &GamesGame2requestfullstatusupdatemessageInPacket{}
	return p, nil
}

const HeaderPollRejectIn uint16 = 1773

// GamesPollRejectInPacket — Poll reject
type GamesPollRejectInPacket struct {
}

func (p *GamesPollRejectInPacket) HeaderID() uint16 { return HeaderPollRejectIn }

func (p *GamesPollRejectInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesPollRejectIn(r *codec.Reader) (*GamesPollRejectInPacket, error) {
	p := &GamesPollRejectInPacket{}
	return p, nil
}

const HeaderLeavequeuemessageIn uint16 = 2384

// GamesLeavequeuemessageInPacket — Leavequeuemessage
type GamesLeavequeuemessageInPacket struct {
}

func (p *GamesLeavequeuemessageInPacket) HeaderID() uint16 { return HeaderLeavequeuemessageIn }

func (p *GamesLeavequeuemessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesLeavequeuemessageIn(r *codec.Reader) (*GamesLeavequeuemessageInPacket, error) {
	p := &GamesLeavequeuemessageInPacket{}
	return p, nil
}

const HeaderGame2loadstagereadymessageIn uint16 = 2415

// GamesGame2loadstagereadymessageInPacket — Game2loadstagereadymessage
type GamesGame2loadstagereadymessageInPacket struct {
}

func (p *GamesGame2loadstagereadymessageInPacket) HeaderID() uint16 { return HeaderGame2loadstagereadymessageIn }

func (p *GamesGame2loadstagereadymessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGame2loadstagereadymessageIn(r *codec.Reader) (*GamesGame2loadstagereadymessageInPacket, error) {
	p := &GamesGame2loadstagereadymessageInPacket{}
	return p, nil
}

const HeaderGame2gamechatmessageIn uint16 = 2502

// GamesGame2gamechatmessageInPacket — Game2gamechatmessage
type GamesGame2gamechatmessageInPacket struct {
}

func (p *GamesGame2gamechatmessageInPacket) HeaderID() uint16 { return HeaderGame2gamechatmessageIn }

func (p *GamesGame2gamechatmessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGame2gamechatmessageIn(r *codec.Reader) (*GamesGame2gamechatmessageInPacket, error) {
	p := &GamesGame2gamechatmessageInPacket{}
	return p, nil
}

const HeaderGame2getweeklyleaderboardIn uint16 = 2565

// GamesGame2getweeklyleaderboardInPacket — Game2getweeklyleaderboard
type GamesGame2getweeklyleaderboardInPacket struct {
}

func (p *GamesGame2getweeklyleaderboardInPacket) HeaderID() uint16 { return HeaderGame2getweeklyleaderboardIn }

func (p *GamesGame2getweeklyleaderboardInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGame2getweeklyleaderboardIn(r *codec.Reader) (*GamesGame2getweeklyleaderboardInPacket, error) {
	p := &GamesGame2getweeklyleaderboardInPacket{}
	return p, nil
}

const HeaderGamesInitIn uint16 = 2914

// GamesGamesInitInPacket — Games init
type GamesGamesInitInPacket struct {
}

func (p *GamesGamesInitInPacket) HeaderID() uint16 { return HeaderGamesInitIn }

func (p *GamesGamesInitInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGamesInitIn(r *codec.Reader) (*GamesGamesInitInPacket, error) {
	p := &GamesGamesInitInPacket{}
	return p, nil
}

const HeaderGetgamestatusmessageIn uint16 = 3171

// GamesGetgamestatusmessageInPacket — Getgamestatusmessage
type GamesGetgamestatusmessageInPacket struct {
}

func (p *GamesGetgamestatusmessageInPacket) HeaderID() uint16 { return HeaderGetgamestatusmessageIn }

func (p *GamesGetgamestatusmessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGetgamestatusmessageIn(r *codec.Reader) (*GamesGetgamestatusmessageInPacket, error) {
	p := &GamesGetgamestatusmessageInPacket{}
	return p, nil
}

const HeaderGame2playagainmessageIn uint16 = 3196

// GamesGame2playagainmessageInPacket — Game2playagainmessage
type GamesGame2playagainmessageInPacket struct {
}

func (p *GamesGame2playagainmessageInPacket) HeaderID() uint16 { return HeaderGame2playagainmessageIn }

func (p *GamesGame2playagainmessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGame2playagainmessageIn(r *codec.Reader) (*GamesGame2playagainmessageInPacket, error) {
	p := &GamesGame2playagainmessageInPacket{}
	return p, nil
}

const HeaderGameunloadedmessageIn uint16 = 3207

// GamesGameunloadedmessageInPacket — Gameunloadedmessage
type GamesGameunloadedmessageInPacket struct {
}

func (p *GamesGameunloadedmessageInPacket) HeaderID() uint16 { return HeaderGameunloadedmessageIn }

func (p *GamesGameunloadedmessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGameunloadedmessageIn(r *codec.Reader) (*GamesGameunloadedmessageInPacket, error) {
	p := &GamesGameunloadedmessageInPacket{}
	return p, nil
}

const HeaderGame2checkgamedirectorystatusmessageIn uint16 = 3259

// GamesGame2checkgamedirectorystatusmessageInPacket — Game2checkgamedirectorystatusmessage
type GamesGame2checkgamedirectorystatusmessageInPacket struct {
}

func (p *GamesGame2checkgamedirectorystatusmessageInPacket) HeaderID() uint16 { return HeaderGame2checkgamedirectorystatusmessageIn }

func (p *GamesGame2checkgamedirectorystatusmessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGame2checkgamedirectorystatusmessageIn(r *codec.Reader) (*GamesGame2checkgamedirectorystatusmessageInPacket, error) {
	p := &GamesGame2checkgamedirectorystatusmessageInPacket{}
	return p, nil
}

const HeaderPollAnswerIn uint16 = 3505

// GamesPollAnswerInPacket — Poll answer
type GamesPollAnswerInPacket struct {
}

func (p *GamesPollAnswerInPacket) HeaderID() uint16 { return HeaderPollAnswerIn }

func (p *GamesPollAnswerInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesPollAnswerIn(r *codec.Reader) (*GamesPollAnswerInPacket, error) {
	p := &GamesPollAnswerInPacket{}
	return p, nil
}

const HeaderAcceptgameinviteIn uint16 = 3802

// GamesAcceptgameinviteInPacket — Acceptgameinvite
type GamesAcceptgameinviteInPacket struct {
}

func (p *GamesAcceptgameinviteInPacket) HeaderID() uint16 { return HeaderAcceptgameinviteIn }

func (p *GamesAcceptgameinviteInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesAcceptgameinviteIn(r *codec.Reader) (*GamesAcceptgameinviteInPacket, error) {
	p := &GamesAcceptgameinviteInPacket{}
	return p, nil
}

const HeaderPollVoteCounterIn uint16 = 6200

// GamesPollVoteCounterInPacket — Poll vote counter
type GamesPollVoteCounterInPacket struct {
}

func (p *GamesPollVoteCounterInPacket) HeaderID() uint16 { return HeaderPollVoteCounterIn }

func (p *GamesPollVoteCounterInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesPollVoteCounterIn(r *codec.Reader) (*GamesPollVoteCounterInPacket, error) {
	p := &GamesPollVoteCounterInPacket{}
	return p, nil
}

const HeaderGameCenterGameListOut uint16 = 222

// GamesGameCenterGameListOutPacket — Game center game list
type GamesGameCenterGameListOutPacket struct {
}

func (p *GamesGameCenterGameListOutPacket) HeaderID() uint16 { return HeaderGameCenterGameListOut }

func (p *GamesGameCenterGameListOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGameCenterGameListOut(r *codec.Reader) (*GamesGameCenterGameListOutPacket, error) {
	p := &GamesGameCenterGameListOutPacket{}
	return p, nil
}

const HeaderPlayingGameOut uint16 = 448

// GamesPlayingGameOutPacket — Playing game
type GamesPlayingGameOutPacket struct {
	Field1 bool
}

func (p *GamesPlayingGameOutPacket) HeaderID() uint16 { return HeaderPlayingGameOut }

func (p *GamesPlayingGameOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.Field1)
	return nil
}

func DecodeGamesPlayingGameOut(r *codec.Reader) (*GamesPlayingGameOutPacket, error) {
	p := &GamesPlayingGameOutPacket{}
	var err error
	if p.Field1, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderPollErrorOut uint16 = 662

// GamesPollErrorOutPacket — Poll error
type GamesPollErrorOutPacket struct {
}

func (p *GamesPollErrorOutPacket) HeaderID() uint16 { return HeaderPollErrorOut }

func (p *GamesPollErrorOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesPollErrorOut(r *codec.Reader) (*GamesPollErrorOutPacket, error) {
	p := &GamesPollErrorOutPacket{}
	return p, nil
}

const HeaderGameCenterInArenaQueueOut uint16 = 872

// GamesGameCenterInArenaQueueOutPacket — Game center in arena queue
type GamesGameCenterInArenaQueueOutPacket struct {
}

func (p *GamesGameCenterInArenaQueueOutPacket) HeaderID() uint16 { return HeaderGameCenterInArenaQueueOut }

func (p *GamesGameCenterInArenaQueueOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGameCenterInArenaQueueOut(r *codec.Reader) (*GamesGameCenterInArenaQueueOutPacket, error) {
	p := &GamesGameCenterInArenaQueueOutPacket{}
	return p, nil
}

const HeaderGameinviteOut uint16 = 904

// GamesGameinviteOutPacket — Gameinvite
type GamesGameinviteOutPacket struct {
	Field1 int32
	Field2 int32
}

func (p *GamesGameinviteOutPacket) HeaderID() uint16 { return HeaderGameinviteOut }

func (p *GamesGameinviteOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeGamesGameinviteOut(r *codec.Reader) (*GamesGameinviteOutPacket, error) {
	p := &GamesGameinviteOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderLeftqueueOut uint16 = 1477

// GamesLeftqueueOutPacket — Leftqueue
type GamesLeftqueueOutPacket struct {
	Field1 int32
}

func (p *GamesLeftqueueOutPacket) HeaderID() uint16 { return HeaderLeftqueueOut }

func (p *GamesLeftqueueOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	return nil
}

func DecodeGamesLeftqueueOut(r *codec.Reader) (*GamesLeftqueueOutPacket, error) {
	p := &GamesLeftqueueOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnloadgameOut uint16 = 1715

// GamesUnloadgameOutPacket — Unloadgame
type GamesUnloadgameOutPacket struct {
	Field1 int32
	Field2 string
}

func (p *GamesUnloadgameOutPacket) HeaderID() uint16 { return HeaderUnloadgameOut }

func (p *GamesUnloadgameOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteString(p.Field2)
	return nil
}

func DecodeGamesUnloadgameOut(r *codec.Reader) (*GamesUnloadgameOutPacket, error) {
	p := &GamesUnloadgameOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderGameCenterJoiningFailedOut uint16 = 1730

// GamesGameCenterJoiningFailedOutPacket — Game center joining failed
type GamesGameCenterJoiningFailedOutPacket struct {
}

func (p *GamesGameCenterJoiningFailedOutPacket) HeaderID() uint16 { return HeaderGameCenterJoiningFailedOut }

func (p *GamesGameCenterJoiningFailedOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGameCenterJoiningFailedOut(r *codec.Reader) (*GamesGameCenterJoiningFailedOutPacket, error) {
	p := &GamesGameCenterJoiningFailedOutPacket{}
	return p, nil
}

const HeaderGameCenterStartingGameFailedOut uint16 = 2142

// GamesGameCenterStartingGameFailedOutPacket — Game center starting game failed
type GamesGameCenterStartingGameFailedOutPacket struct {
}

func (p *GamesGameCenterStartingGameFailedOutPacket) HeaderID() uint16 { return HeaderGameCenterStartingGameFailedOut }

func (p *GamesGameCenterStartingGameFailedOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGameCenterStartingGameFailedOut(r *codec.Reader) (*GamesGameCenterStartingGameFailedOutPacket, error) {
	p := &GamesGameCenterStartingGameFailedOutPacket{}
	return p, nil
}

const HeaderWeeklyGame2LeaderboardOut uint16 = 2196

// GamesWeeklyGame2LeaderboardOutPacket — Weekly game2 leaderboard
type GamesWeeklyGame2LeaderboardOutPacket struct {
}

func (p *GamesWeeklyGame2LeaderboardOutPacket) HeaderID() uint16 { return HeaderWeeklyGame2LeaderboardOut }

func (p *GamesWeeklyGame2LeaderboardOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesWeeklyGame2LeaderboardOut(r *codec.Reader) (*GamesWeeklyGame2LeaderboardOutPacket, error) {
	p := &GamesWeeklyGame2LeaderboardOutPacket{}
	return p, nil
}

const HeaderGameCenterDirectoryStatusOut uint16 = 2246

// GamesGameCenterDirectoryStatusOutPacket — Game center directory status
type GamesGameCenterDirectoryStatusOutPacket struct {
}

func (p *GamesGameCenterDirectoryStatusOutPacket) HeaderID() uint16 { return HeaderGameCenterDirectoryStatusOut }

func (p *GamesGameCenterDirectoryStatusOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGameCenterDirectoryStatusOut(r *codec.Reader) (*GamesGameCenterDirectoryStatusOutPacket, error) {
	p := &GamesGameCenterDirectoryStatusOutPacket{}
	return p, nil
}

const HeaderJoinedqueuemessageOut uint16 = 2260

// GamesJoinedqueuemessageOutPacket — Joinedqueuemessage
type GamesJoinedqueuemessageOutPacket struct {
	Field1 int32
}

func (p *GamesJoinedqueuemessageOutPacket) HeaderID() uint16 { return HeaderJoinedqueuemessageOut }

func (p *GamesJoinedqueuemessageOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	return nil
}

func DecodeGamesJoinedqueuemessageOut(r *codec.Reader) (*GamesJoinedqueuemessageOutPacket, error) {
	p := &GamesJoinedqueuemessageOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderWeeklyGame2FriendsLeaderboardOut uint16 = 2270

// GamesWeeklyGame2FriendsLeaderboardOutPacket — Weekly game2 friends leaderboard
type GamesWeeklyGame2FriendsLeaderboardOutPacket struct {
}

func (p *GamesWeeklyGame2FriendsLeaderboardOutPacket) HeaderID() uint16 { return HeaderWeeklyGame2FriendsLeaderboardOut }

func (p *GamesWeeklyGame2FriendsLeaderboardOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesWeeklyGame2FriendsLeaderboardOut(r *codec.Reader) (*GamesWeeklyGame2FriendsLeaderboardOutPacket, error) {
	p := &GamesWeeklyGame2FriendsLeaderboardOutPacket{}
	return p, nil
}

const HeaderLoadGameUrlOut uint16 = 2624

// GamesLoadGameUrlOutPacket — Load game url
type GamesLoadGameUrlOutPacket struct {
	Field1 int32
	Field2 string
	Field3 string
}

func (p *GamesLoadGameUrlOutPacket) HeaderID() uint16 { return HeaderLoadGameUrlOut }

func (p *GamesLoadGameUrlOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteString(p.Field2)
	w.WriteString(p.Field3)
	return nil
}

func DecodeGamesLoadGameUrlOut(r *codec.Reader) (*GamesLoadGameUrlOutPacket, error) {
	p := &GamesLoadGameUrlOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadString(); err != nil { return nil, err }
	if p.Field3, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderWeeklyGameRewardOut uint16 = 2641

// GamesWeeklyGameRewardOutPacket — Weekly game reward
type GamesWeeklyGameRewardOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 int32
	Field4 bool
}

func (p *GamesWeeklyGameRewardOutPacket) HeaderID() uint16 { return HeaderWeeklyGameRewardOut }

func (p *GamesWeeklyGameRewardOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteInt32(p.Field3)
	w.WriteBool(p.Field4)
	return nil
}

func DecodeGamesWeeklyGameRewardOut(r *codec.Reader) (*GamesWeeklyGameRewardOutPacket, error) {
	p := &GamesWeeklyGameRewardOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field4, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderGameCenterStatusOut uint16 = 2893

// GamesGameCenterStatusOutPacket — Game center status
type GamesGameCenterStatusOutPacket struct {
}

func (p *GamesGameCenterStatusOutPacket) HeaderID() uint16 { return HeaderGameCenterStatusOut }

func (p *GamesGameCenterStatusOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGameCenterStatusOut(r *codec.Reader) (*GamesGameCenterStatusOutPacket, error) {
	p := &GamesGameCenterStatusOutPacket{}
	return p, nil
}

const HeaderPollContentsOut uint16 = 2997

// GamesPollContentsOutPacket — Poll contents
type GamesPollContentsOutPacket struct {
	Field1 int32
	Field2 string
	Field3 string
	Field4 int32
	Field5 int32
	Field6 bool
	Field7 int32
	Field8 int32
	Field9 int32
	Field10 string
	Field11 int32
	Field12 int32
	Field13 int32
	Field14 string
	Field15 string
	Field16 int32
}

func (p *GamesPollContentsOutPacket) HeaderID() uint16 { return HeaderPollContentsOut }

func (p *GamesPollContentsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteString(p.Field2)
	w.WriteString(p.Field3)
	w.WriteInt32(p.Field4)
	w.WriteInt32(p.Field5)
	w.WriteBool(p.Field6)
	w.WriteInt32(p.Field7)
	w.WriteInt32(p.Field8)
	w.WriteInt32(p.Field9)
	w.WriteString(p.Field10)
	w.WriteInt32(p.Field11)
	w.WriteInt32(p.Field12)
	w.WriteInt32(p.Field13)
	w.WriteString(p.Field14)
	w.WriteString(p.Field15)
	w.WriteInt32(p.Field16)
	return nil
}

func DecodeGamesPollContentsOut(r *codec.Reader) (*GamesPollContentsOutPacket, error) {
	p := &GamesPollContentsOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadString(); err != nil { return nil, err }
	if p.Field3, err = r.ReadString(); err != nil { return nil, err }
	if p.Field4, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field5, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field6, err = r.ReadBool(); err != nil { return nil, err }
	if p.Field7, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field8, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field9, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field10, err = r.ReadString(); err != nil { return nil, err }
	if p.Field11, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field12, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field13, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field14, err = r.ReadString(); err != nil { return nil, err }
	if p.Field15, err = r.ReadString(); err != nil { return nil, err }
	if p.Field16, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderJoiningqueuefailedOut uint16 = 3035

// GamesJoiningqueuefailedOutPacket — Joiningqueuefailed
type GamesJoiningqueuefailedOutPacket struct {
	Field1 int32
	Field2 int32
}

func (p *GamesJoiningqueuefailedOutPacket) HeaderID() uint16 { return HeaderJoiningqueuefailedOut }

func (p *GamesJoiningqueuefailedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeGamesJoiningqueuefailedOut(r *codec.Reader) (*GamesJoiningqueuefailedOutPacket, error) {
	p := &GamesJoiningqueuefailedOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderWeeklyGameRewardWinnersOut uint16 = 3097

// GamesWeeklyGameRewardWinnersOutPacket — Weekly game reward winners
type GamesWeeklyGameRewardWinnersOutPacket struct {
	Field1 int32
	Field2 int32
}

func (p *GamesWeeklyGameRewardWinnersOutPacket) HeaderID() uint16 { return HeaderWeeklyGameRewardWinnersOut }

func (p *GamesWeeklyGameRewardWinnersOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeGamesWeeklyGameRewardWinnersOut(r *codec.Reader) (*GamesWeeklyGameRewardWinnersOutPacket, error) {
	p := &GamesWeeklyGameRewardWinnersOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGameCenterUserLeftGameOut uint16 = 3138

// GamesGameCenterUserLeftGameOutPacket — Game center user left game
type GamesGameCenterUserLeftGameOutPacket struct {
}

func (p *GamesGameCenterUserLeftGameOutPacket) HeaderID() uint16 { return HeaderGameCenterUserLeftGameOut }

func (p *GamesGameCenterUserLeftGameOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGameCenterUserLeftGameOut(r *codec.Reader) (*GamesGameCenterUserLeftGameOutPacket, error) {
	p := &GamesGameCenterUserLeftGameOutPacket{}
	return p, nil
}

const HeaderGameCenterStopCounterOut uint16 = 3191

// GamesGameCenterStopCounterOutPacket — Game center stop counter
type GamesGameCenterStopCounterOutPacket struct {
}

func (p *GamesGameCenterStopCounterOutPacket) HeaderID() uint16 { return HeaderGameCenterStopCounterOut }

func (p *GamesGameCenterStopCounterOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesGameCenterStopCounterOut(r *codec.Reader) (*GamesGameCenterStopCounterOutPacket, error) {
	p := &GamesGameCenterStopCounterOutPacket{}
	return p, nil
}

const HeaderWeeklyCompetitiveLeaderboardOut uint16 = 3512

// GamesWeeklyCompetitiveLeaderboardOutPacket — Weekly competitive leaderboard
type GamesWeeklyCompetitiveLeaderboardOutPacket struct {
}

func (p *GamesWeeklyCompetitiveLeaderboardOutPacket) HeaderID() uint16 { return HeaderWeeklyCompetitiveLeaderboardOut }

func (p *GamesWeeklyCompetitiveLeaderboardOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesWeeklyCompetitiveLeaderboardOut(r *codec.Reader) (*GamesWeeklyCompetitiveLeaderboardOutPacket, error) {
	p := &GamesWeeklyCompetitiveLeaderboardOutPacket{}
	return p, nil
}

const HeaderWeeklyCompetitiveFriendsLeaderboardOut uint16 = 3560

// GamesWeeklyCompetitiveFriendsLeaderboardOutPacket — Weekly competitive friends leaderboard
type GamesWeeklyCompetitiveFriendsLeaderboardOutPacket struct {
}

func (p *GamesWeeklyCompetitiveFriendsLeaderboardOutPacket) HeaderID() uint16 { return HeaderWeeklyCompetitiveFriendsLeaderboardOut }

func (p *GamesWeeklyCompetitiveFriendsLeaderboardOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesWeeklyCompetitiveFriendsLeaderboardOut(r *codec.Reader) (*GamesWeeklyCompetitiveFriendsLeaderboardOutPacket, error) {
	p := &GamesWeeklyCompetitiveFriendsLeaderboardOutPacket{}
	return p, nil
}

const HeaderLoadgameOut uint16 = 3654

// GamesLoadgameOutPacket — Loadgame
type GamesLoadgameOutPacket struct {
	Field1 int32
	Field2 string
	Field3 string
	Field4 string
	Field5 string
	Field6 int32
	Field7 int32
	Field8 int32
	Field9 int32
	Field10 string
	Field11 string
}

func (p *GamesLoadgameOutPacket) HeaderID() uint16 { return HeaderLoadgameOut }

func (p *GamesLoadgameOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteString(p.Field2)
	w.WriteString(p.Field3)
	w.WriteString(p.Field4)
	w.WriteString(p.Field5)
	w.WriteInt32(p.Field6)
	w.WriteInt32(p.Field7)
	w.WriteInt32(p.Field8)
	w.WriteInt32(p.Field9)
	w.WriteString(p.Field10)
	w.WriteString(p.Field11)
	return nil
}

func DecodeGamesLoadgameOut(r *codec.Reader) (*GamesLoadgameOutPacket, error) {
	p := &GamesLoadgameOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadString(); err != nil { return nil, err }
	if p.Field3, err = r.ReadString(); err != nil { return nil, err }
	if p.Field4, err = r.ReadString(); err != nil { return nil, err }
	if p.Field5, err = r.ReadString(); err != nil { return nil, err }
	if p.Field6, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field7, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field8, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field9, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field10, err = r.ReadString(); err != nil { return nil, err }
	if p.Field11, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderPollOfferOut uint16 = 3785

// GamesPollOfferOutPacket — Poll offer
type GamesPollOfferOutPacket struct {
	Field1 int32
	Field2 string
	Field3 string
	Field4 string
}

func (p *GamesPollOfferOutPacket) HeaderID() uint16 { return HeaderPollOfferOut }

func (p *GamesPollOfferOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteString(p.Field2)
	w.WriteString(p.Field3)
	w.WriteString(p.Field4)
	return nil
}

func DecodeGamesPollOfferOut(r *codec.Reader) (*GamesPollOfferOutPacket, error) {
	p := &GamesPollOfferOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadString(); err != nil { return nil, err }
	if p.Field3, err = r.ReadString(); err != nil { return nil, err }
	if p.Field4, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderGamestatusmessageOut uint16 = 3805

// GamesGamestatusmessageOutPacket — Gamestatusmessage
type GamesGamestatusmessageOutPacket struct {
	Field1 int32
	Field2 int32
}

func (p *GamesGamestatusmessageOutPacket) HeaderID() uint16 { return HeaderGamestatusmessageOut }

func (p *GamesGamestatusmessageOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeGamesGamestatusmessageOut(r *codec.Reader) (*GamesGamestatusmessageOutPacket, error) {
	p := &GamesGamestatusmessageOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPollStartRoomOut uint16 = 5200

// GamesPollStartRoomOutPacket — Poll start room
type GamesPollStartRoomOutPacket struct {
}

func (p *GamesPollStartRoomOutPacket) HeaderID() uint16 { return HeaderPollStartRoomOut }

func (p *GamesPollStartRoomOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesPollStartRoomOut(r *codec.Reader) (*GamesPollStartRoomOutPacket, error) {
	p := &GamesPollStartRoomOutPacket{}
	return p, nil
}

const HeaderPollRoomResultOut uint16 = 5201

// GamesPollRoomResultOutPacket — Poll room result
type GamesPollRoomResultOutPacket struct {
}

func (p *GamesPollRoomResultOutPacket) HeaderID() uint16 { return HeaderPollRoomResultOut }

func (p *GamesPollRoomResultOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeGamesPollRoomResultOut(r *codec.Reader) (*GamesPollRoomResultOutPacket, error) {
	p := &GamesPollRoomResultOutPacket{}
	return p, nil
}

