// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderReleaseVersionIn uint16 = 4000

// HandshakeReleaseVersionInPacket — Advertise Nitro release and client platform metadata
type HandshakeReleaseVersionInPacket struct {
	ReleaseVersion string
	ClientType string
	Platform int32
	DeviceCategory int32
}

func (p *HandshakeReleaseVersionInPacket) HeaderID() uint16 { return HeaderReleaseVersionIn }

func (p *HandshakeReleaseVersionInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.ReleaseVersion)
	w.WriteString(p.ClientType)
	w.WriteInt32(p.Platform)
	w.WriteInt32(p.DeviceCategory)
	return nil
}

func DecodeHandshakeReleaseVersionIn(r *codec.Reader) (*HandshakeReleaseVersionInPacket, error) {
	p := &HandshakeReleaseVersionInPacket{}
	var err error
	if p.ReleaseVersion, err = r.ReadString(); err != nil { return nil, err }
	if p.ClientType, err = r.ReadString(); err != nil { return nil, err }
	if p.Platform, err = r.ReadInt32(); err != nil { return nil, err }
	if p.DeviceCategory, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderClientVariablesIn uint16 = 1053

// HandshakeClientVariablesInPacket — Send client resource metadata required by some server revisions
type HandshakeClientVariablesInPacket struct {
	ClientId int32
	ClientUrl string
	ExternalVariablesUrl string
}

func (p *HandshakeClientVariablesInPacket) HeaderID() uint16 { return HeaderClientVariablesIn }

func (p *HandshakeClientVariablesInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ClientId)
	w.WriteString(p.ClientUrl)
	w.WriteString(p.ExternalVariablesUrl)
	return nil
}

func DecodeHandshakeClientVariablesIn(r *codec.Reader) (*HandshakeClientVariablesInPacket, error) {
	p := &HandshakeClientVariablesInPacket{}
	var err error
	if p.ClientId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ClientUrl, err = r.ReadString(); err != nil { return nil, err }
	if p.ExternalVariablesUrl, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderHandshakeInitDiffieIn uint16 = 3110

// HandshakeInitDiffieInPacket — Request signed Diffie-Hellman parameters from server
type HandshakeInitDiffieInPacket struct {
}

func (p *HandshakeInitDiffieInPacket) HeaderID() uint16 { return HeaderHandshakeInitDiffieIn }

func (p *HandshakeInitDiffieInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeHandshakeInitDiffieIn(r *codec.Reader) (*HandshakeInitDiffieInPacket, error) {
	p := &HandshakeInitDiffieInPacket{}
	return p, nil
}

const HeaderHandshakeCompleteDiffieIn uint16 = 773

// HandshakeCompleteDiffieInPacket — Send client public key and complete key exchange
type HandshakeCompleteDiffieInPacket struct {
	EncryptedPublicKey string
}

func (p *HandshakeCompleteDiffieInPacket) HeaderID() uint16 { return HeaderHandshakeCompleteDiffieIn }

func (p *HandshakeCompleteDiffieInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.EncryptedPublicKey)
	return nil
}

func DecodeHandshakeCompleteDiffieIn(r *codec.Reader) (*HandshakeCompleteDiffieInPacket, error) {
	p := &HandshakeCompleteDiffieInPacket{}
	var err error
	if p.EncryptedPublicKey, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderSecurityMachineIn uint16 = 2490

// SecurityMachineIdInPacket — Send machine and fingerprint identifiers
type SecurityMachineIdInPacket struct {
	MachineId string
	Fingerprint string
	Capabilities string
}

func (p *SecurityMachineIdInPacket) HeaderID() uint16 { return HeaderSecurityMachineIn }

func (p *SecurityMachineIdInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.MachineId)
	w.WriteString(p.Fingerprint)
	w.WriteString(p.Capabilities)
	return nil
}

func DecodeSecurityMachineIdIn(r *codec.Reader) (*SecurityMachineIdInPacket, error) {
	p := &SecurityMachineIdInPacket{}
	var err error
	if p.MachineId, err = r.ReadString(); err != nil { return nil, err }
	if p.Fingerprint, err = r.ReadString(); err != nil { return nil, err }
	if p.Capabilities, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderSecurityTicketIn uint16 = 2419

// SecuritySsoTicketInPacket — Authenticate using the SSO ticket
type SecuritySsoTicketInPacket struct {
	Ticket string
	Timestamp int32
}

func (p *SecuritySsoTicketInPacket) HeaderID() uint16 { return HeaderSecurityTicketIn }

func (p *SecuritySsoTicketInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Ticket)
	w.WriteInt32(p.Timestamp)
	return nil
}

func DecodeSecuritySsoTicketIn(r *codec.Reader) (*SecuritySsoTicketInPacket, error) {
	p := &SecuritySsoTicketInPacket{}
	var err error
	if p.Ticket, err = r.ReadString(); err != nil { return nil, err }
	if p.Timestamp, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderClientLatencyMeasureIn uint16 = 96

// HandshakeClientLatencyMeasureInPacket — Client latency measure
type HandshakeClientLatencyMeasureInPacket struct {
}

func (p *HandshakeClientLatencyMeasureInPacket) HeaderID() uint16 { return HeaderClientLatencyMeasureIn }

func (p *HandshakeClientLatencyMeasureInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeHandshakeClientLatencyMeasureIn(r *codec.Reader) (*HandshakeClientLatencyMeasureInPacket, error) {
	p := &HandshakeClientLatencyMeasureInPacket{}
	return p, nil
}

const HeaderClientPolicyIn uint16 = 26979

// HandshakeClientPolicyInPacket — Client policy
type HandshakeClientPolicyInPacket struct {
}

func (p *HandshakeClientPolicyInPacket) HeaderID() uint16 { return HeaderClientPolicyIn }

func (p *HandshakeClientPolicyInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeHandshakeClientPolicyIn(r *codec.Reader) (*HandshakeClientPolicyInPacket, error) {
	p := &HandshakeClientPolicyInPacket{}
	return p, nil
}

const HeaderHandshakeInitDiffieOut uint16 = 1347

// HandshakeInitDiffieOutPacket — Provide signed prime and generator for Diffie-Hellman
type HandshakeInitDiffieOutPacket struct {
	EncryptedPrime string
	EncryptedGenerator string
}

func (p *HandshakeInitDiffieOutPacket) HeaderID() uint16 { return HeaderHandshakeInitDiffieOut }

func (p *HandshakeInitDiffieOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.EncryptedPrime)
	w.WriteString(p.EncryptedGenerator)
	return nil
}

func DecodeHandshakeInitDiffieOut(r *codec.Reader) (*HandshakeInitDiffieOutPacket, error) {
	p := &HandshakeInitDiffieOutPacket{}
	var err error
	if p.EncryptedPrime, err = r.ReadString(); err != nil { return nil, err }
	if p.EncryptedGenerator, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderHandshakeCompleteDiffieOut uint16 = 3885

// HandshakeCompleteDiffieOutPacket — Return server public key and optional encryption flag
type HandshakeCompleteDiffieOutPacket struct {
	EncryptedPublicKey string
	ServerClientEncryption bool
}

func (p *HandshakeCompleteDiffieOutPacket) HeaderID() uint16 { return HeaderHandshakeCompleteDiffieOut }

func (p *HandshakeCompleteDiffieOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.EncryptedPublicKey)
	w.WriteBool(p.ServerClientEncryption)
	return nil
}

func DecodeHandshakeCompleteDiffieOut(r *codec.Reader) (*HandshakeCompleteDiffieOutPacket, error) {
	p := &HandshakeCompleteDiffieOutPacket{}
	var err error
	if p.EncryptedPublicKey, err = r.ReadString(); err != nil { return nil, err }
	if p.ServerClientEncryption, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderSecurityMachineOut uint16 = 1488

// SecurityMachineIdOutPacket — Send normalized machine id back to client for storage
type SecurityMachineIdOutPacket struct {
	MachineId string
}

func (p *SecurityMachineIdOutPacket) HeaderID() uint16 { return HeaderSecurityMachineOut }

func (p *SecurityMachineIdOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.MachineId)
	return nil
}

func DecodeSecurityMachineIdOut(r *codec.Reader) (*SecurityMachineIdOutPacket, error) {
	p := &SecurityMachineIdOutPacket{}
	var err error
	if p.MachineId, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderAuthenticatedOut uint16 = 2491

// AuthenticationOkOutPacket — Confirm successful SSO authentication
type AuthenticationOkOutPacket struct {
}

func (p *AuthenticationOkOutPacket) HeaderID() uint16 { return HeaderAuthenticatedOut }

func (p *AuthenticationOkOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeAuthenticationOkOut(r *codec.Reader) (*AuthenticationOkOutPacket, error) {
	p := &AuthenticationOkOutPacket{}
	return p, nil
}

const HeaderHandshakeIdentityAccountOut uint16 = 3523

// HandshakeIdentityAccountsOutPacket — Provide linked account identities associated with the session
type HandshakeIdentityAccountsOutPacket struct {
	Count int32
}

func (p *HandshakeIdentityAccountsOutPacket) HeaderID() uint16 { return HeaderHandshakeIdentityAccountOut }

func (p *HandshakeIdentityAccountsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Count)
	return nil
}

func DecodeHandshakeIdentityAccountsOut(r *codec.Reader) (*HandshakeIdentityAccountsOutPacket, error) {
	p := &HandshakeIdentityAccountsOutPacket{}
	var err error
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

