// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderUserBadgesCurrentIn uint16 = 2091

// UserGetCurrentBadgesInPacket — Request the equipped badges of a user
type UserGetCurrentBadgesInPacket struct {
	UserId int32
}

func (p *UserGetCurrentBadgesInPacket) HeaderID() uint16 { return HeaderUserBadgesCurrentIn }

func (p *UserGetCurrentBadgesInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeUserGetCurrentBadgesIn(r *codec.Reader) (*UserGetCurrentBadgesInPacket, error) {
	p := &UserGetCurrentBadgesInPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserEffectActivateIn uint16 = 2959

// UserEffectActivateInPacket — Activate an avatar effect in the inventory
type UserEffectActivateInPacket struct {
	Type int32
}

func (p *UserEffectActivateInPacket) HeaderID() uint16 { return HeaderUserEffectActivateIn }

func (p *UserEffectActivateInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Type)
	return nil
}

func DecodeUserEffectActivateIn(r *codec.Reader) (*UserEffectActivateInPacket, error) {
	p := &UserEffectActivateInPacket{}
	var err error
	if p.Type, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserBadgesIn uint16 = 2769

// UserGetBadgesInPacket — Request the full badge inventory for the authenticated user
type UserGetBadgesInPacket struct {
}

func (p *UserGetBadgesInPacket) HeaderID() uint16 { return HeaderUserBadgesIn }

func (p *UserGetBadgesInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserGetBadgesIn(r *codec.Reader) (*UserGetBadgesInPacket, error) {
	p := &UserGetBadgesInPacket{}
	return p, nil
}

const HeaderUserBadgesCurrentUpdateIn uint16 = 644

// UserUpdateBadgesInPacket — Save the current badge slot assignments
type UserUpdateBadgesInPacket struct {
}

func (p *UserUpdateBadgesInPacket) HeaderID() uint16 { return HeaderUserBadgesCurrentUpdateIn }

func (p *UserUpdateBadgesInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserUpdateBadgesIn(r *codec.Reader) (*UserUpdateBadgesInPacket, error) {
	p := &UserUpdateBadgesInPacket{}
	return p, nil
}

const HeaderUnseenResetCategoryIn uint16 = 3493

// UserUnseenResetCategoryInPacket — Mark all unseen items in a category as seen
type UserUnseenResetCategoryInPacket struct {
	Category int32
}

func (p *UserUnseenResetCategoryInPacket) HeaderID() uint16 { return HeaderUnseenResetCategoryIn }

func (p *UserUnseenResetCategoryInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Category)
	return nil
}

func DecodeUserUnseenResetCategoryIn(r *codec.Reader) (*UserUnseenResetCategoryInPacket, error) {
	p := &UserUnseenResetCategoryInPacket{}
	var err error
	if p.Category, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnseenResetItemsIn uint16 = 2343

// UserUnseenResetItemsInPacket — Mark specific unseen items as seen
type UserUnseenResetItemsInPacket struct {
	Category int32
	Count int32
}

func (p *UserUnseenResetItemsInPacket) HeaderID() uint16 { return HeaderUnseenResetItemsIn }

func (p *UserUnseenResetItemsInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Category)
	w.WriteInt32(p.Count)
	return nil
}

func DecodeUserUnseenResetItemsIn(r *codec.Reader) (*UserUnseenResetItemsInPacket, error) {
	p := &UserUnseenResetItemsInPacket{}
	var err error
	if p.Category, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGroupBadgesIn uint16 = 21

// UserGetGroupBadgesInPacket — Request badge codes for groups the user has joined
type UserGetGroupBadgesInPacket struct {
}

func (p *UserGetGroupBadgesInPacket) HeaderID() uint16 { return HeaderGroupBadgesIn }

func (p *UserGetGroupBadgesInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserGetGroupBadgesIn(r *codec.Reader) (*UserGetGroupBadgesInPacket, error) {
	p := &UserGetGroupBadgesInPacket{}
	return p, nil
}

const HeaderGroupMembershipsIn uint16 = 367

// UserGetGroupMembershipsInPacket — Request the full list of groups the user belongs to
type UserGetGroupMembershipsInPacket struct {
}

func (p *UserGetGroupMembershipsInPacket) HeaderID() uint16 { return HeaderGroupMembershipsIn }

func (p *UserGetGroupMembershipsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserGetGroupMembershipsIn(r *codec.Reader) (*UserGetGroupMembershipsInPacket, error) {
	p := &UserGetGroupMembershipsInPacket{}
	return p, nil
}

const HeaderUserFurnitureIn uint16 = 3150

// UserGetFurnitureInPacket — Request the furniture inventory while inside a room
type UserGetFurnitureInPacket struct {
}

func (p *UserGetFurnitureInPacket) HeaderID() uint16 { return HeaderUserFurnitureIn }

func (p *UserGetFurnitureInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserGetFurnitureIn(r *codec.Reader) (*UserGetFurnitureInPacket, error) {
	p := &UserGetFurnitureInPacket{}
	return p, nil
}

const HeaderRequestfurniinventorywhennotinroomIn uint16 = 3500

// UserGetFurnitureNotInRoomInPacket — Request the furniture inventory while not in a room
type UserGetFurnitureNotInRoomInPacket struct {
}

func (p *UserGetFurnitureNotInRoomInPacket) HeaderID() uint16 { return HeaderRequestfurniinventorywhennotinroomIn }

func (p *UserGetFurnitureNotInRoomInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserGetFurnitureNotInRoomIn(r *codec.Reader) (*UserGetFurnitureNotInRoomInPacket, error) {
	p := &UserGetFurnitureNotInRoomInPacket{}
	return p, nil
}

const HeaderUserBotsIn uint16 = 3848

// UserGetBotsInPacket — Request the bot inventory
type UserGetBotsInPacket struct {
}

func (p *UserGetBotsInPacket) HeaderID() uint16 { return HeaderUserBotsIn }

func (p *UserGetBotsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserGetBotsIn(r *codec.Reader) (*UserGetBotsInPacket, error) {
	p := &UserGetBotsInPacket{}
	return p, nil
}

const HeaderUserPetsIn uint16 = 3095

// UserGetPetsInPacket — Request the pet inventory
type UserGetPetsInPacket struct {
}

func (p *UserGetPetsInPacket) HeaderID() uint16 { return HeaderUserPetsIn }

func (p *UserGetPetsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserGetPetsIn(r *codec.Reader) (*UserGetPetsInPacket, error) {
	p := &UserGetPetsInPacket{}
	return p, nil
}

const HeaderItemClothingRedeemIn uint16 = 3374

// UserClothingRedeemInPacket — Redeem a clothing item from furniture
type UserClothingRedeemInPacket struct {
	ItemId int32
}

func (p *UserClothingRedeemInPacket) HeaderID() uint16 { return HeaderItemClothingRedeemIn }

func (p *UserClothingRedeemInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeUserClothingRedeemIn(r *codec.Reader) (*UserClothingRedeemInPacket, error) {
	p := &UserClothingRedeemInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserBadgesCurrentOut uint16 = 1087

// UserCurrentBadgesOutPacket — Deliver the equipped badge slots for a user
type UserCurrentBadgesOutPacket struct {
	UserId int32
	Count int32
}

func (p *UserCurrentBadgesOutPacket) HeaderID() uint16 { return HeaderUserBadgesCurrentOut }

func (p *UserCurrentBadgesOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	w.WriteInt32(p.Count)
	return nil
}

func DecodeUserCurrentBadgesOut(r *codec.Reader) (*UserCurrentBadgesOutPacket, error) {
	p := &UserCurrentBadgesOutPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserEffectListAddOut uint16 = 2867

// UserEffectAddedOutPacket — Notify that a new avatar effect has been added to inventory
type UserEffectAddedOutPacket struct {
	Type int32
	SubType int32
	Duration int32
	IsPermanent bool
}

func (p *UserEffectAddedOutPacket) HeaderID() uint16 { return HeaderUserEffectListAddOut }

func (p *UserEffectAddedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Type)
	w.WriteInt32(p.SubType)
	w.WriteInt32(p.Duration)
	w.WriteBool(p.IsPermanent)
	return nil
}

func DecodeUserEffectAddedOut(r *codec.Reader) (*UserEffectAddedOutPacket, error) {
	p := &UserEffectAddedOutPacket{}
	var err error
	if p.Type, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SubType, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Duration, err = r.ReadInt32(); err != nil { return nil, err }
	if p.IsPermanent, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserEffectListRemoveOut uint16 = 2228

// UserEffectRemovedOutPacket — Notify that an avatar effect has expired and been removed
type UserEffectRemovedOutPacket struct {
	Type int32
}

func (p *UserEffectRemovedOutPacket) HeaderID() uint16 { return HeaderUserEffectListRemoveOut }

func (p *UserEffectRemovedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Type)
	return nil
}

func DecodeUserEffectRemovedOut(r *codec.Reader) (*UserEffectRemovedOutPacket, error) {
	p := &UserEffectRemovedOutPacket{}
	var err error
	if p.Type, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserEffectActivateOut uint16 = 1959

// UserEffectActivatedOutPacket — Confirm that an avatar effect has been activated in the room
type UserEffectActivatedOutPacket struct {
	Type int32
	Duration int32
	IsPermanent bool
}

func (p *UserEffectActivatedOutPacket) HeaderID() uint16 { return HeaderUserEffectActivateOut }

func (p *UserEffectActivatedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Type)
	w.WriteInt32(p.Duration)
	w.WriteBool(p.IsPermanent)
	return nil
}

func DecodeUserEffectActivatedOut(r *codec.Reader) (*UserEffectActivatedOutPacket, error) {
	p := &UserEffectActivatedOutPacket{}
	var err error
	if p.Type, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Duration, err = r.ReadInt32(); err != nil { return nil, err }
	if p.IsPermanent, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderAvatarEffectSelectedOut uint16 = 3473

// UserEffectSelectedOutPacket — Confirm the currently selected avatar effect
type UserEffectSelectedOutPacket struct {
	Type int32
}

func (p *UserEffectSelectedOutPacket) HeaderID() uint16 { return HeaderAvatarEffectSelectedOut }

func (p *UserEffectSelectedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Type)
	return nil
}

func DecodeUserEffectSelectedOut(r *codec.Reader) (*UserEffectSelectedOutPacket, error) {
	p := &UserEffectSelectedOutPacket{}
	var err error
	if p.Type, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserBadgesOut uint16 = 717

// UserBadgesOutPacket — Deliver the full badge inventory and current slot assignments
type UserBadgesOutPacket struct {
	BadgeCount int32
}

func (p *UserBadgesOutPacket) HeaderID() uint16 { return HeaderUserBadgesOut }

func (p *UserBadgesOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.BadgeCount)
	return nil
}

func DecodeUserBadgesOut(r *codec.Reader) (*UserBadgesOutPacket, error) {
	p := &UserBadgesOutPacket{}
	var err error
	if p.BadgeCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserBadgesAddOut uint16 = 2493

// UserBadgeReceivedOutPacket — Notify that the user has received a new badge
type UserBadgeReceivedOutPacket struct {
	BadgeId int32
	BadgeCode string
}

func (p *UserBadgeReceivedOutPacket) HeaderID() uint16 { return HeaderUserBadgesAddOut }

func (p *UserBadgeReceivedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.BadgeId)
	w.WriteString(p.BadgeCode)
	return nil
}

func DecodeUserBadgeReceivedOut(r *codec.Reader) (*UserBadgeReceivedOutPacket, error) {
	p := &UserBadgeReceivedOutPacket{}
	var err error
	if p.BadgeId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.BadgeCode, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnseenItemsOut uint16 = 2103

// UserUnseenItemsOutPacket — Deliver the list of new unseen items in the inventory
type UserUnseenItemsOutPacket struct {
	CategoryCount int32
}

func (p *UserUnseenItemsOutPacket) HeaderID() uint16 { return HeaderUnseenItemsOut }

func (p *UserUnseenItemsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.CategoryCount)
	return nil
}

func DecodeUserUnseenItemsOut(r *codec.Reader) (*UserUnseenItemsOutPacket, error) {
	p := &UserUnseenItemsOutPacket{}
	var err error
	if p.CategoryCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserFurnitureOut uint16 = 994

// UserFurnitureOutPacket — Deliver a fragment of the player's furniture inventory
type UserFurnitureOutPacket struct {
	TotalFragments int32
	FragmentNumber int32
	Items []byte // TODO: hand-implement nested decode
}

func (p *UserFurnitureOutPacket) HeaderID() uint16 { return HeaderUserFurnitureOut }

func (p *UserFurnitureOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.TotalFragments)
	w.WriteInt32(p.FragmentNumber)
	w.WriteBytes(p.Items)
	return nil
}

func DecodeUserFurnitureOut(r *codec.Reader) (*UserFurnitureOutPacket, error) {
	p := &UserFurnitureOutPacket{}
	var err error
	if p.TotalFragments, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FragmentNumber, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Items, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserFurnitureAddOut uint16 = 104

// UserFurnitureAddOutPacket — Add or update a single item in the furniture inventory
type UserFurnitureAddOutPacket struct {
	Item []byte // TODO: hand-implement nested decode
}

func (p *UserFurnitureAddOutPacket) HeaderID() uint16 { return HeaderUserFurnitureAddOut }

func (p *UserFurnitureAddOutPacket) Encode(w *codec.Writer) error {
	w.WriteBytes(p.Item)
	return nil
}

func DecodeUserFurnitureAddOut(r *codec.Reader) (*UserFurnitureAddOutPacket, error) {
	p := &UserFurnitureAddOutPacket{}
	var err error
	if p.Item, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserFurnitureRefreshOut uint16 = 3151

// UserFurnitureRefreshOutPacket — Invalidate the cached furniture inventory
type UserFurnitureRefreshOutPacket struct {
}

func (p *UserFurnitureRefreshOutPacket) HeaderID() uint16 { return HeaderUserFurnitureRefreshOut }

func (p *UserFurnitureRefreshOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserFurnitureRefreshOut(r *codec.Reader) (*UserFurnitureRefreshOutPacket, error) {
	p := &UserFurnitureRefreshOutPacket{}
	return p, nil
}

const HeaderUserFurnitureRemoveOut uint16 = 159

// UserFurnitureRemoveOutPacket — Remove a furniture item from inventory
type UserFurnitureRemoveOutPacket struct {
	ItemId int32
}

func (p *UserFurnitureRemoveOutPacket) HeaderID() uint16 { return HeaderUserFurnitureRemoveOut }

func (p *UserFurnitureRemoveOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeUserFurnitureRemoveOut(r *codec.Reader) (*UserFurnitureRemoveOutPacket, error) {
	p := &UserFurnitureRemoveOutPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserBotsOut uint16 = 3086

// UserBotsOutPacket — Deliver the player's bot inventory
type UserBotsOutPacket struct {
	Bots []byte // TODO: hand-implement nested decode
}

func (p *UserBotsOutPacket) HeaderID() uint16 { return HeaderUserBotsOut }

func (p *UserBotsOutPacket) Encode(w *codec.Writer) error {
	w.WriteBytes(p.Bots)
	return nil
}

func DecodeUserBotsOut(r *codec.Reader) (*UserBotsOutPacket, error) {
	p := &UserBotsOutPacket{}
	var err error
	if p.Bots, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderAddBotToInventoryOut uint16 = 1352

// UserBotAddedOutPacket — Add a bot to the inventory
type UserBotAddedOutPacket struct {
	Bot []byte // TODO: hand-implement nested decode
	OpenInventory bool
}

func (p *UserBotAddedOutPacket) HeaderID() uint16 { return HeaderAddBotToInventoryOut }

func (p *UserBotAddedOutPacket) Encode(w *codec.Writer) error {
	w.WriteBytes(p.Bot)
	w.WriteBool(p.OpenInventory)
	return nil
}

func DecodeUserBotAddedOut(r *codec.Reader) (*UserBotAddedOutPacket, error) {
	p := &UserBotAddedOutPacket{}
	var err error
	if p.Bot, err = r.ReadBytes(); err != nil { return nil, err }
	if p.OpenInventory, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserBotRemoveOut uint16 = 233

// UserBotRemovedOutPacket — Remove a bot from the inventory
type UserBotRemovedOutPacket struct {
	BotId int32
}

func (p *UserBotRemovedOutPacket) HeaderID() uint16 { return HeaderUserBotRemoveOut }

func (p *UserBotRemovedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.BotId)
	return nil
}

func DecodeUserBotRemovedOut(r *codec.Reader) (*UserBotRemovedOutPacket, error) {
	p := &UserBotRemovedOutPacket{}
	var err error
	if p.BotId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserEffectsOut uint16 = 340

// UserEffectsOutPacket — Deliver the full avatar effect inventory
type UserEffectsOutPacket struct {
	Effects []byte // TODO: hand-implement nested decode
}

func (p *UserEffectsOutPacket) HeaderID() uint16 { return HeaderUserEffectsOut }

func (p *UserEffectsOutPacket) Encode(w *codec.Writer) error {
	w.WriteBytes(p.Effects)
	return nil
}

func DecodeUserEffectsOut(r *codec.Reader) (*UserEffectsOutPacket, error) {
	p := &UserEffectsOutPacket{}
	var err error
	if p.Effects, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserClothingOut uint16 = 1450

// UserClothingOutPacket — Deliver the player's unlocked clothing sets
type UserClothingOutPacket struct {
	FigureSetIds []int32
	BoundFurnitureNames []string
}

func (p *UserClothingOutPacket) HeaderID() uint16 { return HeaderUserClothingOut }

func (p *UserClothingOutPacket) Encode(w *codec.Writer) error {
	w.WriteListInt32(p.FigureSetIds)
	w.WriteListString(p.BoundFurnitureNames)
	return nil
}

func DecodeUserClothingOut(r *codec.Reader) (*UserClothingOutPacket, error) {
	p := &UserClothingOutPacket{}
	var err error
	if p.FigureSetIds, err = r.ReadListInt32(); err != nil { return nil, err }
	if p.BoundFurnitureNames, err = r.ReadListString(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserPetsOut uint16 = 3522

// UserPetsOutPacket — Deliver the player's pet inventory
type UserPetsOutPacket struct {
	TotalFragments int32
	FragmentNumber int32
	Pets []byte // TODO: hand-implement nested decode
}

func (p *UserPetsOutPacket) HeaderID() uint16 { return HeaderUserPetsOut }

func (p *UserPetsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.TotalFragments)
	w.WriteInt32(p.FragmentNumber)
	w.WriteBytes(p.Pets)
	return nil
}

func DecodeUserPetsOut(r *codec.Reader) (*UserPetsOutPacket, error) {
	p := &UserPetsOutPacket{}
	var err error
	if p.TotalFragments, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FragmentNumber, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Pets, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserPetAddOut uint16 = 2101

// UserPetAddedOutPacket — Add a pet to the inventory
type UserPetAddedOutPacket struct {
	Pet []byte // TODO: hand-implement nested decode
	BoughtAsGift bool
}

func (p *UserPetAddedOutPacket) HeaderID() uint16 { return HeaderUserPetAddOut }

func (p *UserPetAddedOutPacket) Encode(w *codec.Writer) error {
	w.WriteBytes(p.Pet)
	w.WriteBool(p.BoughtAsGift)
	return nil
}

func DecodeUserPetAddedOut(r *codec.Reader) (*UserPetAddedOutPacket, error) {
	p := &UserPetAddedOutPacket{}
	var err error
	if p.Pet, err = r.ReadBytes(); err != nil { return nil, err }
	if p.BoughtAsGift, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserPetRemoveOut uint16 = 3253

// UserPetRemovedOutPacket — Remove a pet from the inventory
type UserPetRemovedOutPacket struct {
	PetId int32
}

func (p *UserPetRemovedOutPacket) HeaderID() uint16 { return HeaderUserPetRemoveOut }

func (p *UserPetRemovedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	return nil
}

func DecodeUserPetRemovedOut(r *codec.Reader) (*UserPetRemovedOutPacket, error) {
	p := &UserPetRemovedOutPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

