// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderMessengerInitIn uint16 = 2781

// MessengerInitInPacket — Initialize the friend list and messenger subsystem
type MessengerInitInPacket struct {
}

func (p *MessengerInitInPacket) HeaderID() uint16 { return HeaderMessengerInitIn }

func (p *MessengerInitInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeMessengerInitIn(r *codec.Reader) (*MessengerInitInPacket, error) {
	p := &MessengerInitInPacket{}
	return p, nil
}

const HeaderMessengerChatIn uint16 = 3567

// MessengerChatInPacket — Send a private message to a friend
type MessengerChatInPacket struct {
	RecipientId int32
	Message string
}

func (p *MessengerChatInPacket) HeaderID() uint16 { return HeaderMessengerChatIn }

func (p *MessengerChatInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RecipientId)
	w.WriteString(p.Message)
	return nil
}

func DecodeMessengerChatIn(r *codec.Reader) (*MessengerChatInPacket, error) {
	p := &MessengerChatInPacket{}
	var err error
	if p.RecipientId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRequestFriendIn uint16 = 3157

// MessengerRequestFriendInPacket — Send a friend request to another user by username
type MessengerRequestFriendInPacket struct {
	Username string
}

func (p *MessengerRequestFriendInPacket) HeaderID() uint16 { return HeaderRequestFriendIn }

func (p *MessengerRequestFriendInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Username)
	return nil
}

func DecodeMessengerRequestFriendIn(r *codec.Reader) (*MessengerRequestFriendInPacket, error) {
	p := &MessengerRequestFriendInPacket{}
	var err error
	if p.Username, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderAcceptFriendIn uint16 = 137

// MessengerAcceptFriendInPacket — Accept one or more pending friend requests
type MessengerAcceptFriendInPacket struct {
	Count int32
}

func (p *MessengerAcceptFriendInPacket) HeaderID() uint16 { return HeaderAcceptFriendIn }

func (p *MessengerAcceptFriendInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Count)
	return nil
}

func DecodeMessengerAcceptFriendIn(r *codec.Reader) (*MessengerAcceptFriendInPacket, error) {
	p := &MessengerAcceptFriendInPacket{}
	var err error
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderDeclineFriendIn uint16 = 2890

// MessengerDeclineFriendInPacket — Decline one or more pending friend requests, or clear all
type MessengerDeclineFriendInPacket struct {
	RemoveAll bool
	Count int32
}

func (p *MessengerDeclineFriendInPacket) HeaderID() uint16 { return HeaderDeclineFriendIn }

func (p *MessengerDeclineFriendInPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.RemoveAll)
	w.WriteInt32(p.Count)
	return nil
}

func DecodeMessengerDeclineFriendIn(r *codec.Reader) (*MessengerDeclineFriendInPacket, error) {
	p := &MessengerDeclineFriendInPacket{}
	var err error
	if p.RemoveAll, err = r.ReadBool(); err != nil { return nil, err }
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRemoveFriendIn uint16 = 1689

// MessengerRemoveFriendInPacket — Remove one or more users from the friend list
type MessengerRemoveFriendInPacket struct {
	Count int32
}

func (p *MessengerRemoveFriendInPacket) HeaderID() uint16 { return HeaderRemoveFriendIn }

func (p *MessengerRemoveFriendInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Count)
	return nil
}

func DecodeMessengerRemoveFriendIn(r *codec.Reader) (*MessengerRemoveFriendInPacket, error) {
	p := &MessengerRemoveFriendInPacket{}
	var err error
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderFollowFriendIn uint16 = 3997

// MessengerFollowFriendInPacket — Follow a friend to their current room
type MessengerFollowFriendInPacket struct {
	FriendId int32
}

func (p *MessengerFollowFriendInPacket) HeaderID() uint16 { return HeaderFollowFriendIn }

func (p *MessengerFollowFriendInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.FriendId)
	return nil
}

func DecodeMessengerFollowFriendIn(r *codec.Reader) (*MessengerFollowFriendInPacket, error) {
	p := &MessengerFollowFriendInPacket{}
	var err error
	if p.FriendId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderHabboSearchIn uint16 = 1210

// MessengerSearchInPacket — Search for users by name fragment
type MessengerSearchInPacket struct {
	Query string
}

func (p *MessengerSearchInPacket) HeaderID() uint16 { return HeaderHabboSearchIn }

func (p *MessengerSearchInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Query)
	return nil
}

func DecodeMessengerSearchIn(r *codec.Reader) (*MessengerSearchInPacket, error) {
	p := &MessengerSearchInPacket{}
	var err error
	if p.Query, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderSendRoomInviteIn uint16 = 1276

// MessengerRoomInviteInPacket — Send a room invitation to one or more friends
type MessengerRoomInviteInPacket struct {
	RecipientCount int32
	Message string
}

func (p *MessengerRoomInviteInPacket) HeaderID() uint16 { return HeaderSendRoomInviteIn }

func (p *MessengerRoomInviteInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RecipientCount)
	w.WriteString(p.Message)
	return nil
}

func DecodeMessengerRoomInviteIn(r *codec.Reader) (*MessengerRoomInviteInPacket, error) {
	p := &MessengerRoomInviteInPacket{}
	var err error
	if p.RecipientCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetFriendRequestsIn uint16 = 2448

// MessengerGetRequestsInPacket — Request the full list of pending friend requests
type MessengerGetRequestsInPacket struct {
}

func (p *MessengerGetRequestsInPacket) HeaderID() uint16 { return HeaderGetFriendRequestsIn }

func (p *MessengerGetRequestsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeMessengerGetRequestsIn(r *codec.Reader) (*MessengerGetRequestsInPacket, error) {
	p := &MessengerGetRequestsInPacket{}
	return p, nil
}

const HeaderFindNewFriendsIn uint16 = 516

// MessengerFindNewFriendsInPacket — Trigger the automated friend-finder process
type MessengerFindNewFriendsInPacket struct {
}

func (p *MessengerFindNewFriendsInPacket) HeaderID() uint16 { return HeaderFindNewFriendsIn }

func (p *MessengerFindNewFriendsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeMessengerFindNewFriendsIn(r *codec.Reader) (*MessengerFindNewFriendsInPacket, error) {
	p := &MessengerFindNewFriendsInPacket{}
	return p, nil
}

const HeaderFriendListUpdateIn uint16 = 1419

// MessengerRefreshInPacket — Request a full refresh of the friend list
type MessengerRefreshInPacket struct {
}

func (p *MessengerRefreshInPacket) HeaderID() uint16 { return HeaderFriendListUpdateIn }

func (p *MessengerRefreshInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeMessengerRefreshIn(r *codec.Reader) (*MessengerRefreshInPacket, error) {
	p := &MessengerRefreshInPacket{}
	return p, nil
}

const HeaderFriendRequestQuestCompleteIn uint16 = 1148

// MessengerFriendRequestQuestCompleteInPacket — Friend request quest complete
type MessengerFriendRequestQuestCompleteInPacket struct {
}

func (p *MessengerFriendRequestQuestCompleteInPacket) HeaderID() uint16 { return HeaderFriendRequestQuestCompleteIn }

func (p *MessengerFriendRequestQuestCompleteInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeMessengerFriendRequestQuestCompleteIn(r *codec.Reader) (*MessengerFriendRequestQuestCompleteInPacket, error) {
	p := &MessengerFriendRequestQuestCompleteInPacket{}
	return p, nil
}

const HeaderMessengerFriendsIn uint16 = 1523

// MessengerMessengerFriendsInPacket — Messenger friends
type MessengerMessengerFriendsInPacket struct {
}

func (p *MessengerMessengerFriendsInPacket) HeaderID() uint16 { return HeaderMessengerFriendsIn }

func (p *MessengerMessengerFriendsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeMessengerMessengerFriendsIn(r *codec.Reader) (*MessengerMessengerFriendsInPacket, error) {
	p := &MessengerMessengerFriendsInPacket{}
	return p, nil
}

const HeaderMessengerInitOut uint16 = 1605

// MessengerInitOutPacket — Deliver messenger configuration and friend categories to the client
type MessengerInitOutPacket struct {
	UserFriendLimit int32
	NormalFriendLimit int32
	ExtendedFriendLimit int32
	CategoryCount int32
}

func (p *MessengerInitOutPacket) HeaderID() uint16 { return HeaderMessengerInitOut }

func (p *MessengerInitOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserFriendLimit)
	w.WriteInt32(p.NormalFriendLimit)
	w.WriteInt32(p.ExtendedFriendLimit)
	w.WriteInt32(p.CategoryCount)
	return nil
}

func DecodeMessengerInitOut(r *codec.Reader) (*MessengerInitOutPacket, error) {
	p := &MessengerInitOutPacket{}
	var err error
	if p.UserFriendLimit, err = r.ReadInt32(); err != nil { return nil, err }
	if p.NormalFriendLimit, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ExtendedFriendLimit, err = r.ReadInt32(); err != nil { return nil, err }
	if p.CategoryCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerFriendsOut uint16 = 3130

// MessengerFriendsOutPacket — Deliver one fragment of the user's friend list
type MessengerFriendsOutPacket struct {
	TotalFragments int32
	FragmentNumber int32
	FriendCount int32
}

func (p *MessengerFriendsOutPacket) HeaderID() uint16 { return HeaderMessengerFriendsOut }

func (p *MessengerFriendsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.TotalFragments)
	w.WriteInt32(p.FragmentNumber)
	w.WriteInt32(p.FriendCount)
	return nil
}

func DecodeMessengerFriendsOut(r *codec.Reader) (*MessengerFriendsOutPacket, error) {
	p := &MessengerFriendsOutPacket{}
	var err error
	if p.TotalFragments, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FragmentNumber, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FriendCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerUpdateOut uint16 = 2800

// MessengerUpdateOutPacket — Push incremental changes to the friend list
type MessengerUpdateOutPacket struct {
	CategoryCount int32
	UpdateCount int32
}

func (p *MessengerUpdateOutPacket) HeaderID() uint16 { return HeaderMessengerUpdateOut }

func (p *MessengerUpdateOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.CategoryCount)
	w.WriteInt32(p.UpdateCount)
	return nil
}

func DecodeMessengerUpdateOut(r *codec.Reader) (*MessengerUpdateOutPacket, error) {
	p := &MessengerUpdateOutPacket{}
	var err error
	if p.CategoryCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UpdateCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerRequestOut uint16 = 2219

// MessengerFriendRequestOutPacket — Notify the client of a new incoming friend request
type MessengerFriendRequestOutPacket struct {
	RequestId int32
	RequesterName string
	FigureString string
}

func (p *MessengerFriendRequestOutPacket) HeaderID() uint16 { return HeaderMessengerRequestOut }

func (p *MessengerFriendRequestOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RequestId)
	w.WriteString(p.RequesterName)
	w.WriteString(p.FigureString)
	return nil
}

func DecodeMessengerFriendRequestOut(r *codec.Reader) (*MessengerFriendRequestOutPacket, error) {
	p := &MessengerFriendRequestOutPacket{}
	var err error
	if p.RequestId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RequesterName, err = r.ReadString(); err != nil { return nil, err }
	if p.FigureString, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerRequestsOut uint16 = 280

// MessengerFriendRequestsOutPacket — Deliver the full list of pending incoming friend requests
type MessengerFriendRequestsOutPacket struct {
	TotalRequests int32
	RequestCount int32
}

func (p *MessengerFriendRequestsOutPacket) HeaderID() uint16 { return HeaderMessengerRequestsOut }

func (p *MessengerFriendRequestsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.TotalRequests)
	w.WriteInt32(p.RequestCount)
	return nil
}

func DecodeMessengerFriendRequestsOut(r *codec.Reader) (*MessengerFriendRequestsOutPacket, error) {
	p := &MessengerFriendRequestsOutPacket{}
	var err error
	if p.TotalRequests, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RequestCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerChatOut uint16 = 1587

// MessengerChatOutPacket — Deliver an incoming private message from a friend
type MessengerChatOutPacket struct {
	SenderId int32
	MessageText string
	SecondsSinceSent int32
	ExtraData string
}

func (p *MessengerChatOutPacket) HeaderID() uint16 { return HeaderMessengerChatOut }

func (p *MessengerChatOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.SenderId)
	w.WriteString(p.MessageText)
	w.WriteInt32(p.SecondsSinceSent)
	w.WriteString(p.ExtraData)
	return nil
}

func DecodeMessengerChatOut(r *codec.Reader) (*MessengerChatOutPacket, error) {
	p := &MessengerChatOutPacket{}
	var err error
	if p.SenderId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.MessageText, err = r.ReadString(); err != nil { return nil, err }
	if p.SecondsSinceSent, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ExtraData, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerAcceptFriendsOut uint16 = 896

// MessengerAcceptResultOutPacket — Report failures encountered while processing friend-request acceptances
type MessengerAcceptResultOutPacket struct {
	FailureCount int32
}

func (p *MessengerAcceptResultOutPacket) HeaderID() uint16 { return HeaderMessengerAcceptFriendsOut }

func (p *MessengerAcceptResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.FailureCount)
	return nil
}

func DecodeMessengerAcceptResultOut(r *codec.Reader) (*MessengerAcceptResultOutPacket, error) {
	p := &MessengerAcceptResultOutPacket{}
	var err error
	if p.FailureCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerSearchOut uint16 = 973

// MessengerSearchResultOutPacket — Deliver user-search results split into friends and others
type MessengerSearchResultOutPacket struct {
	FriendCount int32
	OtherCount int32
}

func (p *MessengerSearchResultOutPacket) HeaderID() uint16 { return HeaderMessengerSearchOut }

func (p *MessengerSearchResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.FriendCount)
	w.WriteInt32(p.OtherCount)
	return nil
}

func DecodeMessengerSearchResultOut(r *codec.Reader) (*MessengerSearchResultOutPacket, error) {
	p := &MessengerSearchResultOutPacket{}
	var err error
	if p.FriendCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.OtherCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerInviteOut uint16 = 3870

// MessengerRoomInviteOutPacket — Deliver a room invitation sent by a friend
type MessengerRoomInviteOutPacket struct {
	SenderId int32
	Message string
}

func (p *MessengerRoomInviteOutPacket) HeaderID() uint16 { return HeaderMessengerInviteOut }

func (p *MessengerRoomInviteOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.SenderId)
	w.WriteString(p.Message)
	return nil
}

func DecodeMessengerRoomInviteOut(r *codec.Reader) (*MessengerRoomInviteOutPacket, error) {
	p := &MessengerRoomInviteOutPacket{}
	var err error
	if p.SenderId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerInviteErrorOut uint16 = 462

// MessengerRoomInviteErrorOutPacket — Report recipients that could not be reached by a room invitation
type MessengerRoomInviteErrorOutPacket struct {
	ErrorCode int32
	FailedCount int32
}

func (p *MessengerRoomInviteErrorOutPacket) HeaderID() uint16 { return HeaderMessengerInviteErrorOut }

func (p *MessengerRoomInviteErrorOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ErrorCode)
	w.WriteInt32(p.FailedCount)
	return nil
}

func DecodeMessengerRoomInviteErrorOut(r *codec.Reader) (*MessengerRoomInviteErrorOutPacket, error) {
	p := &MessengerRoomInviteErrorOutPacket{}
	var err error
	if p.ErrorCode, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FailedCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerMessageErrorOut uint16 = 892

// MessengerMessageErrorOutPacket — Report a failure when sending a private message or friend request
type MessengerMessageErrorOutPacket struct {
	SenderId int32
	ErrorCode int32
}

func (p *MessengerMessageErrorOutPacket) HeaderID() uint16 { return HeaderMessengerMessageErrorOut }

func (p *MessengerMessageErrorOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.SenderId)
	w.WriteInt32(p.ErrorCode)
	return nil
}

func DecodeMessengerMessageErrorOut(r *codec.Reader) (*MessengerMessageErrorOutPacket, error) {
	p := &MessengerMessageErrorOutPacket{}
	var err error
	if p.SenderId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ErrorCode, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerInstanceMessageErrorOut uint16 = 3359

// MessengerInstantMessageErrorOutPacket — Report a delivery failure for a specific private message
type MessengerInstantMessageErrorOutPacket struct {
	ErrorCode int32
	UserId int32
	Message string
}

func (p *MessengerInstantMessageErrorOutPacket) HeaderID() uint16 { return HeaderMessengerInstanceMessageErrorOut }

func (p *MessengerInstantMessageErrorOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ErrorCode)
	w.WriteInt32(p.UserId)
	w.WriteString(p.Message)
	return nil
}

func DecodeMessengerInstantMessageErrorOut(r *codec.Reader) (*MessengerInstantMessageErrorOutPacket, error) {
	p := &MessengerInstantMessageErrorOutPacket{}
	var err error
	if p.ErrorCode, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerFindFriendsOut uint16 = 1210

// MessengerFindFriendsResultOutPacket — Report the outcome of the automated friend-finder process
type MessengerFindFriendsResultOutPacket struct {
	Success bool
}

func (p *MessengerFindFriendsResultOutPacket) HeaderID() uint16 { return HeaderMessengerFindFriendsOut }

func (p *MessengerFindFriendsResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.Success)
	return nil
}

func DecodeMessengerFindFriendsResultOut(r *codec.Reader) (*MessengerFindFriendsResultOutPacket, error) {
	p := &MessengerFindFriendsResultOutPacket{}
	var err error
	if p.Success, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerFollowFailedOut uint16 = 3048

// MessengerFollowFailedOutPacket — Notify the client that following a friend to their room failed
type MessengerFollowFailedOutPacket struct {
	ErrorCode int32
}

func (p *MessengerFollowFailedOutPacket) HeaderID() uint16 { return HeaderMessengerFollowFailedOut }

func (p *MessengerFollowFailedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ErrorCode)
	return nil
}

func DecodeMessengerFollowFailedOut(r *codec.Reader) (*MessengerFollowFailedOutPacket, error) {
	p := &MessengerFollowFailedOutPacket{}
	var err error
	if p.ErrorCode, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerMinimailCountOut uint16 = 2803

// MessengerMinimailCountOutPacket — Deliver the current count of unread minimail messages
type MessengerMinimailCountOutPacket struct {
	Count int32
}

func (p *MessengerMinimailCountOutPacket) HeaderID() uint16 { return HeaderMessengerMinimailCountOut }

func (p *MessengerMinimailCountOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Count)
	return nil
}

func DecodeMessengerMinimailCountOut(r *codec.Reader) (*MessengerMinimailCountOutPacket, error) {
	p := &MessengerMinimailCountOutPacket{}
	var err error
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerMinimailNewOut uint16 = 1911

// MessengerMinimailNewOutPacket — Notify the client that a new minimail message has arrived
type MessengerMinimailNewOutPacket struct {
}

func (p *MessengerMinimailNewOutPacket) HeaderID() uint16 { return HeaderMessengerMinimailNewOut }

func (p *MessengerMinimailNewOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeMessengerMinimailNewOut(r *codec.Reader) (*MessengerMinimailNewOutPacket, error) {
	p := &MessengerMinimailNewOutPacket{}
	return p, nil
}

