// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderForwardToRandomPromotedRoomIn uint16 = 10

// NavigatorForwardToRandomPromotedRoomInPacket — Forward to random promoted room
type NavigatorForwardToRandomPromotedRoomInPacket struct {
}

func (p *NavigatorForwardToRandomPromotedRoomInPacket) HeaderID() uint16 { return HeaderForwardToRandomPromotedRoomIn }

func (p *NavigatorForwardToRandomPromotedRoomInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeNavigatorForwardToRandomPromotedRoomIn(r *codec.Reader) (*NavigatorForwardToRandomPromotedRoomInPacket, error) {
	p := &NavigatorForwardToRandomPromotedRoomInPacket{}
	return p, nil
}

const HeaderInterstitialShownIn uint16 = 1109

// SessionInterstitialShownInPacket — Interstitial shown
type SessionInterstitialShownInPacket struct {
}

func (p *SessionInterstitialShownInPacket) HeaderID() uint16 { return HeaderInterstitialShownIn }

func (p *SessionInterstitialShownInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSessionInterstitialShownIn(r *codec.Reader) (*SessionInterstitialShownInPacket, error) {
	p := &SessionInterstitialShownInPacket{}
	return p, nil
}

const HeaderDesktopNewsIn uint16 = 1827

// SubscriptionPromoArticlesInPacket — Get promo articles
type SubscriptionPromoArticlesInPacket struct {
}

func (p *SubscriptionPromoArticlesInPacket) HeaderID() uint16 { return HeaderDesktopNewsIn }

func (p *SubscriptionPromoArticlesInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSubscriptionPromoArticlesIn(r *codec.Reader) (*SubscriptionPromoArticlesInPacket, error) {
	p := &SubscriptionPromoArticlesInPacket{}
	return p, nil
}

const HeaderMysteryboxwaitingcanceledmessageIn uint16 = 2012

// FurnitureMysteryboxwaitingcanceledmessageInPacket — Mysteryboxwaitingcanceledmessage
type FurnitureMysteryboxwaitingcanceledmessageInPacket struct {
}

func (p *FurnitureMysteryboxwaitingcanceledmessageInPacket) HeaderID() uint16 { return HeaderMysteryboxwaitingcanceledmessageIn }

func (p *FurnitureMysteryboxwaitingcanceledmessageInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureMysteryboxwaitingcanceledmessageIn(r *codec.Reader) (*FurnitureMysteryboxwaitingcanceledmessageInPacket, error) {
	p := &FurnitureMysteryboxwaitingcanceledmessageInPacket{}
	return p, nil
}

const HeaderMysteryboxOpenTrophyIn uint16 = 3074

// FurnitureMysteryboxOpenTrophyInPacket — Mysterybox open trophy
type FurnitureMysteryboxOpenTrophyInPacket struct {
}

func (p *FurnitureMysteryboxOpenTrophyInPacket) HeaderID() uint16 { return HeaderMysteryboxOpenTrophyIn }

func (p *FurnitureMysteryboxOpenTrophyInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureMysteryboxOpenTrophyIn(r *codec.Reader) (*FurnitureMysteryboxOpenTrophyInPacket, error) {
	p := &FurnitureMysteryboxOpenTrophyInPacket{}
	return p, nil
}

const HeaderGetInterstitialIn uint16 = 2519

// OtherGetInterstitialInPacket — Get interstitial
type OtherGetInterstitialInPacket struct {
}

func (p *OtherGetInterstitialInPacket) HeaderID() uint16 { return HeaderGetInterstitialIn }

func (p *OtherGetInterstitialInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeOtherGetInterstitialIn(r *codec.Reader) (*OtherGetInterstitialInPacket, error) {
	p := &OtherGetInterstitialInPacket{}
	return p, nil
}

const HeaderActivityPointNotificationOut uint16 = 2275

// UserActivityPointNotificationOutPacket — Notify the client of an activity-point currency change
type UserActivityPointNotificationOutPacket struct {
	Amount int32
	AmountChanged int32
	Type int32
}

func (p *UserActivityPointNotificationOutPacket) HeaderID() uint16 { return HeaderActivityPointNotificationOut }

func (p *UserActivityPointNotificationOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Amount)
	w.WriteInt32(p.AmountChanged)
	w.WriteInt32(p.Type)
	return nil
}

func DecodeUserActivityPointNotificationOut(r *codec.Reader) (*UserActivityPointNotificationOutPacket, error) {
	p := &UserActivityPointNotificationOutPacket{}
	var err error
	if p.Amount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.AmountChanged, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Type, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerFriendNotificationOut uint16 = 3082

// MessengerFriendNotificationOutPacket — Push a friend-related state notification to the client
type MessengerFriendNotificationOutPacket struct {
	TypeCode int32
	AvatarId int32
	Message string
}

func (p *MessengerFriendNotificationOutPacket) HeaderID() uint16 { return HeaderMessengerFriendNotificationOut }

func (p *MessengerFriendNotificationOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.TypeCode)
	w.WriteInt32(p.AvatarId)
	w.WriteString(p.Message)
	return nil
}

func DecodeMessengerFriendNotificationOut(r *codec.Reader) (*MessengerFriendNotificationOutPacket, error) {
	p := &MessengerFriendNotificationOutPacket{}
	var err error
	if p.TypeCode, err = r.ReadInt32(); err != nil { return nil, err }
	if p.AvatarId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderCustomUserNotificationOut uint16 = 909

// FurnitureCustomNotificationOutPacket — Deliver a custom notification message from furniture
type FurnitureCustomNotificationOutPacket struct {
	Message string
}

func (p *FurnitureCustomNotificationOutPacket) HeaderID() uint16 { return HeaderCustomUserNotificationOut }

func (p *FurnitureCustomNotificationOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Message)
	return nil
}

func DecodeFurnitureCustomNotificationOut(r *codec.Reader) (*FurnitureCustomNotificationOutPacket, error) {
	p := &FurnitureCustomNotificationOutPacket{}
	var err error
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderClubGiftNotificationOut uint16 = 2188

// CatalogClubGiftNotificationOutPacket — Notify the player that Club gifts are available
type CatalogClubGiftNotificationOutPacket struct {
	NumGifts int32
}

func (p *CatalogClubGiftNotificationOutPacket) HeaderID() uint16 { return HeaderClubGiftNotificationOut }

func (p *CatalogClubGiftNotificationOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.NumGifts)
	return nil
}

func DecodeCatalogClubGiftNotificationOut(r *codec.Reader) (*CatalogClubGiftNotificationOutPacket, error) {
	p := &CatalogClubGiftNotificationOutPacket{}
	var err error
	if p.NumGifts, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetLevelNotificationOut uint16 = 859

// PetLevelNotificationOutPacket — Notify the owner that a pet leveled up
type PetLevelNotificationOutPacket struct {
	PetId int32
	PetName string
	Level int32
	FigureData []byte // TODO: hand-implement nested decode
}

func (p *PetLevelNotificationOutPacket) HeaderID() uint16 { return HeaderPetLevelNotificationOut }

func (p *PetLevelNotificationOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	w.WriteString(p.PetName)
	w.WriteInt32(p.Level)
	w.WriteBytes(p.FigureData)
	return nil
}

func DecodePetLevelNotificationOut(r *codec.Reader) (*PetLevelNotificationOutPacket, error) {
	p := &PetLevelNotificationOutPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PetName, err = r.ReadString(); err != nil { return nil, err }
	if p.Level, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FigureData, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderDesktopNewsOut uint16 = 286

// SubscriptionPromoArticlesOutPacket — Promo articles
type SubscriptionPromoArticlesOutPacket struct {
	Field1 int32
}

func (p *SubscriptionPromoArticlesOutPacket) HeaderID() uint16 { return HeaderDesktopNewsOut }

func (p *SubscriptionPromoArticlesOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	return nil
}

func DecodeSubscriptionPromoArticlesOut(r *codec.Reader) (*SubscriptionPromoArticlesOutPacket, error) {
	p := &SubscriptionPromoArticlesOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderCancelmysteryboxwaitmessageOut uint16 = 596

// FurnitureCancelmysteryboxwaitmessageOutPacket — Cancelmysteryboxwaitmessage
type FurnitureCancelmysteryboxwaitmessageOutPacket struct {
}

func (p *FurnitureCancelmysteryboxwaitmessageOutPacket) HeaderID() uint16 { return HeaderCancelmysteryboxwaitmessageOut }

func (p *FurnitureCancelmysteryboxwaitmessageOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureCancelmysteryboxwaitmessageOut(r *codec.Reader) (*FurnitureCancelmysteryboxwaitmessageOutPacket, error) {
	p := &FurnitureCancelmysteryboxwaitmessageOutPacket{}
	return p, nil
}

const HeaderRoomMessageNotificationOut uint16 = 1634

// RoomRoomMessageNotificationOutPacket — Room message notification
type RoomRoomMessageNotificationOutPacket struct {
	Field1 int32
	Field2 string
	Field3 int32
}

func (p *RoomRoomMessageNotificationOutPacket) HeaderID() uint16 { return HeaderRoomMessageNotificationOut }

func (p *RoomRoomMessageNotificationOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteString(p.Field2)
	w.WriteInt32(p.Field3)
	return nil
}

func DecodeRoomRoomMessageNotificationOut(r *codec.Reader) (*RoomRoomMessageNotificationOutPacket, error) {
	p := &RoomRoomMessageNotificationOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadString(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderNotificationElementPointerOut uint16 = 1787

// SessionNotificationElementPointerOutPacket — Notification element pointer
type SessionNotificationElementPointerOutPacket struct {
}

func (p *SessionNotificationElementPointerOutPacket) HeaderID() uint16 { return HeaderNotificationElementPointerOut }

func (p *SessionNotificationElementPointerOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSessionNotificationElementPointerOut(r *codec.Reader) (*SessionNotificationElementPointerOutPacket, error) {
	p := &SessionNotificationElementPointerOutPacket{}
	return p, nil
}

const HeaderInterstitialMessageOut uint16 = 1808

// SessionInterstitialMessageOutPacket — Interstitial message
type SessionInterstitialMessageOutPacket struct {
	Field1 bool
}

func (p *SessionInterstitialMessageOutPacket) HeaderID() uint16 { return HeaderInterstitialMessageOut }

func (p *SessionInterstitialMessageOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.Field1)
	return nil
}

func DecodeSessionInterstitialMessageOut(r *codec.Reader) (*SessionInterstitialMessageOutPacket, error) {
	p := &SessionInterstitialMessageOutPacket{}
	var err error
	if p.Field1, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderNotificationListOut uint16 = 1992

// SessionNotificationListOutPacket — Notification list
type SessionNotificationListOutPacket struct {
}

func (p *SessionNotificationListOutPacket) HeaderID() uint16 { return HeaderNotificationListOut }

func (p *SessionNotificationListOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSessionNotificationListOut(r *codec.Reader) (*SessionNotificationListOutPacket, error) {
	p := &SessionNotificationListOutPacket{}
	return p, nil
}

const HeaderNotificationOfferRewardDeliveredOut uint16 = 2125

// SessionNotificationOfferRewardDeliveredOutPacket — Notification offer reward delivered
type SessionNotificationOfferRewardDeliveredOutPacket struct {
}

func (p *SessionNotificationOfferRewardDeliveredOutPacket) HeaderID() uint16 { return HeaderNotificationOfferRewardDeliveredOut }

func (p *SessionNotificationOfferRewardDeliveredOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSessionNotificationOfferRewardDeliveredOut(r *codec.Reader) (*SessionNotificationOfferRewardDeliveredOutPacket, error) {
	p := &SessionNotificationOfferRewardDeliveredOutPacket{}
	return p, nil
}

const HeaderShowmysteryboxwaitmessageOut uint16 = 3201

// FurnitureShowmysteryboxwaitmessageOutPacket — Showmysteryboxwaitmessage
type FurnitureShowmysteryboxwaitmessageOutPacket struct {
}

func (p *FurnitureShowmysteryboxwaitmessageOutPacket) HeaderID() uint16 { return HeaderShowmysteryboxwaitmessageOut }

func (p *FurnitureShowmysteryboxwaitmessageOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeFurnitureShowmysteryboxwaitmessageOut(r *codec.Reader) (*FurnitureShowmysteryboxwaitmessageOutPacket, error) {
	p := &FurnitureShowmysteryboxwaitmessageOutPacket{}
	return p, nil
}

const HeaderGotmysteryboxprizemessageOut uint16 = 3712

// FurnitureGotmysteryboxprizemessageOutPacket — Gotmysteryboxprizemessage
type FurnitureGotmysteryboxprizemessageOutPacket struct {
	Field1 string
	Field2 int32
}

func (p *FurnitureGotmysteryboxprizemessageOutPacket) HeaderID() uint16 { return HeaderGotmysteryboxprizemessageOut }

func (p *FurnitureGotmysteryboxprizemessageOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeFurnitureGotmysteryboxprizemessageOut(r *codec.Reader) (*FurnitureGotmysteryboxprizemessageOutPacket, error) {
	p := &FurnitureGotmysteryboxprizemessageOutPacket{}
	var err error
	if p.Field1, err = r.ReadString(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderNotificationSimpleAlertOut uint16 = 5100

// SessionNotificationSimpleAlertOutPacket — Notification simple alert
type SessionNotificationSimpleAlertOutPacket struct {
}

func (p *SessionNotificationSimpleAlertOutPacket) HeaderID() uint16 { return HeaderNotificationSimpleAlertOut }

func (p *SessionNotificationSimpleAlertOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSessionNotificationSimpleAlertOut(r *codec.Reader) (*SessionNotificationSimpleAlertOutPacket, error) {
	p := &SessionNotificationSimpleAlertOutPacket{}
	return p, nil
}

const HeaderIssueCloseNotificationOut uint16 = 934

// ModerationIssueCloseNotificationOutPacket — Issue close notification
type ModerationIssueCloseNotificationOutPacket struct {
	Field1 int32
	Field2 string
}

func (p *ModerationIssueCloseNotificationOutPacket) HeaderID() uint16 { return HeaderIssueCloseNotificationOut }

func (p *ModerationIssueCloseNotificationOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteString(p.Field2)
	return nil
}

func DecodeModerationIssueCloseNotificationOut(r *codec.Reader) (*ModerationIssueCloseNotificationOutPacket, error) {
	p := &ModerationIssueCloseNotificationOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

