// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderPetSupplementIn uint16 = 749

// UserPetSupplementInPacket — Give a supplement item to a pet
type UserPetSupplementInPacket struct {
	PetId int32
	Supplement int32
}

func (p *UserPetSupplementInPacket) HeaderID() uint16 { return HeaderPetSupplementIn }

func (p *UserPetSupplementInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	w.WriteInt32(p.Supplement)
	return nil
}

func DecodeUserPetSupplementIn(r *codec.Reader) (*UserPetSupplementInPacket, error) {
	p := &UserPetSupplementInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Supplement, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetPlaceIn uint16 = 2647

// RoomPlacePetInPacket — Place a pet from inventory into the room
type RoomPlacePetInPacket struct {
	PetId int32
	X int32
	Y int32
}

func (p *RoomPlacePetInPacket) HeaderID() uint16 { return HeaderPetPlaceIn }

func (p *RoomPlacePetInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	w.WriteInt32(p.X)
	w.WriteInt32(p.Y)
	return nil
}

func DecodeRoomPlacePetIn(r *codec.Reader) (*RoomPlacePetInPacket, error) {
	p := &RoomPlacePetInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.X, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Y, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetMoveIn uint16 = 3449

// RoomMovePetInPacket — Move a pet to a new tile in the room
type RoomMovePetInPacket struct {
	PetId int32
	X int32
	Y int32
}

func (p *RoomMovePetInPacket) HeaderID() uint16 { return HeaderPetMoveIn }

func (p *RoomMovePetInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	w.WriteInt32(p.X)
	w.WriteInt32(p.Y)
	return nil
}

func DecodeRoomMovePetIn(r *codec.Reader) (*RoomMovePetInPacket, error) {
	p := &RoomMovePetInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.X, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Y, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetPickupIn uint16 = 1581

// RoomPickupPetInPacket — Remove a pet from the room into inventory
type RoomPickupPetInPacket struct {
	PetId int32
}

func (p *RoomPickupPetInPacket) HeaderID() uint16 { return HeaderPetPickupIn }

func (p *RoomPickupPetInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	return nil
}

func DecodeRoomPickupPetIn(r *codec.Reader) (*RoomPickupPetInPacket, error) {
	p := &RoomPickupPetInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetRideIn uint16 = 1036

// RoomMountPetInPacket — Mount or unmount a rideable pet
type RoomMountPetInPacket struct {
	PetId int32
	Mount bool
}

func (p *RoomMountPetInPacket) HeaderID() uint16 { return HeaderPetRideIn }

func (p *RoomMountPetInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	w.WriteBool(p.Mount)
	return nil
}

func DecodeRoomMountPetIn(r *codec.Reader) (*RoomMountPetInPacket, error) {
	p := &RoomMountPetInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Mount, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderRemovePetSaddleIn uint16 = 186

// RoomRemovePetSaddleInPacket — Remove a saddle from a pet
type RoomRemovePetSaddleInPacket struct {
	PetId int32
}

func (p *RoomRemovePetSaddleInPacket) HeaderID() uint16 { return HeaderRemovePetSaddleIn }

func (p *RoomRemovePetSaddleInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	return nil
}

func DecodeRoomRemovePetSaddleIn(r *codec.Reader) (*RoomRemovePetSaddleInPacket, error) {
	p := &RoomRemovePetSaddleInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetInfoIn uint16 = 2934

// RoomRequestPetInfoInPacket — Request detailed information about a pet
type RoomRequestPetInfoInPacket struct {
	PetId int32
}

func (p *RoomRequestPetInfoInPacket) HeaderID() uint16 { return HeaderPetInfoIn }

func (p *RoomRequestPetInfoInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	return nil
}

func DecodeRoomRequestPetInfoIn(r *codec.Reader) (*RoomRequestPetInfoInPacket, error) {
	p := &RoomRequestPetInfoInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderTogglePetBreedingIn uint16 = 3379

// RoomTogglePetBreedingInPacket — Toggle pet breeding mode
type RoomTogglePetBreedingInPacket struct {
	PetId int32
	Enabled bool
}

func (p *RoomTogglePetBreedingInPacket) HeaderID() uint16 { return HeaderTogglePetBreedingIn }

func (p *RoomTogglePetBreedingInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	w.WriteBool(p.Enabled)
	return nil
}

func DecodeRoomTogglePetBreedingIn(r *codec.Reader) (*RoomTogglePetBreedingInPacket, error) {
	p := &RoomTogglePetBreedingInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Enabled, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderTogglePetRidingIn uint16 = 1472

// RoomTogglePetRidingInPacket — Toggle pet riding permission
type RoomTogglePetRidingInPacket struct {
	PetId int32
	Enabled bool
}

func (p *RoomTogglePetRidingInPacket) HeaderID() uint16 { return HeaderTogglePetRidingIn }

func (p *RoomTogglePetRidingInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	w.WriteBool(p.Enabled)
	return nil
}

func DecodeRoomTogglePetRidingIn(r *codec.Reader) (*RoomTogglePetRidingInPacket, error) {
	p := &RoomTogglePetRidingInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Enabled, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderUsePetProductIn uint16 = 1328

// RoomUsePetProductInPacket — Use a product item on a pet
type RoomUsePetProductInPacket struct {
	PetId int32
	ItemId int32
}

func (p *RoomUsePetProductInPacket) HeaderID() uint16 { return HeaderUsePetProductIn }

func (p *RoomUsePetProductInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeRoomUsePetProductIn(r *codec.Reader) (*RoomUsePetProductInPacket, error) {
	p := &RoomUsePetProductInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetPetTrainingPanelIn uint16 = 2161

// RoomGetPetCommandsInPacket — Request the pet training command panel
type RoomGetPetCommandsInPacket struct {
	PetId int32
}

func (p *RoomGetPetCommandsInPacket) HeaderID() uint16 { return HeaderGetPetTrainingPanelIn }

func (p *RoomGetPetCommandsInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	return nil
}

func DecodeRoomGetPetCommandsIn(r *codec.Reader) (*RoomGetPetCommandsInPacket, error) {
	p := &RoomGetPetCommandsInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetOpenPackageIn uint16 = 3698

// RoomOpenPetPackageInPacket — Open a pet package to reveal a pet
type RoomOpenPetPackageInPacket struct {
	ObjectId int32
	PetName string
}

func (p *RoomOpenPetPackageInPacket) HeaderID() uint16 { return HeaderPetOpenPackageIn }

func (p *RoomOpenPetPackageInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ObjectId)
	w.WriteString(p.PetName)
	return nil
}

func DecodeRoomOpenPetPackageIn(r *codec.Reader) (*RoomOpenPetPackageInPacket, error) {
	p := &RoomOpenPetPackageInPacket{}
	var err error
	if p.ObjectId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PetName, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetSelectedIn uint16 = 549

// RoomSelectPetInPacket — Select a pet in the room
type RoomSelectPetInPacket struct {
	PetId int32
}

func (p *RoomSelectPetInPacket) HeaderID() uint16 { return HeaderPetSelectedIn }

func (p *RoomSelectPetInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	return nil
}

func DecodeRoomSelectPetIn(r *codec.Reader) (*RoomSelectPetInPacket, error) {
	p := &RoomSelectPetInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetsBreedIn uint16 = 1638

// RoomBreedPetsInPacket — Initiate breeding between two pets
type RoomBreedPetsInPacket struct {
	PetId1 int32
	PetId2 int32
}

func (p *RoomBreedPetsInPacket) HeaderID() uint16 { return HeaderPetsBreedIn }

func (p *RoomBreedPetsInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId1)
	w.WriteInt32(p.PetId2)
	return nil
}

func DecodeRoomBreedPetsIn(r *codec.Reader) (*RoomBreedPetsInPacket, error) {
	p := &RoomBreedPetsInPacket{}
	var err error
	if p.PetId1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PetId2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderHarvestPetIn uint16 = 1521

// RoomHarvestPetInPacket — Harvest from a pet-grown plant
type RoomHarvestPetInPacket struct {
	PetId int32
}

func (p *RoomHarvestPetInPacket) HeaderID() uint16 { return HeaderHarvestPetIn }

func (p *RoomHarvestPetInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	return nil
}

func DecodeRoomHarvestPetIn(r *codec.Reader) (*RoomHarvestPetInPacket, error) {
	p := &RoomHarvestPetInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitGiveHanditemPetIn uint16 = 2768

// RoomEntitiesGiveHandItemPetInPacket — Give the hand item to a pet
type RoomEntitiesGiveHandItemPetInPacket struct {
	PetId int32
}

func (p *RoomEntitiesGiveHandItemPetInPacket) HeaderID() uint16 { return HeaderUnitGiveHanditemPetIn }

func (p *RoomEntitiesGiveHandItemPetInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	return nil
}

func DecodeRoomEntitiesGiveHandItemPetIn(r *codec.Reader) (*RoomEntitiesGiveHandItemPetInPacket, error) {
	p := &RoomEntitiesGiveHandItemPetInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetRespectIn uint16 = 3202

// RoomEntitiesRespectPetInPacket — Show affection to a pet
type RoomEntitiesRespectPetInPacket struct {
	PetId int32
}

func (p *RoomEntitiesRespectPetInPacket) HeaderID() uint16 { return HeaderPetRespectIn }

func (p *RoomEntitiesRespectPetInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	return nil
}

func DecodeRoomEntitiesRespectPetIn(r *codec.Reader) (*RoomEntitiesRespectPetInPacket, error) {
	p := &RoomEntitiesRespectPetInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderCatalogRequesetPetBreedsIn uint16 = 1756

// CatalogGetPetBreedsInPacket — Request available pet breed palettes for a pet type
type CatalogGetPetBreedsInPacket struct {
	PetTypeId string
}

func (p *CatalogGetPetBreedsInPacket) HeaderID() uint16 { return HeaderCatalogRequesetPetBreedsIn }

func (p *CatalogGetPetBreedsInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.PetTypeId)
	return nil
}

func DecodeCatalogGetPetBreedsIn(r *codec.Reader) (*CatalogGetPetBreedsInPacket, error) {
	p := &CatalogGetPetBreedsInPacket{}
	var err error
	if p.PetTypeId, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetCancelBreedingIn uint16 = 2713

// PetCancelBreedingInPacket — Cancel an in-progress pet breeding session
type PetCancelBreedingInPacket struct {
	PetId int32
}

func (p *PetCancelBreedingInPacket) HeaderID() uint16 { return HeaderPetCancelBreedingIn }

func (p *PetCancelBreedingInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	return nil
}

func DecodePetCancelBreedingIn(r *codec.Reader) (*PetCancelBreedingInPacket, error) {
	p := &PetCancelBreedingInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetConfirmBreedingIn uint16 = 3382

// PetConfirmBreedingInPacket — Confirm a pet breeding request
type PetConfirmBreedingInPacket struct {
	NestItemId int32
}

func (p *PetConfirmBreedingInPacket) HeaderID() uint16 { return HeaderPetConfirmBreedingIn }

func (p *PetConfirmBreedingInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.NestItemId)
	return nil
}

func DecodePetConfirmBreedingIn(r *codec.Reader) (*PetConfirmBreedingInPacket, error) {
	p := &PetConfirmBreedingInPacket{}
	var err error
	if p.NestItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderCompostPlantIn uint16 = 3835

// PetCompostInPacket — Compost a plant pet
type PetCompostInPacket struct {
	PetId int32
}

func (p *PetCompostInPacket) HeaderID() uint16 { return HeaderCompostPlantIn }

func (p *PetCompostInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	return nil
}

func DecodePetCompostIn(r *codec.Reader) (*PetCompostInPacket, error) {
	p := &PetCompostInPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetRespectedOut uint16 = 2788

// UserPetRespectedOutPacket — Notify that a pet has received a respect point
type UserPetRespectedOutPacket struct {
	Respect int32
	PetOwnerId int32
}

func (p *UserPetRespectedOutPacket) HeaderID() uint16 { return HeaderPetRespectedOut }

func (p *UserPetRespectedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Respect)
	w.WriteInt32(p.PetOwnerId)
	return nil
}

func DecodeUserPetRespectedOut(r *codec.Reader) (*UserPetRespectedOutPacket, error) {
	p := &UserPetRespectedOutPacket{}
	var err error
	if p.Respect, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PetOwnerId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetSupplementOut uint16 = 3441

// UserPetSupplementedOutPacket — Notify that a pet has received a supplement
type UserPetSupplementedOutPacket struct {
	PetId int32
	UserId int32
	SupplementType int32
}

func (p *UserPetSupplementedOutPacket) HeaderID() uint16 { return HeaderPetSupplementOut }

func (p *UserPetSupplementedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	w.WriteInt32(p.UserId)
	w.WriteInt32(p.SupplementType)
	return nil
}

func DecodeUserPetSupplementedOut(r *codec.Reader) (*UserPetSupplementedOutPacket, error) {
	p := &UserPetSupplementedOutPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SupplementType, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderCatalogReceivePetBreedsOut uint16 = 3331

// CatalogPetBreedsOutPacket — Deliver available pet breed palette data
type CatalogPetBreedsOutPacket struct {
	PetType string
	PaletteCount int32
	Palettes []byte // TODO: hand-implement nested decode
}

func (p *CatalogPetBreedsOutPacket) HeaderID() uint16 { return HeaderCatalogReceivePetBreedsOut }

func (p *CatalogPetBreedsOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.PetType)
	w.WriteInt32(p.PaletteCount)
	w.WriteBytes(p.Palettes)
	return nil
}

func DecodeCatalogPetBreedsOut(r *codec.Reader) (*CatalogPetBreedsOutPacket, error) {
	p := &CatalogPetBreedsOutPacket{}
	var err error
	if p.PetType, err = r.ReadString(); err != nil { return nil, err }
	if p.PaletteCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Palettes, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetInfoOut uint16 = 2901

// PetInfoOutPacket — Deliver detailed information about a pet
type PetInfoOutPacket struct {
	Id int32
	Name string
	Level int32
	MaximumLevel int32
	Experience int32
	LevelExperienceGoal int32
	Energy int32
	MaximumEnergy int32
	Happiness int32
	MaximumHappiness int32
	Respect int32
	OwnerId int32
	Age int32
	OwnerName string
	RarityLevel int32
	HasSaddle bool
	IsRiding bool
	SkillThresholds []int32
	PubliclyRideable int32
	Breedable bool
	FullyGrown bool
	Dead bool
	UnknownRarity int32
	MaximumTimeToLive int32
	RemainingTimeToLive int32
	RemainingGrowTime int32
	PubliclyBreedable bool
}

func (p *PetInfoOutPacket) HeaderID() uint16 { return HeaderPetInfoOut }

func (p *PetInfoOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Id)
	w.WriteString(p.Name)
	w.WriteInt32(p.Level)
	w.WriteInt32(p.MaximumLevel)
	w.WriteInt32(p.Experience)
	w.WriteInt32(p.LevelExperienceGoal)
	w.WriteInt32(p.Energy)
	w.WriteInt32(p.MaximumEnergy)
	w.WriteInt32(p.Happiness)
	w.WriteInt32(p.MaximumHappiness)
	w.WriteInt32(p.Respect)
	w.WriteInt32(p.OwnerId)
	w.WriteInt32(p.Age)
	w.WriteString(p.OwnerName)
	w.WriteInt32(p.RarityLevel)
	w.WriteBool(p.HasSaddle)
	w.WriteBool(p.IsRiding)
	w.WriteListInt32(p.SkillThresholds)
	w.WriteInt32(p.PubliclyRideable)
	w.WriteBool(p.Breedable)
	w.WriteBool(p.FullyGrown)
	w.WriteBool(p.Dead)
	w.WriteInt32(p.UnknownRarity)
	w.WriteInt32(p.MaximumTimeToLive)
	w.WriteInt32(p.RemainingTimeToLive)
	w.WriteInt32(p.RemainingGrowTime)
	w.WriteBool(p.PubliclyBreedable)
	return nil
}

func DecodePetInfoOut(r *codec.Reader) (*PetInfoOutPacket, error) {
	p := &PetInfoOutPacket{}
	var err error
	if p.Id, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Name, err = r.ReadString(); err != nil { return nil, err }
	if p.Level, err = r.ReadInt32(); err != nil { return nil, err }
	if p.MaximumLevel, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Experience, err = r.ReadInt32(); err != nil { return nil, err }
	if p.LevelExperienceGoal, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Energy, err = r.ReadInt32(); err != nil { return nil, err }
	if p.MaximumEnergy, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Happiness, err = r.ReadInt32(); err != nil { return nil, err }
	if p.MaximumHappiness, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Respect, err = r.ReadInt32(); err != nil { return nil, err }
	if p.OwnerId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Age, err = r.ReadInt32(); err != nil { return nil, err }
	if p.OwnerName, err = r.ReadString(); err != nil { return nil, err }
	if p.RarityLevel, err = r.ReadInt32(); err != nil { return nil, err }
	if p.HasSaddle, err = r.ReadBool(); err != nil { return nil, err }
	if p.IsRiding, err = r.ReadBool(); err != nil { return nil, err }
	if p.SkillThresholds, err = r.ReadListInt32(); err != nil { return nil, err }
	if p.PubliclyRideable, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Breedable, err = r.ReadBool(); err != nil { return nil, err }
	if p.FullyGrown, err = r.ReadBool(); err != nil { return nil, err }
	if p.Dead, err = r.ReadBool(); err != nil { return nil, err }
	if p.UnknownRarity, err = r.ReadInt32(); err != nil { return nil, err }
	if p.MaximumTimeToLive, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RemainingTimeToLive, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RemainingGrowTime, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PubliclyBreedable, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetTrainingPanelOut uint16 = 1164

// PetTrainingPanelOutPacket — Deliver the pet training command panel
type PetTrainingPanelOutPacket struct {
	PetId int32
	Commands []int32
	EnabledCommands []int32
}

func (p *PetTrainingPanelOutPacket) HeaderID() uint16 { return HeaderPetTrainingPanelOut }

func (p *PetTrainingPanelOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	w.WriteListInt32(p.Commands)
	w.WriteListInt32(p.EnabledCommands)
	return nil
}

func DecodePetTrainingPanelOut(r *codec.Reader) (*PetTrainingPanelOutPacket, error) {
	p := &PetTrainingPanelOutPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Commands, err = r.ReadListInt32(); err != nil { return nil, err }
	if p.EnabledCommands, err = r.ReadListInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetLevelUpdateOut uint16 = 2824

// PetLevelUpdateOutPacket — Notify that a pet leveled up in the room
type PetLevelUpdateOutPacket struct {
	RoomIndex int32
	PetId int32
	Level int32
}

func (p *PetLevelUpdateOutPacket) HeaderID() uint16 { return HeaderPetLevelUpdateOut }

func (p *PetLevelUpdateOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteInt32(p.PetId)
	w.WriteInt32(p.Level)
	return nil
}

func DecodePetLevelUpdateOut(r *codec.Reader) (*PetLevelUpdateOutPacket, error) {
	p := &PetLevelUpdateOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Level, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetScratchFailedOut uint16 = 1130

// PetScratchFailedOutPacket — Indicate that a pet scratch (respect) failed due to age
type PetScratchFailedOutPacket struct {
	CurrentAge int32
	RequiredAge int32
}

func (p *PetScratchFailedOutPacket) HeaderID() uint16 { return HeaderPetScratchFailedOut }

func (p *PetScratchFailedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.CurrentAge)
	w.WriteInt32(p.RequiredAge)
	return nil
}

func DecodePetScratchFailedOut(r *codec.Reader) (*PetScratchFailedOutPacket, error) {
	p := &PetScratchFailedOutPacket{}
	var err error
	if p.CurrentAge, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RequiredAge, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetFigureUpdateOut uint16 = 1924

// PetFigureUpdateOutPacket — Update a pet's visual figure in the room
type PetFigureUpdateOutPacket struct {
	RoomIndex int32
	PetId int32
	FigureData []byte // TODO: hand-implement nested decode
	HasSaddle bool
	IsRiding bool
}

func (p *PetFigureUpdateOutPacket) HeaderID() uint16 { return HeaderPetFigureUpdateOut }

func (p *PetFigureUpdateOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteInt32(p.PetId)
	w.WriteBytes(p.FigureData)
	w.WriteBool(p.HasSaddle)
	w.WriteBool(p.IsRiding)
	return nil
}

func DecodePetFigureUpdateOut(r *codec.Reader) (*PetFigureUpdateOutPacket, error) {
	p := &PetFigureUpdateOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FigureData, err = r.ReadBytes(); err != nil { return nil, err }
	if p.HasSaddle, err = r.ReadBool(); err != nil { return nil, err }
	if p.IsRiding, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetExperienceOut uint16 = 2156

// PetExperienceOutPacket — Show experience gained by a pet
type PetExperienceOutPacket struct {
	PetId int32
	RoomIndex int32
	GainedExperience int32
}

func (p *PetExperienceOutPacket) HeaderID() uint16 { return HeaderPetExperienceOut }

func (p *PetExperienceOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	w.WriteInt32(p.RoomIndex)
	w.WriteInt32(p.GainedExperience)
	return nil
}

func DecodePetExperienceOut(r *codec.Reader) (*PetExperienceOutPacket, error) {
	p := &PetExperienceOutPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.GainedExperience, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetStatusOut uint16 = 1907

// PetStatusOutPacket — Update a pet's breeding and harvest status
type PetStatusOutPacket struct {
	RoomIndex int32
	PetId int32
	CanBreed bool
	CanHarvest bool
	CanRevive bool
	HasBreedingPermission bool
}

func (p *PetStatusOutPacket) HeaderID() uint16 { return HeaderPetStatusOut }

func (p *PetStatusOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteInt32(p.PetId)
	w.WriteBool(p.CanBreed)
	w.WriteBool(p.CanHarvest)
	w.WriteBool(p.CanRevive)
	w.WriteBool(p.HasBreedingPermission)
	return nil
}

func DecodePetStatusOut(r *codec.Reader) (*PetStatusOutPacket, error) {
	p := &PetStatusOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.CanBreed, err = r.ReadBool(); err != nil { return nil, err }
	if p.CanHarvest, err = r.ReadBool(); err != nil { return nil, err }
	if p.CanRevive, err = r.ReadBool(); err != nil { return nil, err }
	if p.HasBreedingPermission, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetPlacingErrorOut uint16 = 2913

// PetPlacingErrorOutPacket — Indicate a pet placement error
type PetPlacingErrorOutPacket struct {
	ErrorCode int32
}

func (p *PetPlacingErrorOutPacket) HeaderID() uint16 { return HeaderPetPlacingErrorOut }

func (p *PetPlacingErrorOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ErrorCode)
	return nil
}

func DecodePetPlacingErrorOut(r *codec.Reader) (*PetPlacingErrorOutPacket, error) {
	p := &PetPlacingErrorOutPacket{}
	var err error
	if p.ErrorCode, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetReceivedOut uint16 = 1111

// PetReceivedOutPacket — Notify that the player received a pet
type PetReceivedOutPacket struct {
	BoughtAsGift bool
	Pet []byte // TODO: hand-implement nested decode
}

func (p *PetReceivedOutPacket) HeaderID() uint16 { return HeaderPetReceivedOut }

func (p *PetReceivedOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.BoughtAsGift)
	w.WriteBytes(p.Pet)
	return nil
}

func DecodePetReceivedOut(r *codec.Reader) (*PetReceivedOutPacket, error) {
	p := &PetReceivedOutPacket{}
	var err error
	if p.BoughtAsGift, err = r.ReadBool(); err != nil { return nil, err }
	if p.Pet, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetOpenPackageRequestedOut uint16 = 2380

// PetOpenPackageRequestedOutPacket — Show the pet package opening dialog
type PetOpenPackageRequestedOutPacket struct {
	ObjectId int32
	FigureData string
}

func (p *PetOpenPackageRequestedOutPacket) HeaderID() uint16 { return HeaderPetOpenPackageRequestedOut }

func (p *PetOpenPackageRequestedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ObjectId)
	w.WriteString(p.FigureData)
	return nil
}

func DecodePetOpenPackageRequestedOut(r *codec.Reader) (*PetOpenPackageRequestedOutPacket, error) {
	p := &PetOpenPackageRequestedOutPacket{}
	var err error
	if p.ObjectId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FigureData, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetOpenPackageResultOut uint16 = 546

// PetOpenPackageResultOutPacket — Deliver the result of naming a pet from a package
type PetOpenPackageResultOutPacket struct {
	ObjectId int32
	NameValidationStatus int32
	NameValidationInfo string
}

func (p *PetOpenPackageResultOutPacket) HeaderID() uint16 { return HeaderPetOpenPackageResultOut }

func (p *PetOpenPackageResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ObjectId)
	w.WriteInt32(p.NameValidationStatus)
	w.WriteString(p.NameValidationInfo)
	return nil
}

func DecodePetOpenPackageResultOut(r *codec.Reader) (*PetOpenPackageResultOutPacket, error) {
	p := &PetOpenPackageResultOutPacket{}
	var err error
	if p.ObjectId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.NameValidationStatus, err = r.ReadInt32(); err != nil { return nil, err }
	if p.NameValidationInfo, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetBreedingOut uint16 = 1746

// PetBreedingOutPacket — Notify about a pet breeding state change
type PetBreedingOutPacket struct {
	State int32
	OwnPetId int32
	OtherPetId int32
}

func (p *PetBreedingOutPacket) HeaderID() uint16 { return HeaderPetBreedingOut }

func (p *PetBreedingOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.State)
	w.WriteInt32(p.OwnPetId)
	w.WriteInt32(p.OtherPetId)
	return nil
}

func DecodePetBreedingOut(r *codec.Reader) (*PetBreedingOutPacket, error) {
	p := &PetBreedingOutPacket{}
	var err error
	if p.State, err = r.ReadInt32(); err != nil { return nil, err }
	if p.OwnPetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.OtherPetId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetConfirmBreedingRequestOut uint16 = 634

// PetConfirmBreedingRequestOutPacket — Show the breeding confirmation dialog
type PetConfirmBreedingRequestOutPacket struct {
	NestId int32
	Pet1 []byte // TODO: hand-implement nested decode
	Pet2 []byte // TODO: hand-implement nested decode
	RarityCategories []byte // TODO: hand-implement nested decode
	ResultPetType int32
}

func (p *PetConfirmBreedingRequestOutPacket) HeaderID() uint16 { return HeaderPetConfirmBreedingRequestOut }

func (p *PetConfirmBreedingRequestOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.NestId)
	w.WriteBytes(p.Pet1)
	w.WriteBytes(p.Pet2)
	w.WriteBytes(p.RarityCategories)
	w.WriteInt32(p.ResultPetType)
	return nil
}

func DecodePetConfirmBreedingRequestOut(r *codec.Reader) (*PetConfirmBreedingRequestOutPacket, error) {
	p := &PetConfirmBreedingRequestOutPacket{}
	var err error
	if p.NestId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Pet1, err = r.ReadBytes(); err != nil { return nil, err }
	if p.Pet2, err = r.ReadBytes(); err != nil { return nil, err }
	if p.RarityCategories, err = r.ReadBytes(); err != nil { return nil, err }
	if p.ResultPetType, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetConfirmBreedingResultOut uint16 = 1625

// PetConfirmBreedingResultOutPacket — Deliver the breeding nest confirmation result
type PetConfirmBreedingResultOutPacket struct {
	BreedingNestStuffId int32
	Result int32
}

func (p *PetConfirmBreedingResultOutPacket) HeaderID() uint16 { return HeaderPetConfirmBreedingResultOut }

func (p *PetConfirmBreedingResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.BreedingNestStuffId)
	w.WriteInt32(p.Result)
	return nil
}

func DecodePetConfirmBreedingResultOut(r *codec.Reader) (*PetConfirmBreedingResultOutPacket, error) {
	p := &PetConfirmBreedingResultOutPacket{}
	var err error
	if p.BreedingNestStuffId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Result, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetBreedingResultOut uint16 = 1553

// PetBreedingResultOutPacket — Deliver the result of a completed pet breeding
type PetBreedingResultOutPacket struct {
	ResultData []byte // TODO: hand-implement nested decode
	OtherResultData []byte // TODO: hand-implement nested decode
}

func (p *PetBreedingResultOutPacket) HeaderID() uint16 { return HeaderPetBreedingResultOut }

func (p *PetBreedingResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteBytes(p.ResultData)
	w.WriteBytes(p.OtherResultData)
	return nil
}

func DecodePetBreedingResultOut(r *codec.Reader) (*PetBreedingResultOutPacket, error) {
	p := &PetBreedingResultOutPacket{}
	var err error
	if p.ResultData, err = r.ReadBytes(); err != nil { return nil, err }
	if p.OtherResultData, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetNestBreedingSuccessOut uint16 = 2527

// PetNestBreedingSuccessOutPacket — Confirm that breeding nest assignment succeeded
type PetNestBreedingSuccessOutPacket struct {
	PetId int32
	RarityCategory int32
}

func (p *PetNestBreedingSuccessOutPacket) HeaderID() uint16 { return HeaderPetNestBreedingSuccessOut }

func (p *PetNestBreedingSuccessOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PetId)
	w.WriteInt32(p.RarityCategory)
	return nil
}

func DecodePetNestBreedingSuccessOut(r *codec.Reader) (*PetNestBreedingSuccessOutPacket, error) {
	p := &PetNestBreedingSuccessOutPacket{}
	var err error
	if p.PetId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RarityCategory, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderPetGoToBreedingNestFailureOut uint16 = 2621

// PetGoToBreedingNestFailureOutPacket — Indicate that a pet could not reach the breeding nest
type PetGoToBreedingNestFailureOutPacket struct {
	Reason int32
}

func (p *PetGoToBreedingNestFailureOutPacket) HeaderID() uint16 { return HeaderPetGoToBreedingNestFailureOut }

func (p *PetGoToBreedingNestFailureOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Reason)
	return nil
}

func DecodePetGoToBreedingNestFailureOut(r *codec.Reader) (*PetGoToBreedingNestFailureOutPacket, error) {
	p := &PetGoToBreedingNestFailureOutPacket{}
	var err error
	if p.Reason, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

