// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderUnitWalkIn uint16 = 3320

// RoomEntitiesWalkInPacket — Walk the user's avatar to a tile
type RoomEntitiesWalkInPacket struct {
	X int32
	Y int32
}

func (p *RoomEntitiesWalkInPacket) HeaderID() uint16 { return HeaderUnitWalkIn }

func (p *RoomEntitiesWalkInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.X)
	w.WriteInt32(p.Y)
	return nil
}

func DecodeRoomEntitiesWalkIn(r *codec.Reader) (*RoomEntitiesWalkInPacket, error) {
	p := &RoomEntitiesWalkInPacket{}
	var err error
	if p.X, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Y, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitDanceIn uint16 = 2080

// RoomEntitiesDanceInPacket — Set the avatar's dance animation
type RoomEntitiesDanceInPacket struct {
	DanceId int32
}

func (p *RoomEntitiesDanceInPacket) HeaderID() uint16 { return HeaderUnitDanceIn }

func (p *RoomEntitiesDanceInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.DanceId)
	return nil
}

func DecodeRoomEntitiesDanceIn(r *codec.Reader) (*RoomEntitiesDanceInPacket, error) {
	p := &RoomEntitiesDanceInPacket{}
	var err error
	if p.DanceId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitActionIn uint16 = 2456

// RoomEntitiesActionInPacket — Perform an avatar action or expression
type RoomEntitiesActionInPacket struct {
	ActionId int32
}

func (p *RoomEntitiesActionInPacket) HeaderID() uint16 { return HeaderUnitActionIn }

func (p *RoomEntitiesActionInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ActionId)
	return nil
}

func DecodeRoomEntitiesActionIn(r *codec.Reader) (*RoomEntitiesActionInPacket, error) {
	p := &RoomEntitiesActionInPacket{}
	var err error
	if p.ActionId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitPostureIn uint16 = 2235

// RoomEntitiesSetPostureInPacket — Set the avatar's posture (sit or stand)
type RoomEntitiesSetPostureInPacket struct {
	Posture int32
}

func (p *RoomEntitiesSetPostureInPacket) HeaderID() uint16 { return HeaderUnitPostureIn }

func (p *RoomEntitiesSetPostureInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Posture)
	return nil
}

func DecodeRoomEntitiesSetPostureIn(r *codec.Reader) (*RoomEntitiesSetPostureInPacket, error) {
	p := &RoomEntitiesSetPostureInPacket{}
	var err error
	if p.Posture, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitSignIn uint16 = 1975

// RoomEntitiesHoldSignInPacket — Hold up a sign with a number or symbol
type RoomEntitiesHoldSignInPacket struct {
	SignId int32
}

func (p *RoomEntitiesHoldSignInPacket) HeaderID() uint16 { return HeaderUnitSignIn }

func (p *RoomEntitiesHoldSignInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.SignId)
	return nil
}

func DecodeRoomEntitiesHoldSignIn(r *codec.Reader) (*RoomEntitiesHoldSignInPacket, error) {
	p := &RoomEntitiesHoldSignInPacket{}
	var err error
	if p.SignId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitLookIn uint16 = 3301

// RoomEntitiesLookAtInPacket — Make the avatar look toward a target
type RoomEntitiesLookAtInPacket struct {
	X int32
	Y int32
}

func (p *RoomEntitiesLookAtInPacket) HeaderID() uint16 { return HeaderUnitLookIn }

func (p *RoomEntitiesLookAtInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.X)
	w.WriteInt32(p.Y)
	return nil
}

func DecodeRoomEntitiesLookAtIn(r *codec.Reader) (*RoomEntitiesLookAtInPacket, error) {
	p := &RoomEntitiesLookAtInPacket{}
	var err error
	if p.X, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Y, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitGiveHanditemIn uint16 = 2941

// RoomEntitiesGiveHandItemInPacket — Give the hand item to another user
type RoomEntitiesGiveHandItemInPacket struct {
	UserId int32
}

func (p *RoomEntitiesGiveHandItemInPacket) HeaderID() uint16 { return HeaderUnitGiveHanditemIn }

func (p *RoomEntitiesGiveHandItemInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeRoomEntitiesGiveHandItemIn(r *codec.Reader) (*RoomEntitiesGiveHandItemInPacket, error) {
	p := &RoomEntitiesGiveHandItemInPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitDropHandItemIn uint16 = 2814

// RoomEntitiesDropHandItemInPacket — Drop the currently held hand item
type RoomEntitiesDropHandItemInPacket struct {
}

func (p *RoomEntitiesDropHandItemInPacket) HeaderID() uint16 { return HeaderUnitDropHandItemIn }

func (p *RoomEntitiesDropHandItemInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomEntitiesDropHandItemIn(r *codec.Reader) (*RoomEntitiesDropHandItemInPacket, error) {
	p := &RoomEntitiesDropHandItemInPacket{}
	return p, nil
}

const HeaderUnitChatIn uint16 = 1314

// RoomEntitiesSayInPacket — Send a normal chat message in the room
type RoomEntitiesSayInPacket struct {
	Message string
	StyleId int32
}

func (p *RoomEntitiesSayInPacket) HeaderID() uint16 { return HeaderUnitChatIn }

func (p *RoomEntitiesSayInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Message)
	w.WriteInt32(p.StyleId)
	return nil
}

func DecodeRoomEntitiesSayIn(r *codec.Reader) (*RoomEntitiesSayInPacket, error) {
	p := &RoomEntitiesSayInPacket{}
	var err error
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	if p.StyleId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitChatShoutIn uint16 = 2085

// RoomEntitiesShoutInPacket — Send a shout message visible to the whole room
type RoomEntitiesShoutInPacket struct {
	Message string
	StyleId int32
}

func (p *RoomEntitiesShoutInPacket) HeaderID() uint16 { return HeaderUnitChatShoutIn }

func (p *RoomEntitiesShoutInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Message)
	w.WriteInt32(p.StyleId)
	return nil
}

func DecodeRoomEntitiesShoutIn(r *codec.Reader) (*RoomEntitiesShoutInPacket, error) {
	p := &RoomEntitiesShoutInPacket{}
	var err error
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	if p.StyleId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserSettingsChatStyleIn uint16 = 1030

// RoomEntitiesSetChatStyleInPacket — Set the user's preferred chat bubble style
type RoomEntitiesSetChatStyleInPacket struct {
	StyleId int32
}

func (p *RoomEntitiesSetChatStyleInPacket) HeaderID() uint16 { return HeaderUserSettingsChatStyleIn }

func (p *RoomEntitiesSetChatStyleInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.StyleId)
	return nil
}

func DecodeRoomEntitiesSetChatStyleIn(r *codec.Reader) (*RoomEntitiesSetChatStyleInPacket, error) {
	p := &RoomEntitiesSetChatStyleInPacket{}
	var err error
	if p.StyleId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitChatWhisperIn uint16 = 1543

// RoomEntitiesWhisperInPacket — Send a private whisper to a specific user
type RoomEntitiesWhisperInPacket struct {
	TargetName string
	Message string
	StyleId int32
}

func (p *RoomEntitiesWhisperInPacket) HeaderID() uint16 { return HeaderUnitChatWhisperIn }

func (p *RoomEntitiesWhisperInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.TargetName)
	w.WriteString(p.Message)
	w.WriteInt32(p.StyleId)
	return nil
}

func DecodeRoomEntitiesWhisperIn(r *codec.Reader) (*RoomEntitiesWhisperInPacket, error) {
	p := &RoomEntitiesWhisperInPacket{}
	var err error
	if p.TargetName, err = r.ReadString(); err != nil { return nil, err }
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	if p.StyleId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitTypingIn uint16 = 1597

// RoomEntitiesTypingStartInPacket — Indicate the user has started typing
type RoomEntitiesTypingStartInPacket struct {
}

func (p *RoomEntitiesTypingStartInPacket) HeaderID() uint16 { return HeaderUnitTypingIn }

func (p *RoomEntitiesTypingStartInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomEntitiesTypingStartIn(r *codec.Reader) (*RoomEntitiesTypingStartInPacket, error) {
	p := &RoomEntitiesTypingStartInPacket{}
	return p, nil
}

const HeaderUnitTypingStopIn uint16 = 1474

// RoomEntitiesTypingStopInPacket — Indicate the user has stopped typing
type RoomEntitiesTypingStopInPacket struct {
}

func (p *RoomEntitiesTypingStopInPacket) HeaderID() uint16 { return HeaderUnitTypingStopIn }

func (p *RoomEntitiesTypingStopInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomEntitiesTypingStopIn(r *codec.Reader) (*RoomEntitiesTypingStopInPacket, error) {
	p := &RoomEntitiesTypingStopInPacket{}
	return p, nil
}

const HeaderUnitOut uint16 = 374

// RoomEntitiesUnitsOutPacket — Deliver a batch of room units (avatars, pets, bots)
type RoomEntitiesUnitsOutPacket struct {
	UnitCount int32
	Units []byte // TODO: hand-implement nested decode
}

func (p *RoomEntitiesUnitsOutPacket) HeaderID() uint16 { return HeaderUnitOut }

func (p *RoomEntitiesUnitsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UnitCount)
	w.WriteBytes(p.Units)
	return nil
}

func DecodeRoomEntitiesUnitsOut(r *codec.Reader) (*RoomEntitiesUnitsOutPacket, error) {
	p := &RoomEntitiesUnitsOutPacket{}
	var err error
	if p.UnitCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Units, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitStatusOut uint16 = 1640

// RoomEntitiesStatusOutPacket — Update unit positions and action states in the room
type RoomEntitiesStatusOutPacket struct {
	UnitCount int32
	Units []byte // TODO: hand-implement nested decode
}

func (p *RoomEntitiesStatusOutPacket) HeaderID() uint16 { return HeaderUnitStatusOut }

func (p *RoomEntitiesStatusOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UnitCount)
	w.WriteBytes(p.Units)
	return nil
}

func DecodeRoomEntitiesStatusOut(r *codec.Reader) (*RoomEntitiesStatusOutPacket, error) {
	p := &RoomEntitiesStatusOutPacket{}
	var err error
	if p.UnitCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Units, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitInfoOut uint16 = 3920

// RoomEntitiesInfoOutPacket — Update a unit's display information
type RoomEntitiesInfoOutPacket struct {
	RoomIndex int32
	Name string
	Custom string
	Figure string
	Gender string
	GroupId int32
	GroupStatus int32
	GroupName string
	ActivityPoints int32
	IsModerator bool
}

func (p *RoomEntitiesInfoOutPacket) HeaderID() uint16 { return HeaderUnitInfoOut }

func (p *RoomEntitiesInfoOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteString(p.Name)
	w.WriteString(p.Custom)
	w.WriteString(p.Figure)
	w.WriteString(p.Gender)
	w.WriteInt32(p.GroupId)
	w.WriteInt32(p.GroupStatus)
	w.WriteString(p.GroupName)
	w.WriteInt32(p.ActivityPoints)
	w.WriteBool(p.IsModerator)
	return nil
}

func DecodeRoomEntitiesInfoOut(r *codec.Reader) (*RoomEntitiesInfoOutPacket, error) {
	p := &RoomEntitiesInfoOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Name, err = r.ReadString(); err != nil { return nil, err }
	if p.Custom, err = r.ReadString(); err != nil { return nil, err }
	if p.Figure, err = r.ReadString(); err != nil { return nil, err }
	if p.Gender, err = r.ReadString(); err != nil { return nil, err }
	if p.GroupId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.GroupStatus, err = r.ReadInt32(); err != nil { return nil, err }
	if p.GroupName, err = r.ReadString(); err != nil { return nil, err }
	if p.ActivityPoints, err = r.ReadInt32(); err != nil { return nil, err }
	if p.IsModerator, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitChatOut uint16 = 1446

// RoomEntitiesChatOutPacket — Deliver a normal chat message from a room unit
type RoomEntitiesChatOutPacket struct {
	RoomIndex int32
	Message string
	Gesture int32
	BubbleStyle int32
	UrlCount int32
	Urls []string
	MessageLength int32
}

func (p *RoomEntitiesChatOutPacket) HeaderID() uint16 { return HeaderUnitChatOut }

func (p *RoomEntitiesChatOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteString(p.Message)
	w.WriteInt32(p.Gesture)
	w.WriteInt32(p.BubbleStyle)
	w.WriteInt32(p.UrlCount)
	w.WriteListString(p.Urls)
	w.WriteInt32(p.MessageLength)
	return nil
}

func DecodeRoomEntitiesChatOut(r *codec.Reader) (*RoomEntitiesChatOutPacket, error) {
	p := &RoomEntitiesChatOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	if p.Gesture, err = r.ReadInt32(); err != nil { return nil, err }
	if p.BubbleStyle, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UrlCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Urls, err = r.ReadListString(); err != nil { return nil, err }
	if p.MessageLength, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitChatShoutOut uint16 = 1036

// RoomEntitiesShoutOutPacket — Deliver a shout message from a room unit
type RoomEntitiesShoutOutPacket struct {
	RoomIndex int32
	Message string
	Gesture int32
	BubbleStyle int32
	UrlCount int32
	Urls []string
	MessageLength int32
}

func (p *RoomEntitiesShoutOutPacket) HeaderID() uint16 { return HeaderUnitChatShoutOut }

func (p *RoomEntitiesShoutOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteString(p.Message)
	w.WriteInt32(p.Gesture)
	w.WriteInt32(p.BubbleStyle)
	w.WriteInt32(p.UrlCount)
	w.WriteListString(p.Urls)
	w.WriteInt32(p.MessageLength)
	return nil
}

func DecodeRoomEntitiesShoutOut(r *codec.Reader) (*RoomEntitiesShoutOutPacket, error) {
	p := &RoomEntitiesShoutOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	if p.Gesture, err = r.ReadInt32(); err != nil { return nil, err }
	if p.BubbleStyle, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UrlCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Urls, err = r.ReadListString(); err != nil { return nil, err }
	if p.MessageLength, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitChatWhisperOut uint16 = 2704

// RoomEntitiesWhisperOutPacket — Deliver a private whisper to the recipient
type RoomEntitiesWhisperOutPacket struct {
	RoomIndex int32
	Message string
	Gesture int32
	BubbleStyle int32
	UrlCount int32
	Urls []string
	MessageLength int32
}

func (p *RoomEntitiesWhisperOutPacket) HeaderID() uint16 { return HeaderUnitChatWhisperOut }

func (p *RoomEntitiesWhisperOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteString(p.Message)
	w.WriteInt32(p.Gesture)
	w.WriteInt32(p.BubbleStyle)
	w.WriteInt32(p.UrlCount)
	w.WriteListString(p.Urls)
	w.WriteInt32(p.MessageLength)
	return nil
}

func DecodeRoomEntitiesWhisperOut(r *codec.Reader) (*RoomEntitiesWhisperOutPacket, error) {
	p := &RoomEntitiesWhisperOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	if p.Gesture, err = r.ReadInt32(); err != nil { return nil, err }
	if p.BubbleStyle, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UrlCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Urls, err = r.ReadListString(); err != nil { return nil, err }
	if p.MessageLength, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitDanceOut uint16 = 2233

// RoomEntitiesDanceOutPacket — Notify that a unit's dance animation changed
type RoomEntitiesDanceOutPacket struct {
	RoomIndex int32
	DanceId int32
}

func (p *RoomEntitiesDanceOutPacket) HeaderID() uint16 { return HeaderUnitDanceOut }

func (p *RoomEntitiesDanceOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteInt32(p.DanceId)
	return nil
}

func DecodeRoomEntitiesDanceOut(r *codec.Reader) (*RoomEntitiesDanceOutPacket, error) {
	p := &RoomEntitiesDanceOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.DanceId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitEffectOut uint16 = 1167

// RoomEntitiesEffectOutPacket — Notify that a unit's avatar effect changed
type RoomEntitiesEffectOutPacket struct {
	RoomIndex int32
	EffectId int32
	DelayMs int32
}

func (p *RoomEntitiesEffectOutPacket) HeaderID() uint16 { return HeaderUnitEffectOut }

func (p *RoomEntitiesEffectOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteInt32(p.EffectId)
	w.WriteInt32(p.DelayMs)
	return nil
}

func DecodeRoomEntitiesEffectOut(r *codec.Reader) (*RoomEntitiesEffectOutPacket, error) {
	p := &RoomEntitiesEffectOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.EffectId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.DelayMs, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitExpressionOut uint16 = 1631

// RoomEntitiesExpressionOutPacket — Notify that a unit performed an expression or gesture
type RoomEntitiesExpressionOutPacket struct {
	RoomIndex int32
	ExpressionId int32
}

func (p *RoomEntitiesExpressionOutPacket) HeaderID() uint16 { return HeaderUnitExpressionOut }

func (p *RoomEntitiesExpressionOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteInt32(p.ExpressionId)
	return nil
}

func DecodeRoomEntitiesExpressionOut(r *codec.Reader) (*RoomEntitiesExpressionOutPacket, error) {
	p := &RoomEntitiesExpressionOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ExpressionId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitHandItemOut uint16 = 1474

// RoomEntitiesHandItemOutPacket — Notify that a unit is carrying a hand item
type RoomEntitiesHandItemOutPacket struct {
	RoomIndex int32
	ItemId int32
}

func (p *RoomEntitiesHandItemOutPacket) HeaderID() uint16 { return HeaderUnitHandItemOut }

func (p *RoomEntitiesHandItemOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeRoomEntitiesHandItemOut(r *codec.Reader) (*RoomEntitiesHandItemOutPacket, error) {
	p := &RoomEntitiesHandItemOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitIdleOut uint16 = 1797

// RoomEntitiesIdleOutPacket — Notify that a unit entered or left idle state
type RoomEntitiesIdleOutPacket struct {
	RoomIndex int32
	Idle bool
}

func (p *RoomEntitiesIdleOutPacket) HeaderID() uint16 { return HeaderUnitIdleOut }

func (p *RoomEntitiesIdleOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteBool(p.Idle)
	return nil
}

func DecodeRoomEntitiesIdleOut(r *codec.Reader) (*RoomEntitiesIdleOutPacket, error) {
	p := &RoomEntitiesIdleOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Idle, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitNumberOut uint16 = 2324

// RoomEntitiesNumberOutPacket — Assign or confirm the user's room index
type RoomEntitiesNumberOutPacket struct {
	RoomIndex int32
}

func (p *RoomEntitiesNumberOutPacket) HeaderID() uint16 { return HeaderUnitNumberOut }

func (p *RoomEntitiesNumberOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	return nil
}

func DecodeRoomEntitiesNumberOut(r *codec.Reader) (*RoomEntitiesNumberOutPacket, error) {
	p := &RoomEntitiesNumberOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitRemoveOut uint16 = 2661

// RoomEntitiesRemovedOutPacket — Notify that a unit was removed from the room
type RoomEntitiesRemovedOutPacket struct {
	RoomIndex int32
}

func (p *RoomEntitiesRemovedOutPacket) HeaderID() uint16 { return HeaderUnitRemoveOut }

func (p *RoomEntitiesRemovedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	return nil
}

func DecodeRoomEntitiesRemovedOut(r *codec.Reader) (*RoomEntitiesRemovedOutPacket, error) {
	p := &RoomEntitiesRemovedOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitTypingOut uint16 = 1717

// RoomEntitiesTypingOutPacket — Notify that a unit's typing status changed
type RoomEntitiesTypingOutPacket struct {
	RoomIndex int32
	Typing int32
}

func (p *RoomEntitiesTypingOutPacket) HeaderID() uint16 { return HeaderUnitTypingOut }

func (p *RoomEntitiesTypingOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomIndex)
	w.WriteInt32(p.Typing)
	return nil
}

func DecodeRoomEntitiesTypingOut(r *codec.Reader) (*RoomEntitiesTypingOutPacket, error) {
	p := &RoomEntitiesTypingOutPacket{}
	var err error
	if p.RoomIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Typing, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderBotSkillListUpdateOut uint16 = 69

// RoomBotSkillListUpdateOutPacket — Bot skill list update
type RoomBotSkillListUpdateOutPacket struct {
	Field1 int32
	Field2 int32
}

func (p *RoomBotSkillListUpdateOutPacket) HeaderID() uint16 { return HeaderBotSkillListUpdateOut }

func (p *RoomBotSkillListUpdateOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeRoomBotSkillListUpdateOut(r *codec.Reader) (*RoomBotSkillListUpdateOutPacket, error) {
	p := &RoomBotSkillListUpdateOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderBotForceOpenContextMenuOut uint16 = 296

// RoomBotForceOpenContextMenuOutPacket — Bot force open context menu
type RoomBotForceOpenContextMenuOutPacket struct {
	Field1 int32
}

func (p *RoomBotForceOpenContextMenuOutPacket) HeaderID() uint16 { return HeaderBotForceOpenContextMenuOut }

func (p *RoomBotForceOpenContextMenuOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	return nil
}

func DecodeRoomBotForceOpenContextMenuOut(r *codec.Reader) (*RoomBotForceOpenContextMenuOutPacket, error) {
	p := &RoomBotForceOpenContextMenuOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderHandItemReceivedOut uint16 = 354

// RoomHandItemReceivedOutPacket — Hand item received
type RoomHandItemReceivedOutPacket struct {
	Field1 int32
	Field2 int32
}

func (p *RoomHandItemReceivedOutPacket) HeaderID() uint16 { return HeaderHandItemReceivedOut }

func (p *RoomHandItemReceivedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeRoomHandItemReceivedOut(r *codec.Reader) (*RoomHandItemReceivedOutPacket, error) {
	p := &RoomHandItemReceivedOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderBotErrorOut uint16 = 639

// RoomBotErrorOutPacket — Bot error
type RoomBotErrorOutPacket struct {
	Field1 int32
}

func (p *RoomBotErrorOutPacket) HeaderID() uint16 { return HeaderBotErrorOut }

func (p *RoomBotErrorOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	return nil
}

func DecodeRoomBotErrorOut(r *codec.Reader) (*RoomBotErrorOutPacket, error) {
	p := &RoomBotErrorOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderBotCommandConfigurationOut uint16 = 1618

// RoomBotCommandConfigurationOutPacket — Bot command configuration
type RoomBotCommandConfigurationOutPacket struct {
	Field1 int32
	Field2 int32
	Field3 string
}

func (p *RoomBotCommandConfigurationOutPacket) HeaderID() uint16 { return HeaderBotCommandConfigurationOut }

func (p *RoomBotCommandConfigurationOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteString(p.Field3)
	return nil
}

func DecodeRoomBotCommandConfigurationOut(r *codec.Reader) (*RoomBotCommandConfigurationOutPacket, error) {
	p := &RoomBotCommandConfigurationOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderBotReceivedOut uint16 = 3684

// RoomBotReceivedOutPacket — Bot received
type RoomBotReceivedOutPacket struct {
	Field1 bool
}

func (p *RoomBotReceivedOutPacket) HeaderID() uint16 { return HeaderBotReceivedOut }

func (p *RoomBotReceivedOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.Field1)
	return nil
}

func DecodeRoomBotReceivedOut(r *codec.Reader) (*RoomBotReceivedOutPacket, error) {
	p := &RoomBotReceivedOutPacket{}
	var err error
	if p.Field1, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

