// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderRoomEnterIn uint16 = 2312

// RoomEnterInPacket — Enter a room by its flat ID
type RoomEnterInPacket struct {
	FlatId int32
}

func (p *RoomEnterInPacket) HeaderID() uint16 { return HeaderRoomEnterIn }

func (p *RoomEnterInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.FlatId)
	return nil
}

func DecodeRoomEnterIn(r *codec.Reader) (*RoomEnterInPacket, error) {
	p := &RoomEnterInPacket{}
	var err error
	if p.FlatId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomDoorbellIn uint16 = 1644

// RoomDoorbellInPacket — Ring the doorbell of a locked room
type RoomDoorbellInPacket struct {
	Username string
}

func (p *RoomDoorbellInPacket) HeaderID() uint16 { return HeaderRoomDoorbellIn }

func (p *RoomDoorbellInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Username)
	return nil
}

func DecodeRoomDoorbellIn(r *codec.Reader) (*RoomDoorbellInPacket, error) {
	p := &RoomDoorbellInPacket{}
	var err error
	if p.Username, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomAmbassadorAlertIn uint16 = 2996

// RoomAmbassadorAlertInPacket — Send an ambassador alert in the current room
type RoomAmbassadorAlertInPacket struct {
	Message string
}

func (p *RoomAmbassadorAlertInPacket) HeaderID() uint16 { return HeaderRoomAmbassadorAlertIn }

func (p *RoomAmbassadorAlertInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Message)
	return nil
}

func DecodeRoomAmbassadorAlertIn(r *codec.Reader) (*RoomAmbassadorAlertInPacket, error) {
	p := &RoomAmbassadorAlertInPacket{}
	var err error
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomBanGiveIn uint16 = 1477

// RoomBanUserInPacket — Ban a user from the room
type RoomBanUserInPacket struct {
	UserId int32
	RoomId int32
	Length string
}

func (p *RoomBanUserInPacket) HeaderID() uint16 { return HeaderRoomBanGiveIn }

func (p *RoomBanUserInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	w.WriteInt32(p.RoomId)
	w.WriteString(p.Length)
	return nil
}

func DecodeRoomBanUserIn(r *codec.Reader) (*RoomBanUserInPacket, error) {
	p := &RoomBanUserInPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Length, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomBanRemoveIn uint16 = 992

// RoomUnbanUserInPacket — Remove a ban from a user in the room
type RoomUnbanUserInPacket struct {
	UserId int32
	RoomId int32
}

func (p *RoomUnbanUserInPacket) HeaderID() uint16 { return HeaderRoomBanRemoveIn }

func (p *RoomUnbanUserInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomUnbanUserIn(r *codec.Reader) (*RoomUnbanUserInPacket, error) {
	p := &RoomUnbanUserInPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomRightsGiveIn uint16 = 808

// RoomGiveRightsInPacket — Grant room rights to a user
type RoomGiveRightsInPacket struct {
	UserId int32
}

func (p *RoomGiveRightsInPacket) HeaderID() uint16 { return HeaderRoomRightsGiveIn }

func (p *RoomGiveRightsInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeRoomGiveRightsIn(r *codec.Reader) (*RoomGiveRightsInPacket, error) {
	p := &RoomGiveRightsInPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomKickIn uint16 = 1320

// RoomKickUserInPacket — Kick a user from the room
type RoomKickUserInPacket struct {
	UserId int32
}

func (p *RoomKickUserInPacket) HeaderID() uint16 { return HeaderRoomKickIn }

func (p *RoomKickUserInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeRoomKickUserIn(r *codec.Reader) (*RoomKickUserInPacket, error) {
	p := &RoomKickUserInPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomMuteUserIn uint16 = 3485

// RoomMuteUserInPacket — Mute a specific user in the room
type RoomMuteUserInPacket struct {
	UserId int32
	RoomId int32
	Minutes int32
}

func (p *RoomMuteUserInPacket) HeaderID() uint16 { return HeaderRoomMuteUserIn }

func (p *RoomMuteUserInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	w.WriteInt32(p.RoomId)
	w.WriteInt32(p.Minutes)
	return nil
}

func DecodeRoomMuteUserIn(r *codec.Reader) (*RoomMuteUserInPacket, error) {
	p := &RoomMuteUserInPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Minutes, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomRightsRemoveIn uint16 = 2064

// RoomTakeRightsInPacket — Remove room rights from a specific user
type RoomTakeRightsInPacket struct {
	UserId int32
}

func (p *RoomTakeRightsInPacket) HeaderID() uint16 { return HeaderRoomRightsRemoveIn }

func (p *RoomTakeRightsInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeRoomTakeRightsIn(r *codec.Reader) (*RoomTakeRightsInPacket, error) {
	p := &RoomTakeRightsInPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomRightsRemoveAllIn uint16 = 2683

// RoomRemoveAllRightsInPacket — Remove rights from all users in the room
type RoomRemoveAllRightsInPacket struct {
	RoomId int32
}

func (p *RoomRemoveAllRightsInPacket) HeaderID() uint16 { return HeaderRoomRightsRemoveAllIn }

func (p *RoomRemoveAllRightsInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomRemoveAllRightsIn(r *codec.Reader) (*RoomRemoveAllRightsInPacket, error) {
	p := &RoomRemoveAllRightsInPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomDeleteIn uint16 = 532

// RoomDeleteInPacket — Delete the room
type RoomDeleteInPacket struct {
	RoomId int32
}

func (p *RoomDeleteInPacket) HeaderID() uint16 { return HeaderRoomDeleteIn }

func (p *RoomDeleteInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomDeleteIn(r *codec.Reader) (*RoomDeleteInPacket, error) {
	p := &RoomDeleteInPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomSettingsIn uint16 = 3129

// RoomGetSettingsInPacket — Request the full room settings record
type RoomGetSettingsInPacket struct {
	RoomId int32
}

func (p *RoomGetSettingsInPacket) HeaderID() uint16 { return HeaderRoomSettingsIn }

func (p *RoomGetSettingsInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomGetSettingsIn(r *codec.Reader) (*RoomGetSettingsInPacket, error) {
	p := &RoomGetSettingsInPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomSettingsSaveIn uint16 = 1969

// RoomSaveSettingsInPacket — Save updated room settings
type RoomSaveSettingsInPacket struct {
	RoomId int32
	RoomName string
	RoomDescription string
	LockState int32
	Password string
	UserCount int32
	CategoryId int32
	TagsCount int32
	Tags []string
	TradeState int32
	AllowPets bool
	AllowPetsEat bool
	AllowWalkthrough bool
	HideWalls bool
	WallThickness int32
	FloorThickness int32
	MuteState int32
	KickState int32
	BanState int32
	ChatBubbleMode int32
	ChatBubbleWeight int32
	ChatBubbleSpeed int32
	ChatDistance int32
	ChatFloodProtection int32
}

func (p *RoomSaveSettingsInPacket) HeaderID() uint16 { return HeaderRoomSettingsSaveIn }

func (p *RoomSaveSettingsInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	w.WriteString(p.RoomName)
	w.WriteString(p.RoomDescription)
	w.WriteInt32(p.LockState)
	w.WriteString(p.Password)
	w.WriteInt32(p.UserCount)
	w.WriteInt32(p.CategoryId)
	w.WriteInt32(p.TagsCount)
	w.WriteListString(p.Tags)
	w.WriteInt32(p.TradeState)
	w.WriteBool(p.AllowPets)
	w.WriteBool(p.AllowPetsEat)
	w.WriteBool(p.AllowWalkthrough)
	w.WriteBool(p.HideWalls)
	w.WriteInt32(p.WallThickness)
	w.WriteInt32(p.FloorThickness)
	w.WriteInt32(p.MuteState)
	w.WriteInt32(p.KickState)
	w.WriteInt32(p.BanState)
	w.WriteInt32(p.ChatBubbleMode)
	w.WriteInt32(p.ChatBubbleWeight)
	w.WriteInt32(p.ChatBubbleSpeed)
	w.WriteInt32(p.ChatDistance)
	w.WriteInt32(p.ChatFloodProtection)
	return nil
}

func DecodeRoomSaveSettingsIn(r *codec.Reader) (*RoomSaveSettingsInPacket, error) {
	p := &RoomSaveSettingsInPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RoomName, err = r.ReadString(); err != nil { return nil, err }
	if p.RoomDescription, err = r.ReadString(); err != nil { return nil, err }
	if p.LockState, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Password, err = r.ReadString(); err != nil { return nil, err }
	if p.UserCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.CategoryId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.TagsCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Tags, err = r.ReadListString(); err != nil { return nil, err }
	if p.TradeState, err = r.ReadInt32(); err != nil { return nil, err }
	if p.AllowPets, err = r.ReadBool(); err != nil { return nil, err }
	if p.AllowPetsEat, err = r.ReadBool(); err != nil { return nil, err }
	if p.AllowWalkthrough, err = r.ReadBool(); err != nil { return nil, err }
	if p.HideWalls, err = r.ReadBool(); err != nil { return nil, err }
	if p.WallThickness, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FloorThickness, err = r.ReadInt32(); err != nil { return nil, err }
	if p.MuteState, err = r.ReadInt32(); err != nil { return nil, err }
	if p.KickState, err = r.ReadInt32(); err != nil { return nil, err }
	if p.BanState, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ChatBubbleMode, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ChatBubbleWeight, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ChatBubbleSpeed, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ChatDistance, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ChatFloodProtection, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomRightsListIn uint16 = 3385

// RoomGetRightsListInPacket — Request the list of users with room rights
type RoomGetRightsListInPacket struct {
	RoomId int32
}

func (p *RoomGetRightsListInPacket) HeaderID() uint16 { return HeaderRoomRightsListIn }

func (p *RoomGetRightsListInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomGetRightsListIn(r *codec.Reader) (*RoomGetRightsListInPacket, error) {
	p := &RoomGetRightsListInPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomBanListIn uint16 = 2267

// RoomGetBanListInPacket — Request the room ban list
type RoomGetBanListInPacket struct {
	RoomId int32
	PageIndex int32
}

func (p *RoomGetBanListInPacket) HeaderID() uint16 { return HeaderRoomBanListIn }

func (p *RoomGetBanListInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	w.WriteInt32(p.PageIndex)
	return nil
}

func DecodeRoomGetBanListIn(r *codec.Reader) (*RoomGetBanListInPacket, error) {
	p := &RoomGetBanListInPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PageIndex, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomMuteIn uint16 = 3637

// RoomToggleMuteInPacket — Toggle room-wide mute for all users
type RoomToggleMuteInPacket struct {
	RoomId int32
}

func (p *RoomToggleMuteInPacket) HeaderID() uint16 { return HeaderRoomMuteIn }

func (p *RoomToggleMuteInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomToggleMuteIn(r *codec.Reader) (*RoomToggleMuteInPacket, error) {
	p := &RoomToggleMuteInPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomModelIn uint16 = 2300

// RoomGetModelInPacket — Request the room layout model and entry data
type RoomGetModelInPacket struct {
}

func (p *RoomGetModelInPacket) HeaderID() uint16 { return HeaderRoomModelIn }

func (p *RoomGetModelInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomGetModelIn(r *codec.Reader) (*RoomGetModelInPacket, error) {
	p := &RoomGetModelInPacket{}
	return p, nil
}

const HeaderGetRoomEntryTileIn uint16 = 3559

// RoomGetEntryTileInPacket — Request the room entry tile position
type RoomGetEntryTileInPacket struct {
}

func (p *RoomGetEntryTileInPacket) HeaderID() uint16 { return HeaderGetRoomEntryTileIn }

func (p *RoomGetEntryTileInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomGetEntryTileIn(r *codec.Reader) (*RoomGetEntryTileInPacket, error) {
	p := &RoomGetEntryTileInPacket{}
	return p, nil
}

const HeaderRoomModelSaveIn uint16 = 875

// RoomSaveFloorPlanInPacket — Save an updated room floor plan
type RoomSaveFloorPlanInPacket struct {
	WallHeight int32
	HideWalls bool
	WallThickness int32
	FloorThickness int32
	HeightmapString string
}

func (p *RoomSaveFloorPlanInPacket) HeaderID() uint16 { return HeaderRoomModelSaveIn }

func (p *RoomSaveFloorPlanInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.WallHeight)
	w.WriteBool(p.HideWalls)
	w.WriteInt32(p.WallThickness)
	w.WriteInt32(p.FloorThickness)
	w.WriteString(p.HeightmapString)
	return nil
}

func DecodeRoomSaveFloorPlanIn(r *codec.Reader) (*RoomSaveFloorPlanInPacket, error) {
	p := &RoomSaveFloorPlanInPacket{}
	var err error
	if p.WallHeight, err = r.ReadInt32(); err != nil { return nil, err }
	if p.HideWalls, err = r.ReadBool(); err != nil { return nil, err }
	if p.WallThickness, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FloorThickness, err = r.ReadInt32(); err != nil { return nil, err }
	if p.HeightmapString, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetOccupiedTilesIn uint16 = 1687

// RoomGetOccupiedTilesInPacket — Request the set of occupied tiles in the room
type RoomGetOccupiedTilesInPacket struct {
}

func (p *RoomGetOccupiedTilesInPacket) HeaderID() uint16 { return HeaderGetOccupiedTilesIn }

func (p *RoomGetOccupiedTilesInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomGetOccupiedTilesIn(r *codec.Reader) (*RoomGetOccupiedTilesInPacket, error) {
	p := &RoomGetOccupiedTilesInPacket{}
	return p, nil
}

const HeaderRoomLikeIn uint16 = 3582

// RoomLikeInPacket — Like the current room
type RoomLikeInPacket struct {
	RoomId int32
}

func (p *RoomLikeInPacket) HeaderID() uint16 { return HeaderRoomLikeIn }

func (p *RoomLikeInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomLikeIn(r *codec.Reader) (*RoomLikeInPacket, error) {
	p := &RoomLikeInPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomRightsRemoveOwnIn uint16 = 3182

// RoomRemoveOwnRightsInPacket — Relinquish the user's own room rights
type RoomRemoveOwnRightsInPacket struct {
	RoomId int32
}

func (p *RoomRemoveOwnRightsInPacket) HeaderID() uint16 { return HeaderRoomRightsRemoveOwnIn }

func (p *RoomRemoveOwnRightsInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomRemoveOwnRightsIn(r *codec.Reader) (*RoomRemoveOwnRightsInPacket, error) {
	p := &RoomRemoveOwnRightsInPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderChangeQueueIn uint16 = 3093

// RoomChangeQueueInPacket — Change the user's position in the room queue
type RoomChangeQueueInPacket struct {
	NewQueueId int32
}

func (p *RoomChangeQueueInPacket) HeaderID() uint16 { return HeaderChangeQueueIn }

func (p *RoomChangeQueueInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.NewQueueId)
	return nil
}

func DecodeRoomChangeQueueIn(r *codec.Reader) (*RoomChangeQueueInPacket, error) {
	p := &RoomChangeQueueInPacket{}
	var err error
	if p.NewQueueId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderBotConfigurationIn uint16 = 1986

// RoomGetBotConfigurationInPacket — Request the configuration panel for a bot
type RoomGetBotConfigurationInPacket struct {
	BotId int32
}

func (p *RoomGetBotConfigurationInPacket) HeaderID() uint16 { return HeaderBotConfigurationIn }

func (p *RoomGetBotConfigurationInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.BotId)
	return nil
}

func DecodeRoomGetBotConfigurationIn(r *codec.Reader) (*RoomGetBotConfigurationInPacket, error) {
	p := &RoomGetBotConfigurationInPacket{}
	var err error
	if p.BotId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderBotPlaceIn uint16 = 1592

// RoomPlaceBotInPacket — Place a bot from inventory into the room
type RoomPlaceBotInPacket struct {
	BotId int32
	X int32
	Y int32
}

func (p *RoomPlaceBotInPacket) HeaderID() uint16 { return HeaderBotPlaceIn }

func (p *RoomPlaceBotInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.BotId)
	w.WriteInt32(p.X)
	w.WriteInt32(p.Y)
	return nil
}

func DecodeRoomPlaceBotIn(r *codec.Reader) (*RoomPlaceBotInPacket, error) {
	p := &RoomPlaceBotInPacket{}
	var err error
	if p.BotId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.X, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Y, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderBotPickupIn uint16 = 3323

// RoomPickupBotInPacket — Remove a bot from the room into inventory
type RoomPickupBotInPacket struct {
	BotId int32
}

func (p *RoomPickupBotInPacket) HeaderID() uint16 { return HeaderBotPickupIn }

func (p *RoomPickupBotInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.BotId)
	return nil
}

func DecodeRoomPickupBotIn(r *codec.Reader) (*RoomPickupBotInPacket, error) {
	p := &RoomPickupBotInPacket{}
	var err error
	if p.BotId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderBotSkillSaveIn uint16 = 2624

// RoomSaveBotSkillInPacket — Save a bot skill configuration
type RoomSaveBotSkillInPacket struct {
	BotId int32
	SkillId int32
	Data string
}

func (p *RoomSaveBotSkillInPacket) HeaderID() uint16 { return HeaderBotSkillSaveIn }

func (p *RoomSaveBotSkillInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.BotId)
	w.WriteInt32(p.SkillId)
	w.WriteString(p.Data)
	return nil
}

func DecodeRoomSaveBotSkillIn(r *codec.Reader) (*RoomSaveBotSkillInPacket, error) {
	p := &RoomSaveBotSkillInPacket{}
	var err error
	if p.BotId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SkillId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Data, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderSetObjectDataIn uint16 = 3608

// RoomSetObjectDataInPacket — Set extra data on a room object
type RoomSetObjectDataInPacket struct {
	ObjectId int32
	Data string
}

func (p *RoomSetObjectDataInPacket) HeaderID() uint16 { return HeaderSetObjectDataIn }

func (p *RoomSetObjectDataInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ObjectId)
	w.WriteString(p.Data)
	return nil
}

func DecodeRoomSetObjectDataIn(r *codec.Reader) (*RoomSetObjectDataInPacket, error) {
	p := &RoomSetObjectDataInPacket{}
	var err error
	if p.ObjectId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Data, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetItemDataIn uint16 = 3964

// RoomGetItemDataInPacket — Request extra data for a specific room item
type RoomGetItemDataInPacket struct {
	ItemId int32
}

func (p *RoomGetItemDataInPacket) HeaderID() uint16 { return HeaderGetItemDataIn }

func (p *RoomGetItemDataInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	return nil
}

func DecodeRoomGetItemDataIn(r *codec.Reader) (*RoomGetItemDataInPacket, error) {
	p := &RoomGetItemDataInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderSetItemDataIn uint16 = 3666

// RoomSetItemDataInPacket — Update the data of a floor item
type RoomSetItemDataInPacket struct {
	ItemId int32
	Data string
}

func (p *RoomSetItemDataInPacket) HeaderID() uint16 { return HeaderSetItemDataIn }

func (p *RoomSetItemDataInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteString(p.Data)
	return nil
}

func DecodeRoomSetItemDataIn(r *codec.Reader) (*RoomSetItemDataInPacket, error) {
	p := &RoomSetItemDataInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Data, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderSetClothingChangeDataIn uint16 = 924

// RoomSetClothingChangeDataInPacket — Set clothing change data for an avatar figure object
type RoomSetClothingChangeDataInPacket struct {
	ItemId int32
	Gender string
	Figure string
}

func (p *RoomSetClothingChangeDataInPacket) HeaderID() uint16 { return HeaderSetClothingChangeDataIn }

func (p *RoomSetClothingChangeDataInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ItemId)
	w.WriteString(p.Gender)
	w.WriteString(p.Figure)
	return nil
}

func DecodeRoomSetClothingChangeDataIn(r *codec.Reader) (*RoomSetClothingChangeDataInPacket, error) {
	p := &RoomSetClothingChangeDataInPacket{}
	var err error
	if p.ItemId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Gender, err = r.ReadString(); err != nil { return nil, err }
	if p.Figure, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderVoteForRoomIn uint16 = 143

// RoomVoteForRoomInPacket — Vote for room
type RoomVoteForRoomInPacket struct {
}

func (p *RoomVoteForRoomInPacket) HeaderID() uint16 { return HeaderVoteForRoomIn }

func (p *RoomVoteForRoomInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomVoteForRoomIn(r *codec.Reader) (*RoomVoteForRoomInPacket, error) {
	p := &RoomVoteForRoomInPacket{}
	return p, nil
}

const HeaderPurchaseRoomAdIn uint16 = 777

// RoomPurchaseRoomAdInPacket — Purchase room ad
type RoomPurchaseRoomAdInPacket struct {
}

func (p *RoomPurchaseRoomAdInPacket) HeaderID() uint16 { return HeaderPurchaseRoomAdIn }

func (p *RoomPurchaseRoomAdInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomPurchaseRoomAdIn(r *codec.Reader) (*RoomPurchaseRoomAdInPacket, error) {
	p := &RoomPurchaseRoomAdInPacket{}
	return p, nil
}

const HeaderGetPopularRoomTagsIn uint16 = 826

// RoomPopularRoomTagsInPacket — Get popular room tags
type RoomPopularRoomTagsInPacket struct {
}

func (p *RoomPopularRoomTagsInPacket) HeaderID() uint16 { return HeaderGetPopularRoomTagsIn }

func (p *RoomPopularRoomTagsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomPopularRoomTagsIn(r *codec.Reader) (*RoomPopularRoomTagsInPacket, error) {
	p := &RoomPopularRoomTagsInPacket{}
	return p, nil
}

const HeaderGetRoomAdPurchaseInfoIn uint16 = 1075

// RoomRoomAdPurchaseInfoInPacket — Get room ad purchase info
type RoomRoomAdPurchaseInfoInPacket struct {
}

func (p *RoomRoomAdPurchaseInfoInPacket) HeaderID() uint16 { return HeaderGetRoomAdPurchaseInfoIn }

func (p *RoomRoomAdPurchaseInfoInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomRoomAdPurchaseInfoIn(r *codec.Reader) (*RoomRoomAdPurchaseInfoInPacket, error) {
	p := &RoomRoomAdPurchaseInfoInPacket{}
	return p, nil
}

const HeaderRoomFilterWordsIn uint16 = 1911

// RoomRoomFilterWordsInPacket — Room filter words
type RoomRoomFilterWordsInPacket struct {
}

func (p *RoomRoomFilterWordsInPacket) HeaderID() uint16 { return HeaderRoomFilterWordsIn }

func (p *RoomRoomFilterWordsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomRoomFilterWordsIn(r *codec.Reader) (*RoomRoomFilterWordsInPacket, error) {
	p := &RoomRoomFilterWordsInPacket{}
	return p, nil
}

const HeaderRoomStaffPickIn uint16 = 1918

// RoomRoomStaffPickInPacket — Room staff pick
type RoomRoomStaffPickInPacket struct {
}

func (p *RoomRoomStaffPickInPacket) HeaderID() uint16 { return HeaderRoomStaffPickIn }

func (p *RoomRoomStaffPickInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomRoomStaffPickIn(r *codec.Reader) (*RoomRoomStaffPickInPacket, error) {
	p := &RoomRoomStaffPickInPacket{}
	return p, nil
}

const HeaderRoomAdPurchaseInitiatedIn uint16 = 2283

// RoomRoomAdPurchaseInitiatedInPacket — Room ad purchase initiated
type RoomRoomAdPurchaseInitiatedInPacket struct {
}

func (p *RoomRoomAdPurchaseInitiatedInPacket) HeaderID() uint16 { return HeaderRoomAdPurchaseInitiatedIn }

func (p *RoomRoomAdPurchaseInitiatedInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomRoomAdPurchaseInitiatedIn(r *codec.Reader) (*RoomRoomAdPurchaseInitiatedInPacket, error) {
	p := &RoomRoomAdPurchaseInitiatedInPacket{}
	return p, nil
}

const HeaderRoomAdEventTabClickedIn uint16 = 2412

// RoomRoomAdEventTabClickedInPacket — Room ad event tab clicked
type RoomRoomAdEventTabClickedInPacket struct {
}

func (p *RoomRoomAdEventTabClickedInPacket) HeaderID() uint16 { return HeaderRoomAdEventTabClickedIn }

func (p *RoomRoomAdEventTabClickedInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomRoomAdEventTabClickedIn(r *codec.Reader) (*RoomRoomAdEventTabClickedInPacket, error) {
	p := &RoomRoomAdEventTabClickedInPacket{}
	return p, nil
}

const HeaderRoomAdEventTabViewedIn uint16 = 2668

// RoomRoomAdEventTabViewedInPacket — Room ad event tab viewed
type RoomRoomAdEventTabViewedInPacket struct {
}

func (p *RoomRoomAdEventTabViewedInPacket) HeaderID() uint16 { return HeaderRoomAdEventTabViewedIn }

func (p *RoomRoomAdEventTabViewedInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomRoomAdEventTabViewedIn(r *codec.Reader) (*RoomRoomAdEventTabViewedInPacket, error) {
	p := &RoomRoomAdEventTabViewedInPacket{}
	return p, nil
}

const HeaderCancelRoomEventIn uint16 = 2725

// RoomCancelRoomEventInPacket — Cancel room event
type RoomCancelRoomEventInPacket struct {
}

func (p *RoomCancelRoomEventInPacket) HeaderID() uint16 { return HeaderCancelRoomEventIn }

func (p *RoomCancelRoomEventInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomCancelRoomEventIn(r *codec.Reader) (*RoomCancelRoomEventInPacket, error) {
	p := &RoomCancelRoomEventInPacket{}
	return p, nil
}

const HeaderRoomAdSearchIn uint16 = 2809

// RoomRoomAdSearchInPacket — Room ad search
type RoomRoomAdSearchInPacket struct {
}

func (p *RoomRoomAdSearchInPacket) HeaderID() uint16 { return HeaderRoomAdSearchIn }

func (p *RoomRoomAdSearchInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomRoomAdSearchIn(r *codec.Reader) (*RoomRoomAdSearchInPacket, error) {
	p := &RoomRoomAdSearchInPacket{}
	return p, nil
}

const HeaderRoomFilterWordsModifyIn uint16 = 3001

// RoomRoomFilterWordsModifyInPacket — Room filter words modify
type RoomRoomFilterWordsModifyInPacket struct {
}

func (p *RoomRoomFilterWordsModifyInPacket) HeaderID() uint16 { return HeaderRoomFilterWordsModifyIn }

func (p *RoomRoomFilterWordsModifyInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomRoomFilterWordsModifyIn(r *codec.Reader) (*RoomRoomFilterWordsModifyInPacket, error) {
	p := &RoomRoomFilterWordsModifyInPacket{}
	return p, nil
}

const HeaderSetRoomSessionTagsIn uint16 = 3305

// RoomRoomSessionTagsInPacket — Set room session tags
type RoomRoomSessionTagsInPacket struct {
}

func (p *RoomRoomSessionTagsInPacket) HeaderID() uint16 { return HeaderSetRoomSessionTagsIn }

func (p *RoomRoomSessionTagsInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomRoomSessionTagsIn(r *codec.Reader) (*RoomRoomSessionTagsInPacket, error) {
	p := &RoomRoomSessionTagsInPacket{}
	return p, nil
}

const HeaderRoomDirectoryRoomNetworkOpenConnectionIn uint16 = 3736

// RoomRoomDirectoryRoomNetworkOpenConnectionInPacket — Room directory room network open connection
type RoomRoomDirectoryRoomNetworkOpenConnectionInPacket struct {
}

func (p *RoomRoomDirectoryRoomNetworkOpenConnectionInPacket) HeaderID() uint16 { return HeaderRoomDirectoryRoomNetworkOpenConnectionIn }

func (p *RoomRoomDirectoryRoomNetworkOpenConnectionInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomRoomDirectoryRoomNetworkOpenConnectionIn(r *codec.Reader) (*RoomRoomDirectoryRoomNetworkOpenConnectionInPacket, error) {
	p := &RoomRoomDirectoryRoomNetworkOpenConnectionInPacket{}
	return p, nil
}

const HeaderEditRoomEventIn uint16 = 3991

// RoomEditRoomEventInPacket — Edit room event
type RoomEditRoomEventInPacket struct {
}

func (p *RoomEditRoomEventInPacket) HeaderID() uint16 { return HeaderEditRoomEventIn }

func (p *RoomEditRoomEventInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomEditRoomEventIn(r *codec.Reader) (*RoomEditRoomEventInPacket, error) {
	p := &RoomEditRoomEventInPacket{}
	return p, nil
}

const HeaderRoomBanListOut uint16 = 1869

// RoomBanListOutPacket — Deliver the list of users banned from the room
type RoomBanListOutPacket struct {
	RoomId int32
	BannedUsers []byte // TODO: hand-implement nested decode
}

func (p *RoomBanListOutPacket) HeaderID() uint16 { return HeaderRoomBanListOut }

func (p *RoomBanListOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	w.WriteBytes(p.BannedUsers)
	return nil
}

func DecodeRoomBanListOut(r *codec.Reader) (*RoomBanListOutPacket, error) {
	p := &RoomBanListOutPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.BannedUsers, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomBanRemoveOut uint16 = 3429

// RoomBanRemovedOutPacket — Notify that a ban has been removed
type RoomBanRemovedOutPacket struct {
	RoomId int32
	UserId int32
}

func (p *RoomBanRemovedOutPacket) HeaderID() uint16 { return HeaderRoomBanRemoveOut }

func (p *RoomBanRemovedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeRoomBanRemovedOut(r *codec.Reader) (*RoomBanRemovedOutPacket, error) {
	p := &RoomBanRemovedOutPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomDoorbellOut uint16 = 2309

// RoomDoorbellRingingOutPacket — Notify the room owner that someone is at the door
type RoomDoorbellRingingOutPacket struct {
	Username string
}

func (p *RoomDoorbellRingingOutPacket) HeaderID() uint16 { return HeaderRoomDoorbellOut }

func (p *RoomDoorbellRingingOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Username)
	return nil
}

func DecodeRoomDoorbellRingingOut(r *codec.Reader) (*RoomDoorbellRingingOutPacket, error) {
	p := &RoomDoorbellRingingOutPacket{}
	var err error
	if p.Username, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomDoorbellAcceptedOut uint16 = 3783

// RoomDoorbellAcceptedOutPacket — Notify the visitor that doorbell access was granted
type RoomDoorbellAcceptedOutPacket struct {
	Username string
}

func (p *RoomDoorbellAcceptedOutPacket) HeaderID() uint16 { return HeaderRoomDoorbellAcceptedOut }

func (p *RoomDoorbellAcceptedOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Username)
	return nil
}

func DecodeRoomDoorbellAcceptedOut(r *codec.Reader) (*RoomDoorbellAcceptedOutPacket, error) {
	p := &RoomDoorbellAcceptedOutPacket{}
	var err error
	if p.Username, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomDoorbellRejectedOut uint16 = 878

// RoomDoorbellRejectedOutPacket — Notify the visitor that doorbell access was denied
type RoomDoorbellRejectedOutPacket struct {
	Username string
}

func (p *RoomDoorbellRejectedOutPacket) HeaderID() uint16 { return HeaderRoomDoorbellRejectedOut }

func (p *RoomDoorbellRejectedOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Username)
	return nil
}

func DecodeRoomDoorbellRejectedOut(r *codec.Reader) (*RoomDoorbellRejectedOutPacket, error) {
	p := &RoomDoorbellRejectedOutPacket{}
	var err error
	if p.Username, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomEnterOut uint16 = 758

// RoomEnteredOutPacket — Confirm successful room entry
type RoomEnteredOutPacket struct {
}

func (p *RoomEnteredOutPacket) HeaderID() uint16 { return HeaderRoomEnterOut }

func (p *RoomEnteredOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomEnteredOut(r *codec.Reader) (*RoomEnteredOutPacket, error) {
	p := &RoomEnteredOutPacket{}
	return p, nil
}

const HeaderRoomEnterErrorOut uint16 = 899

// RoomEntryErrorOutPacket — Indicate that room entry has failed
type RoomEntryErrorOutPacket struct {
	ErrorCode int32
}

func (p *RoomEntryErrorOutPacket) HeaderID() uint16 { return HeaderRoomEnterErrorOut }

func (p *RoomEntryErrorOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ErrorCode)
	return nil
}

func DecodeRoomEntryErrorOut(r *codec.Reader) (*RoomEntryErrorOutPacket, error) {
	p := &RoomEntryErrorOutPacket{}
	var err error
	if p.ErrorCode, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomForwardOut uint16 = 160

// RoomForwardOutPacket — Forward the client to a different room
type RoomForwardOutPacket struct {
	RoomId int32
}

func (p *RoomForwardOutPacket) HeaderID() uint16 { return HeaderRoomForwardOut }

func (p *RoomForwardOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomForwardOut(r *codec.Reader) (*RoomForwardOutPacket, error) {
	p := &RoomForwardOutPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomHeightMapOut uint16 = 2753

// RoomHeightMapOutPacket — Deliver the full room tile heightmap
type RoomHeightMapOutPacket struct {
	Width int32
	Height int32
	Tiles []int32
}

func (p *RoomHeightMapOutPacket) HeaderID() uint16 { return HeaderRoomHeightMapOut }

func (p *RoomHeightMapOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Width)
	w.WriteInt32(p.Height)
	w.WriteListInt32(p.Tiles)
	return nil
}

func DecodeRoomHeightMapOut(r *codec.Reader) (*RoomHeightMapOutPacket, error) {
	p := &RoomHeightMapOutPacket{}
	var err error
	if p.Width, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Height, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Tiles, err = r.ReadListInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomHeightMapUpdateOut uint16 = 558

// RoomHeightMapUpdateOutPacket — Update specific tiles in the room heightmap
type RoomHeightMapUpdateOutPacket struct {
	Count int32
	Updates []byte // TODO: hand-implement nested decode
}

func (p *RoomHeightMapUpdateOutPacket) HeaderID() uint16 { return HeaderRoomHeightMapUpdateOut }

func (p *RoomHeightMapUpdateOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Count)
	w.WriteBytes(p.Updates)
	return nil
}

func DecodeRoomHeightMapUpdateOut(r *codec.Reader) (*RoomHeightMapUpdateOutPacket, error) {
	p := &RoomHeightMapUpdateOutPacket{}
	var err error
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Updates, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomInfoOwnerOut uint16 = 749

// RoomOwnerInfoOutPacket — Provide the room owner's display information
type RoomOwnerInfoOutPacket struct {
	OwnerId int32
	OwnerName string
}

func (p *RoomOwnerInfoOutPacket) HeaderID() uint16 { return HeaderRoomInfoOwnerOut }

func (p *RoomOwnerInfoOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OwnerId)
	w.WriteString(p.OwnerName)
	return nil
}

func DecodeRoomOwnerInfoOut(r *codec.Reader) (*RoomOwnerInfoOutPacket, error) {
	p := &RoomOwnerInfoOutPacket{}
	var err error
	if p.OwnerId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.OwnerName, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomModelOut uint16 = 1301

// RoomModelOutPacket — Deliver the room layout model data
type RoomModelOutPacket struct {
	ModelName string
	RoomId int32
}

func (p *RoomModelOutPacket) HeaderID() uint16 { return HeaderRoomModelOut }

func (p *RoomModelOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.ModelName)
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomModelOut(r *codec.Reader) (*RoomModelOutPacket, error) {
	p := &RoomModelOutPacket{}
	var err error
	if p.ModelName, err = r.ReadString(); err != nil { return nil, err }
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomModelBlockedTilesOut uint16 = 3990

// RoomBlockedTilesOutPacket — Deliver the set of blocked tiles in the room
type RoomBlockedTilesOutPacket struct {
	Count int32
	Tiles []byte // TODO: hand-implement nested decode
}

func (p *RoomBlockedTilesOutPacket) HeaderID() uint16 { return HeaderRoomModelBlockedTilesOut }

func (p *RoomBlockedTilesOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Count)
	w.WriteBytes(p.Tiles)
	return nil
}

func DecodeRoomBlockedTilesOut(r *codec.Reader) (*RoomBlockedTilesOutPacket, error) {
	p := &RoomBlockedTilesOutPacket{}
	var err error
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Tiles, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomModelDoorOut uint16 = 1664

// RoomDoorSettingsOutPacket — Deliver the room entry door position and direction
type RoomDoorSettingsOutPacket struct {
	X int32
	Y int32
	Z string
	Direction int32
}

func (p *RoomDoorSettingsOutPacket) HeaderID() uint16 { return HeaderRoomModelDoorOut }

func (p *RoomDoorSettingsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.X)
	w.WriteInt32(p.Y)
	w.WriteString(p.Z)
	w.WriteInt32(p.Direction)
	return nil
}

func DecodeRoomDoorSettingsOut(r *codec.Reader) (*RoomDoorSettingsOutPacket, error) {
	p := &RoomDoorSettingsOutPacket{}
	var err error
	if p.X, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Y, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Z, err = r.ReadString(); err != nil { return nil, err }
	if p.Direction, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomModelNameOut uint16 = 2031

// RoomModelNameOutPacket — Deliver the room model identifier
type RoomModelNameOutPacket struct {
	ModelName string
	RoomId int32
}

func (p *RoomModelNameOutPacket) HeaderID() uint16 { return HeaderRoomModelNameOut }

func (p *RoomModelNameOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.ModelName)
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomModelNameOut(r *codec.Reader) (*RoomModelNameOutPacket, error) {
	p := &RoomModelNameOutPacket{}
	var err error
	if p.ModelName, err = r.ReadString(); err != nil { return nil, err }
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomMutedOut uint16 = 2533

// RoomMutedOutPacket — Notify that room-wide mute state has changed
type RoomMutedOutPacket struct {
	AllMuted bool
}

func (p *RoomMutedOutPacket) HeaderID() uint16 { return HeaderRoomMutedOut }

func (p *RoomMutedOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.AllMuted)
	return nil
}

func DecodeRoomMutedOut(r *codec.Reader) (*RoomMutedOutPacket, error) {
	p := &RoomMutedOutPacket{}
	var err error
	if p.AllMuted, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomMuteUserOut uint16 = 826

// RoomUserMutedOutPacket — Notify a user that they have been muted
type RoomUserMutedOutPacket struct {
	MuteTimeSeconds int32
}

func (p *RoomUserMutedOutPacket) HeaderID() uint16 { return HeaderRoomMuteUserOut }

func (p *RoomUserMutedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.MuteTimeSeconds)
	return nil
}

func DecodeRoomUserMutedOut(r *codec.Reader) (*RoomUserMutedOutPacket, error) {
	p := &RoomUserMutedOutPacket{}
	var err error
	if p.MuteTimeSeconds, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomPaintOut uint16 = 2454

// RoomPaintOutPacket — Deliver the room decoration settings
type RoomPaintOutPacket struct {
	Type string
	Value string
}

func (p *RoomPaintOutPacket) HeaderID() uint16 { return HeaderRoomPaintOut }

func (p *RoomPaintOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Type)
	w.WriteString(p.Value)
	return nil
}

func DecodeRoomPaintOut(r *codec.Reader) (*RoomPaintOutPacket, error) {
	p := &RoomPaintOutPacket{}
	var err error
	if p.Type, err = r.ReadString(); err != nil { return nil, err }
	if p.Value, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomPromotionOut uint16 = 2274

// RoomEventOutPacket — Deliver room event or promotion data
type RoomEventOutPacket struct {
	EventId int32
	EventName string
	EventDescription string
	MinutesLeft int32
}

func (p *RoomEventOutPacket) HeaderID() uint16 { return HeaderRoomPromotionOut }

func (p *RoomEventOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.EventId)
	w.WriteString(p.EventName)
	w.WriteString(p.EventDescription)
	w.WriteInt32(p.MinutesLeft)
	return nil
}

func DecodeRoomEventOut(r *codec.Reader) (*RoomEventOutPacket, error) {
	p := &RoomEventOutPacket{}
	var err error
	if p.EventId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.EventName, err = r.ReadString(); err != nil { return nil, err }
	if p.EventDescription, err = r.ReadString(); err != nil { return nil, err }
	if p.MinutesLeft, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomQueueStatusOut uint16 = 2208

// RoomQueueStatusOutPacket — Deliver the doorbell queue status
type RoomQueueStatusOutPacket struct {
	QueueId int32
	Position int32
}

func (p *RoomQueueStatusOutPacket) HeaderID() uint16 { return HeaderRoomQueueStatusOut }

func (p *RoomQueueStatusOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.QueueId)
	w.WriteInt32(p.Position)
	return nil
}

func DecodeRoomQueueStatusOut(r *codec.Reader) (*RoomQueueStatusOutPacket, error) {
	p := &RoomQueueStatusOutPacket{}
	var err error
	if p.QueueId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Position, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomRightsOut uint16 = 780

// RoomRightsOutPacket — Deliver the user's rights level in the room
type RoomRightsOutPacket struct {
	RightsLevel int32
}

func (p *RoomRightsOutPacket) HeaderID() uint16 { return HeaderRoomRightsOut }

func (p *RoomRightsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RightsLevel)
	return nil
}

func DecodeRoomRightsOut(r *codec.Reader) (*RoomRightsOutPacket, error) {
	p := &RoomRightsOutPacket{}
	var err error
	if p.RightsLevel, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomRightsClearOut uint16 = 2392

// RoomRightsClearedOutPacket — Notify that all room rights have been cleared
type RoomRightsClearedOutPacket struct {
}

func (p *RoomRightsClearedOutPacket) HeaderID() uint16 { return HeaderRoomRightsClearOut }

func (p *RoomRightsClearedOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomRightsClearedOut(r *codec.Reader) (*RoomRightsClearedOutPacket, error) {
	p := &RoomRightsClearedOutPacket{}
	return p, nil
}

const HeaderRoomRightsListOut uint16 = 1284

// RoomRightsListOutPacket — Deliver the full list of users with room rights
type RoomRightsListOutPacket struct {
	RoomId int32
	Users []byte // TODO: hand-implement nested decode
}

func (p *RoomRightsListOutPacket) HeaderID() uint16 { return HeaderRoomRightsListOut }

func (p *RoomRightsListOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	w.WriteBytes(p.Users)
	return nil
}

func DecodeRoomRightsListOut(r *codec.Reader) (*RoomRightsListOutPacket, error) {
	p := &RoomRightsListOutPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Users, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomRightsListAddOut uint16 = 2088

// RoomRightsListAddOutPacket — Notify that a user was added to the rights list
type RoomRightsListAddOutPacket struct {
	RoomId int32
	UserId int32
	Username string
}

func (p *RoomRightsListAddOutPacket) HeaderID() uint16 { return HeaderRoomRightsListAddOut }

func (p *RoomRightsListAddOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	w.WriteInt32(p.UserId)
	w.WriteString(p.Username)
	return nil
}

func DecodeRoomRightsListAddOut(r *codec.Reader) (*RoomRightsListAddOutPacket, error) {
	p := &RoomRightsListAddOutPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Username, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomRightsListRemoveOut uint16 = 1327

// RoomRightsListRemoveOutPacket — Notify that a user was removed from the rights list
type RoomRightsListRemoveOutPacket struct {
	RoomId int32
	UserId int32
}

func (p *RoomRightsListRemoveOutPacket) HeaderID() uint16 { return HeaderRoomRightsListRemoveOut }

func (p *RoomRightsListRemoveOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeRoomRightsListRemoveOut(r *codec.Reader) (*RoomRightsListRemoveOutPacket, error) {
	p := &RoomRightsListRemoveOutPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomRightsOwnerOut uint16 = 339

// RoomRightsOwnerOutPacket — Notify the user that they have room owner rights
type RoomRightsOwnerOutPacket struct {
	RoomId int32
}

func (p *RoomRightsOwnerOutPacket) HeaderID() uint16 { return HeaderRoomRightsOwnerOut }

func (p *RoomRightsOwnerOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomRightsOwnerOut(r *codec.Reader) (*RoomRightsOwnerOutPacket, error) {
	p := &RoomRightsOwnerOutPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomScoreOut uint16 = 482

// RoomScoreOutPacket — Deliver the room's current score
type RoomScoreOutPacket struct {
	Score int32
}

func (p *RoomScoreOutPacket) HeaderID() uint16 { return HeaderRoomScoreOut }

func (p *RoomScoreOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Score)
	return nil
}

func DecodeRoomScoreOut(r *codec.Reader) (*RoomScoreOutPacket, error) {
	p := &RoomScoreOutPacket{}
	var err error
	if p.Score, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomSettingsOut uint16 = 1498

// RoomSettingsOutPacket — Deliver the full room settings record
type RoomSettingsOutPacket struct {
	RoomId int32
	RoomName string
	RoomDescription string
	DoorMode int32
	UserLimit int32
	CategoryId int32
	Tags []string
	TradeMode int32
	AllowPets bool
	AllowPetsEat bool
	AllowWalkthrough bool
	HideWalls bool
	WallThickness int32
	FloorThickness int32
	MuteState int32
	KickState int32
	BanState int32
	ChatSettings []byte // TODO: hand-implement nested decode
}

func (p *RoomSettingsOutPacket) HeaderID() uint16 { return HeaderRoomSettingsOut }

func (p *RoomSettingsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	w.WriteString(p.RoomName)
	w.WriteString(p.RoomDescription)
	w.WriteInt32(p.DoorMode)
	w.WriteInt32(p.UserLimit)
	w.WriteInt32(p.CategoryId)
	w.WriteListString(p.Tags)
	w.WriteInt32(p.TradeMode)
	w.WriteBool(p.AllowPets)
	w.WriteBool(p.AllowPetsEat)
	w.WriteBool(p.AllowWalkthrough)
	w.WriteBool(p.HideWalls)
	w.WriteInt32(p.WallThickness)
	w.WriteInt32(p.FloorThickness)
	w.WriteInt32(p.MuteState)
	w.WriteInt32(p.KickState)
	w.WriteInt32(p.BanState)
	w.WriteBytes(p.ChatSettings)
	return nil
}

func DecodeRoomSettingsOut(r *codec.Reader) (*RoomSettingsOutPacket, error) {
	p := &RoomSettingsOutPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RoomName, err = r.ReadString(); err != nil { return nil, err }
	if p.RoomDescription, err = r.ReadString(); err != nil { return nil, err }
	if p.DoorMode, err = r.ReadInt32(); err != nil { return nil, err }
	if p.UserLimit, err = r.ReadInt32(); err != nil { return nil, err }
	if p.CategoryId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Tags, err = r.ReadListString(); err != nil { return nil, err }
	if p.TradeMode, err = r.ReadInt32(); err != nil { return nil, err }
	if p.AllowPets, err = r.ReadBool(); err != nil { return nil, err }
	if p.AllowPetsEat, err = r.ReadBool(); err != nil { return nil, err }
	if p.AllowWalkthrough, err = r.ReadBool(); err != nil { return nil, err }
	if p.HideWalls, err = r.ReadBool(); err != nil { return nil, err }
	if p.WallThickness, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FloorThickness, err = r.ReadInt32(); err != nil { return nil, err }
	if p.MuteState, err = r.ReadInt32(); err != nil { return nil, err }
	if p.KickState, err = r.ReadInt32(); err != nil { return nil, err }
	if p.BanState, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ChatSettings, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomSettingsChatOut uint16 = 1191

// RoomChatSettingsOutPacket — Deliver the room chat configuration
type RoomChatSettingsOutPacket struct {
	BubbleMode int32
	BubbleWeight int32
	BubbleSpeed int32
	ChatDistance int32
	FloodProtection int32
}

func (p *RoomChatSettingsOutPacket) HeaderID() uint16 { return HeaderRoomSettingsChatOut }

func (p *RoomChatSettingsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.BubbleMode)
	w.WriteInt32(p.BubbleWeight)
	w.WriteInt32(p.BubbleSpeed)
	w.WriteInt32(p.ChatDistance)
	w.WriteInt32(p.FloodProtection)
	return nil
}

func DecodeRoomChatSettingsOut(r *codec.Reader) (*RoomChatSettingsOutPacket, error) {
	p := &RoomChatSettingsOutPacket{}
	var err error
	if p.BubbleMode, err = r.ReadInt32(); err != nil { return nil, err }
	if p.BubbleWeight, err = r.ReadInt32(); err != nil { return nil, err }
	if p.BubbleSpeed, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ChatDistance, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FloodProtection, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomSettingsSaveOut uint16 = 948

// RoomSettingsSavedOutPacket — Confirm that room settings were saved successfully
type RoomSettingsSavedOutPacket struct {
	RoomId int32
}

func (p *RoomSettingsSavedOutPacket) HeaderID() uint16 { return HeaderRoomSettingsSaveOut }

func (p *RoomSettingsSavedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomSettingsSavedOut(r *codec.Reader) (*RoomSettingsSavedOutPacket, error) {
	p := &RoomSettingsSavedOutPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomSettingsSaveErrorOut uint16 = 1555

// RoomSettingsSaveErrorOutPacket — Indicate that room settings could not be saved
type RoomSettingsSaveErrorOutPacket struct {
	ErrorCode int32
}

func (p *RoomSettingsSaveErrorOutPacket) HeaderID() uint16 { return HeaderRoomSettingsSaveErrorOut }

func (p *RoomSettingsSaveErrorOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ErrorCode)
	return nil
}

func DecodeRoomSettingsSaveErrorOut(r *codec.Reader) (*RoomSettingsSaveErrorOutPacket, error) {
	p := &RoomSettingsSaveErrorOutPacket{}
	var err error
	if p.ErrorCode, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomInfoUpdatedOut uint16 = 3297

// RoomInfoUpdatedOutPacket — Notify that room metadata has been updated
type RoomInfoUpdatedOutPacket struct {
	RoomId int32
}

func (p *RoomInfoUpdatedOutPacket) HeaderID() uint16 { return HeaderRoomInfoUpdatedOut }

func (p *RoomInfoUpdatedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeRoomInfoUpdatedOut(r *codec.Reader) (*RoomInfoUpdatedOutPacket, error) {
	p := &RoomInfoUpdatedOutPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomSpectatorOut uint16 = 1033

// RoomSpectatorModeOutPacket — Indicate the user is in spectator mode
type RoomSpectatorModeOutPacket struct {
}

func (p *RoomSpectatorModeOutPacket) HeaderID() uint16 { return HeaderRoomSpectatorOut }

func (p *RoomSpectatorModeOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomSpectatorModeOut(r *codec.Reader) (*RoomSpectatorModeOutPacket, error) {
	p := &RoomSpectatorModeOutPacket{}
	return p, nil
}

const HeaderRoomThicknessOut uint16 = 3547

// RoomVisualizationSettingsOutPacket — Deliver room visualization settings
type RoomVisualizationSettingsOutPacket struct {
	HideWalls bool
	WallThickness int32
	FloorThickness int32
}

func (p *RoomVisualizationSettingsOutPacket) HeaderID() uint16 { return HeaderRoomThicknessOut }

func (p *RoomVisualizationSettingsOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.HideWalls)
	w.WriteInt32(p.WallThickness)
	w.WriteInt32(p.FloorThickness)
	return nil
}

func DecodeRoomVisualizationSettingsOut(r *codec.Reader) (*RoomVisualizationSettingsOutPacket, error) {
	p := &RoomVisualizationSettingsOutPacket{}
	var err error
	if p.HideWalls, err = r.ReadBool(); err != nil { return nil, err }
	if p.WallThickness, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FloorThickness, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomEventOut uint16 = 1840

// RoomEventInfoOutPacket — Deliver room event or advertisement information
type RoomEventInfoOutPacket struct {
	FlatId int32
	Name string
	Description string
	CategoryId int32
	MinutesLeft int32
	Tags []string
}

func (p *RoomEventInfoOutPacket) HeaderID() uint16 { return HeaderRoomEventOut }

func (p *RoomEventInfoOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.FlatId)
	w.WriteString(p.Name)
	w.WriteString(p.Description)
	w.WriteInt32(p.CategoryId)
	w.WriteInt32(p.MinutesLeft)
	w.WriteListString(p.Tags)
	return nil
}

func DecodeRoomEventInfoOut(r *codec.Reader) (*RoomEventInfoOutPacket, error) {
	p := &RoomEventInfoOutPacket{}
	var err error
	if p.FlatId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Name, err = r.ReadString(); err != nil { return nil, err }
	if p.Description, err = r.ReadString(); err != nil { return nil, err }
	if p.CategoryId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.MinutesLeft, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Tags, err = r.ReadListString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomEventCancelOut uint16 = 3479

// RoomEventCancelledOutPacket — Notify that the active room event was cancelled
type RoomEventCancelledOutPacket struct {
}

func (p *RoomEventCancelledOutPacket) HeaderID() uint16 { return HeaderRoomEventCancelOut }

func (p *RoomEventCancelledOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomEventCancelledOut(r *codec.Reader) (*RoomEventCancelledOutPacket, error) {
	p := &RoomEventCancelledOutPacket{}
	return p, nil
}

const HeaderRoomGetFilterWordsOut uint16 = 2937

// RoomFilterWordsOutPacket — Deliver the room custom filter word list
type RoomFilterWordsOutPacket struct {
	Words []string
}

func (p *RoomFilterWordsOutPacket) HeaderID() uint16 { return HeaderRoomGetFilterWordsOut }

func (p *RoomFilterWordsOutPacket) Encode(w *codec.Writer) error {
	w.WriteListString(p.Words)
	return nil
}

func DecodeRoomFilterWordsOut(r *codec.Reader) (*RoomFilterWordsOutPacket, error) {
	p := &RoomFilterWordsOutPacket{}
	var err error
	if p.Words, err = r.ReadListString(); err != nil { return nil, err }
	return p, nil
}

const HeaderFloodControlOut uint16 = 566

// RoomFloodControlOutPacket — Flood control
type RoomFloodControlOutPacket struct {
	Field1 int32
}

func (p *RoomFloodControlOutPacket) HeaderID() uint16 { return HeaderFloodControlOut }

func (p *RoomFloodControlOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	return nil
}

func DecodeRoomFloodControlOut(r *codec.Reader) (*RoomFloodControlOutPacket, error) {
	p := &RoomFloodControlOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomAdErrorOut uint16 = 1759

// RoomRoomAdErrorOutPacket — Room ad error
type RoomRoomAdErrorOutPacket struct {
	Field1 int32
	Field2 string
}

func (p *RoomRoomAdErrorOutPacket) HeaderID() uint16 { return HeaderRoomAdErrorOut }

func (p *RoomRoomAdErrorOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteString(p.Field2)
	return nil
}

func DecodeRoomRoomAdErrorOut(r *codec.Reader) (*RoomRoomAdErrorOutPacket, error) {
	p := &RoomRoomAdErrorOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomPopularTagsResultOut uint16 = 2012

// RoomRoomPopularTagsResultOutPacket — Room popular tags result
type RoomRoomPopularTagsResultOutPacket struct {
}

func (p *RoomRoomPopularTagsResultOutPacket) HeaderID() uint16 { return HeaderRoomPopularTagsResultOut }

func (p *RoomRoomPopularTagsResultOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeRoomRoomPopularTagsResultOut(r *codec.Reader) (*RoomRoomPopularTagsResultOutPacket, error) {
	p := &RoomRoomPopularTagsResultOutPacket{}
	return p, nil
}

const HeaderRoomAdPurchaseOut uint16 = 2468

// RoomRoomAdPurchaseOutPacket — Room ad purchase
type RoomRoomAdPurchaseOutPacket struct {
	Field1 bool
	Field2 int32
	Field3 int32
	Field4 string
	Field5 bool
}

func (p *RoomRoomAdPurchaseOutPacket) HeaderID() uint16 { return HeaderRoomAdPurchaseOut }

func (p *RoomRoomAdPurchaseOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteInt32(p.Field3)
	w.WriteString(p.Field4)
	w.WriteBool(p.Field5)
	return nil
}

func DecodeRoomRoomAdPurchaseOut(r *codec.Reader) (*RoomRoomAdPurchaseOutPacket, error) {
	p := &RoomRoomAdPurchaseOutPacket{}
	var err error
	if p.Field1, err = r.ReadBool(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field4, err = r.ReadString(); err != nil { return nil, err }
	if p.Field5, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderCanCreateRoomEventOut uint16 = 2599

// RoomCanCreateRoomEventOutPacket — Can create room event
type RoomCanCreateRoomEventOutPacket struct {
	Field1 bool
	Field2 int32
}

func (p *RoomCanCreateRoomEventOutPacket) HeaderID() uint16 { return HeaderCanCreateRoomEventOut }

func (p *RoomCanCreateRoomEventOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeRoomCanCreateRoomEventOut(r *codec.Reader) (*RoomCanCreateRoomEventOutPacket, error) {
	p := &RoomCanCreateRoomEventOutPacket{}
	var err error
	if p.Field1, err = r.ReadBool(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRoomSettingsErrorOut uint16 = 2897

// RoomRoomSettingsErrorOutPacket — Room settings error
type RoomRoomSettingsErrorOutPacket struct {
	Field1 int32
	Field2 int32
}

func (p *RoomRoomSettingsErrorOutPacket) HeaderID() uint16 { return HeaderRoomSettingsErrorOut }

func (p *RoomRoomSettingsErrorOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	w.WriteInt32(p.Field2)
	return nil
}

func DecodeRoomRoomSettingsErrorOut(r *codec.Reader) (*RoomRoomSettingsErrorOutPacket, error) {
	p := &RoomRoomSettingsErrorOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderShowEnforceRoomCategoryOut uint16 = 3896

// RoomShowEnforceRoomCategoryOutPacket — Show enforce room category
type RoomShowEnforceRoomCategoryOutPacket struct {
	Field1 int32
}

func (p *RoomShowEnforceRoomCategoryOutPacket) HeaderID() uint16 { return HeaderShowEnforceRoomCategoryOut }

func (p *RoomShowEnforceRoomCategoryOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	return nil
}

func DecodeRoomShowEnforceRoomCategoryOut(r *codec.Reader) (*RoomShowEnforceRoomCategoryOutPacket, error) {
	p := &RoomShowEnforceRoomCategoryOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

