// Code generated by tools/protogen. DO NOT EDIT.
package protocol

import "pixelsv/pkg/codec"

const HeaderSessionDesktopViewPacket uint16 = 105

type SessionDesktopViewPacket struct {
}

func (p *SessionDesktopViewPacket) HeaderID() uint16 { return HeaderSessionDesktopViewPacket }

func (p *SessionDesktopViewPacket) PacketName() string { return "session.desktop_view" }

func (p *SessionDesktopViewPacket) Realm() string { return "session-connection" }

func (p *SessionDesktopViewPacket) Encode(writer *codec.Writer) error {
	return nil
}

func decodeSessionDesktopViewPacket(reader *codec.Reader) (Packet, error) {
	packet := &SessionDesktopViewPacket{}
	return packet, nil
}

func init() {
	registerC2S(Definition{ID: HeaderSessionDesktopViewPacket, Name: "session.desktop_view", Realm: "session-connection", Summary: "Desktop view", Decode: decodeSessionDesktopViewPacket})
}

const HeaderClientLatencyTestPacket uint16 = 295

type ClientLatencyTestPacket struct {
	RequestId int32
}

func (p *ClientLatencyTestPacket) HeaderID() uint16 { return HeaderClientLatencyTestPacket }

func (p *ClientLatencyTestPacket) PacketName() string { return "client.latency_test" }

func (p *ClientLatencyTestPacket) Realm() string { return "session-connection" }

func (p *ClientLatencyTestPacket) Encode(writer *codec.Writer) error {
	writer.WriteInt32(p.RequestId)
	return nil
}

func decodeClientLatencyTestPacket(reader *codec.Reader) (Packet, error) {
	packet := &ClientLatencyTestPacket{}
	var err error
	packet.RequestId, err = reader.ReadInt32()
	if err != nil {
		return nil, err
	}
	return packet, nil
}

func init() {
	registerC2S(Definition{ID: HeaderClientLatencyTestPacket, Name: "client.latency_test", Realm: "session-connection", Summary: "Send latency probe id to measure round-trip time", Decode: decodeClientLatencyTestPacket})
}

const HeaderSessionPeerUsersClassificationPacket uint16 = 1160

type SessionPeerUsersClassificationPacket struct {
}

func (p *SessionPeerUsersClassificationPacket) HeaderID() uint16 {
	return HeaderSessionPeerUsersClassificationPacket
}

func (p *SessionPeerUsersClassificationPacket) PacketName() string {
	return "session.peer_users_classification"
}

func (p *SessionPeerUsersClassificationPacket) Realm() string { return "session-connection" }

func (p *SessionPeerUsersClassificationPacket) Encode(writer *codec.Writer) error {
	return nil
}

func decodeSessionPeerUsersClassificationPacket(reader *codec.Reader) (Packet, error) {
	packet := &SessionPeerUsersClassificationPacket{}
	return packet, nil
}

func init() {
	registerC2S(Definition{ID: HeaderSessionPeerUsersClassificationPacket, Name: "session.peer_users_classification", Realm: "session-connection", Summary: "Peer users classification", Decode: decodeSessionPeerUsersClassificationPacket})
}

const HeaderSessionClientToolbarTogglePacket uint16 = 2313

type SessionClientToolbarTogglePacket struct {
}

func (p *SessionClientToolbarTogglePacket) HeaderID() uint16 {
	return HeaderSessionClientToolbarTogglePacket
}

func (p *SessionClientToolbarTogglePacket) PacketName() string {
	return "session.client_toolbar_toggle"
}

func (p *SessionClientToolbarTogglePacket) Realm() string { return "session-connection" }

func (p *SessionClientToolbarTogglePacket) Encode(writer *codec.Writer) error {
	return nil
}

func decodeSessionClientToolbarTogglePacket(reader *codec.Reader) (Packet, error) {
	packet := &SessionClientToolbarTogglePacket{}
	return packet, nil
}

func init() {
	registerC2S(Definition{ID: HeaderSessionClientToolbarTogglePacket, Name: "session.client_toolbar_toggle", Realm: "session-connection", Summary: "Client toolbar toggle", Decode: decodeSessionClientToolbarTogglePacket})
}

const HeaderClientDisconnectPacket uint16 = 2445

type ClientDisconnectPacket struct {
}

func (p *ClientDisconnectPacket) HeaderID() uint16 { return HeaderClientDisconnectPacket }

func (p *ClientDisconnectPacket) PacketName() string { return "client.disconnect" }

func (p *ClientDisconnectPacket) Realm() string { return "session-connection" }

func (p *ClientDisconnectPacket) Encode(writer *codec.Writer) error {
	return nil
}

func decodeClientDisconnectPacket(reader *codec.Reader) (Packet, error) {
	packet := &ClientDisconnectPacket{}
	return packet, nil
}

func init() {
	registerC2S(Definition{ID: HeaderClientDisconnectPacket, Name: "client.disconnect", Realm: "session-connection", Summary: "Client-initiated graceful disconnect", Decode: decodeClientDisconnectPacket})
}

const HeaderClientPongPacket uint16 = 2596

type ClientPongPacket struct {
}

func (p *ClientPongPacket) HeaderID() uint16 { return HeaderClientPongPacket }

func (p *ClientPongPacket) PacketName() string { return "client.pong" }

func (p *ClientPongPacket) Realm() string { return "session-connection" }

func (p *ClientPongPacket) Encode(writer *codec.Writer) error {
	return nil
}

func decodeClientPongPacket(reader *codec.Reader) (Packet, error) {
	packet := &ClientPongPacket{}
	return packet, nil
}

func init() {
	registerC2S(Definition{ID: HeaderClientPongPacket, Name: "client.pong", Realm: "session-connection", Summary: "Keepalive response to server ping", Decode: decodeClientPongPacket})
}

const HeaderSessionRenderRoomPacket uint16 = 3226

type SessionRenderRoomPacket struct {
}

func (p *SessionRenderRoomPacket) HeaderID() uint16 { return HeaderSessionRenderRoomPacket }

func (p *SessionRenderRoomPacket) PacketName() string { return "session.render_room" }

func (p *SessionRenderRoomPacket) Realm() string { return "session-connection" }

func (p *SessionRenderRoomPacket) Encode(writer *codec.Writer) error {
	return nil
}

func decodeSessionRenderRoomPacket(reader *codec.Reader) (Packet, error) {
	packet := &SessionRenderRoomPacket{}
	return packet, nil
}

func init() {
	registerC2S(Definition{ID: HeaderSessionRenderRoomPacket, Name: "session.render_room", Realm: "session-connection", Summary: "Render room", Decode: decodeSessionRenderRoomPacket})
}

const HeaderSessionTrackingPerformanceLogPacket uint16 = 3230

type SessionTrackingPerformanceLogPacket struct {
}

func (p *SessionTrackingPerformanceLogPacket) HeaderID() uint16 {
	return HeaderSessionTrackingPerformanceLogPacket
}

func (p *SessionTrackingPerformanceLogPacket) PacketName() string {
	return "session.tracking_performance_log"
}

func (p *SessionTrackingPerformanceLogPacket) Realm() string { return "session-connection" }

func (p *SessionTrackingPerformanceLogPacket) Encode(writer *codec.Writer) error {
	return nil
}

func decodeSessionTrackingPerformanceLogPacket(reader *codec.Reader) (Packet, error) {
	packet := &SessionTrackingPerformanceLogPacket{}
	return packet, nil
}

func init() {
	registerC2S(Definition{ID: HeaderSessionTrackingPerformanceLogPacket, Name: "session.tracking_performance_log", Realm: "session-connection", Summary: "Tracking performance log", Decode: decodeSessionTrackingPerformanceLogPacket})
}

const HeaderSessionEventTrackerPacket uint16 = 3457

type SessionEventTrackerPacket struct {
}

func (p *SessionEventTrackerPacket) HeaderID() uint16 { return HeaderSessionEventTrackerPacket }

func (p *SessionEventTrackerPacket) PacketName() string { return "session.event_tracker" }

func (p *SessionEventTrackerPacket) Realm() string { return "session-connection" }

func (p *SessionEventTrackerPacket) Encode(writer *codec.Writer) error {
	return nil
}

func decodeSessionEventTrackerPacket(reader *codec.Reader) (Packet, error) {
	packet := &SessionEventTrackerPacket{}
	return packet, nil
}

func init() {
	registerC2S(Definition{ID: HeaderSessionEventTrackerPacket, Name: "session.event_tracker", Realm: "session-connection", Summary: "Event tracker", Decode: decodeSessionEventTrackerPacket})
}

const HeaderSessionTrackingLagWarningReportPacket uint16 = 3847

type SessionTrackingLagWarningReportPacket struct {
}

func (p *SessionTrackingLagWarningReportPacket) HeaderID() uint16 {
	return HeaderSessionTrackingLagWarningReportPacket
}

func (p *SessionTrackingLagWarningReportPacket) PacketName() string {
	return "session.tracking_lag_warning_report"
}

func (p *SessionTrackingLagWarningReportPacket) Realm() string { return "session-connection" }

func (p *SessionTrackingLagWarningReportPacket) Encode(writer *codec.Writer) error {
	return nil
}

func decodeSessionTrackingLagWarningReportPacket(reader *codec.Reader) (Packet, error) {
	packet := &SessionTrackingLagWarningReportPacket{}
	return packet, nil
}

func init() {
	registerC2S(Definition{ID: HeaderSessionTrackingLagWarningReportPacket, Name: "session.tracking_lag_warning_report", Realm: "session-connection", Summary: "Tracking lag warning report", Decode: decodeSessionTrackingLagWarningReportPacket})
}
