// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderScrGetKickbackInfoIn uint16 = 869

// UserGetKickbackInfoInPacket — Request Habbo Club kickback (reward) information
type UserGetKickbackInfoInPacket struct {
}

func (p *UserGetKickbackInfoInPacket) HeaderID() uint16 { return HeaderScrGetKickbackInfoIn }

func (p *UserGetKickbackInfoInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserGetKickbackInfoIn(r *codec.Reader) (*UserGetKickbackInfoInPacket, error) {
	p := &UserGetKickbackInfoInPacket{}
	return p, nil
}

const HeaderUserSubscriptionIn uint16 = 3166

// UserGetSubscriptionInPacket — Request subscription status for a named product
type UserGetSubscriptionInPacket struct {
	Type string
}

func (p *UserGetSubscriptionInPacket) HeaderID() uint16 { return HeaderUserSubscriptionIn }

func (p *UserGetSubscriptionInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Type)
	return nil
}

func DecodeUserGetSubscriptionIn(r *codec.Reader) (*UserGetSubscriptionInPacket, error) {
	p := &UserGetSubscriptionInPacket{}
	var err error
	if p.Type, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetClubGiftInfoIn uint16 = 487

// CatalogGetClubGiftInfoInPacket — Request Habbo Club member gift information
type CatalogGetClubGiftInfoInPacket struct {
}

func (p *CatalogGetClubGiftInfoInPacket) HeaderID() uint16 { return HeaderGetClubGiftInfoIn }

func (p *CatalogGetClubGiftInfoInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeCatalogGetClubGiftInfoIn(r *codec.Reader) (*CatalogGetClubGiftInfoInPacket, error) {
	p := &CatalogGetClubGiftInfoInPacket{}
	return p, nil
}

const HeaderGetClubOffersIn uint16 = 3285

// CatalogGetClubOffersInPacket — Request available Habbo Club membership offers
type CatalogGetClubOffersInPacket struct {
	WindowId int32
}

func (p *CatalogGetClubOffersInPacket) HeaderID() uint16 { return HeaderGetClubOffersIn }

func (p *CatalogGetClubOffersInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.WindowId)
	return nil
}

func DecodeCatalogGetClubOffersIn(r *codec.Reader) (*CatalogGetClubOffersInPacket, error) {
	p := &CatalogGetClubOffersInPacket{}
	var err error
	if p.WindowId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetProductOfferIn uint16 = 2594

// CatalogGetProductOfferInPacket — Request details for a specific product offer
type CatalogGetProductOfferInPacket struct {
	OfferId int32
}

func (p *CatalogGetProductOfferInPacket) HeaderID() uint16 { return HeaderGetProductOfferIn }

func (p *CatalogGetProductOfferInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OfferId)
	return nil
}

func DecodeCatalogGetProductOfferIn(r *codec.Reader) (*CatalogGetProductOfferInPacket, error) {
	p := &CatalogGetProductOfferInPacket{}
	var err error
	if p.OfferId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetHabboClubExtendOfferIn uint16 = 2462

// CatalogGetHcExtendOfferInPacket — Request the Habbo Club extension offer
type CatalogGetHcExtendOfferInPacket struct {
}

func (p *CatalogGetHcExtendOfferInPacket) HeaderID() uint16 { return HeaderGetHabboClubExtendOfferIn }

func (p *CatalogGetHcExtendOfferInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeCatalogGetHcExtendOfferIn(r *codec.Reader) (*CatalogGetHcExtendOfferInPacket, error) {
	p := &CatalogGetHcExtendOfferInPacket{}
	return p, nil
}

const HeaderCatalogSelectVipGiftIn uint16 = 2276

// CatalogSelectClubGiftInPacket — Select a Club gift from the available rewards
type CatalogSelectClubGiftInPacket struct {
	GiftName string
}

func (p *CatalogSelectClubGiftInPacket) HeaderID() uint16 { return HeaderCatalogSelectVipGiftIn }

func (p *CatalogSelectClubGiftInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.GiftName)
	return nil
}

func DecodeCatalogSelectClubGiftIn(r *codec.Reader) (*CatalogSelectClubGiftInPacket, error) {
	p := &CatalogSelectClubGiftInPacket{}
	var err error
	if p.GiftName, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderBuildersClubQueryFurniCountIn uint16 = 2529

// CatalogBuildersClubQueryFurniCountInPacket — Request the current Builders Club furniture placement count
type CatalogBuildersClubQueryFurniCountInPacket struct {
}

func (p *CatalogBuildersClubQueryFurniCountInPacket) HeaderID() uint16 { return HeaderBuildersClubQueryFurniCountIn }

func (p *CatalogBuildersClubQueryFurniCountInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeCatalogBuildersClubQueryFurniCountIn(r *codec.Reader) (*CatalogBuildersClubQueryFurniCountInPacket, error) {
	p := &CatalogBuildersClubQueryFurniCountInPacket{}
	return p, nil
}

const HeaderGetLimitedOfferAppearingNextIn uint16 = 410

// CatalogGetLimitedOfferNextInPacket — Request the next limited offer appearance time
type CatalogGetLimitedOfferNextInPacket struct {
}

func (p *CatalogGetLimitedOfferNextInPacket) HeaderID() uint16 { return HeaderGetLimitedOfferAppearingNextIn }

func (p *CatalogGetLimitedOfferNextInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeCatalogGetLimitedOfferNextIn(r *codec.Reader) (*CatalogGetLimitedOfferNextInPacket, error) {
	p := &CatalogGetLimitedOfferNextInPacket{}
	return p, nil
}

const HeaderGetDirectClubBuyAvailableIn uint16 = 801

// CatalogGetDirectClubBuyInPacket — Check whether direct SMS Club purchase is available
type CatalogGetDirectClubBuyInPacket struct {
	DurationDays int32
}

func (p *CatalogGetDirectClubBuyInPacket) HeaderID() uint16 { return HeaderGetDirectClubBuyAvailableIn }

func (p *CatalogGetDirectClubBuyInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.DurationDays)
	return nil
}

func DecodeCatalogGetDirectClubBuyIn(r *codec.Reader) (*CatalogGetDirectClubBuyInPacket, error) {
	p := &CatalogGetDirectClubBuyInPacket{}
	var err error
	if p.DurationDays, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetHabboBasicMembershipExtendOfferIn uint16 = 603

// CatalogGetBasicExtendOfferInPacket — Request the basic membership extension offer
type CatalogGetBasicExtendOfferInPacket struct {
}

func (p *CatalogGetBasicExtendOfferInPacket) HeaderID() uint16 { return HeaderGetHabboBasicMembershipExtendOfferIn }

func (p *CatalogGetBasicExtendOfferInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeCatalogGetBasicExtendOfferIn(r *codec.Reader) (*CatalogGetBasicExtendOfferInPacket, error) {
	p := &CatalogGetBasicExtendOfferInPacket{}
	return p, nil
}

const HeaderPurchaseBasicMembershipExtensionIn uint16 = 2735

// CatalogPurchaseBasicExtensionInPacket — Purchase a basic Club membership extension
type CatalogPurchaseBasicExtensionInPacket struct {
}

func (p *CatalogPurchaseBasicExtensionInPacket) HeaderID() uint16 { return HeaderPurchaseBasicMembershipExtensionIn }

func (p *CatalogPurchaseBasicExtensionInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeCatalogPurchaseBasicExtensionIn(r *codec.Reader) (*CatalogPurchaseBasicExtensionInPacket, error) {
	p := &CatalogPurchaseBasicExtensionInPacket{}
	return p, nil
}

const HeaderPurchaseVipMembershipExtensionIn uint16 = 3407

// CatalogPurchaseVipExtensionInPacket — Purchase a VIP Club membership extension
type CatalogPurchaseVipExtensionInPacket struct {
}

func (p *CatalogPurchaseVipExtensionInPacket) HeaderID() uint16 { return HeaderPurchaseVipMembershipExtensionIn }

func (p *CatalogPurchaseVipExtensionInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeCatalogPurchaseVipExtensionIn(r *codec.Reader) (*CatalogPurchaseVipExtensionInPacket, error) {
	p := &CatalogPurchaseVipExtensionInPacket{}
	return p, nil
}

const HeaderGetCatalogPageExpirationIn uint16 = 742

// CatalogGetPageExpirationInPacket — Request expiration time for a specific catalog page
type CatalogGetPageExpirationInPacket struct {
}

func (p *CatalogGetPageExpirationInPacket) HeaderID() uint16 { return HeaderGetCatalogPageExpirationIn }

func (p *CatalogGetPageExpirationInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeCatalogGetPageExpirationIn(r *codec.Reader) (*CatalogGetPageExpirationInPacket, error) {
	p := &CatalogGetPageExpirationInPacket{}
	return p, nil
}

const HeaderGetCatalogPageWithEarliestExpIn uint16 = 3135

// CatalogGetEarliestExpiryInPacket — Request the earliest expiring catalog page timestamp
type CatalogGetEarliestExpiryInPacket struct {
}

func (p *CatalogGetEarliestExpiryInPacket) HeaderID() uint16 { return HeaderGetCatalogPageWithEarliestExpIn }

func (p *CatalogGetEarliestExpiryInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeCatalogGetEarliestExpiryIn(r *codec.Reader) (*CatalogGetEarliestExpiryInPacket, error) {
	p := &CatalogGetEarliestExpiryInPacket{}
	return p, nil
}

const HeaderPurchaseTargetedOfferIn uint16 = 1826

// OfferPurchaseTargetedInPacket — Purchase the currently displayed targeted offer
type OfferPurchaseTargetedInPacket struct {
	OfferId int32
	Quantity int32
}

func (p *OfferPurchaseTargetedInPacket) HeaderID() uint16 { return HeaderPurchaseTargetedOfferIn }

func (p *OfferPurchaseTargetedInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OfferId)
	w.WriteInt32(p.Quantity)
	return nil
}

func DecodeOfferPurchaseTargetedIn(r *codec.Reader) (*OfferPurchaseTargetedInPacket, error) {
	p := &OfferPurchaseTargetedInPacket{}
	var err error
	if p.OfferId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Quantity, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetNextTargetedOfferIn uint16 = 596

// OfferGetNextTargetedInPacket — Request the next available targeted offer
type OfferGetNextTargetedInPacket struct {
	OfferId int32
}

func (p *OfferGetNextTargetedInPacket) HeaderID() uint16 { return HeaderGetNextTargetedOfferIn }

func (p *OfferGetNextTargetedInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OfferId)
	return nil
}

func DecodeOfferGetNextTargetedIn(r *codec.Reader) (*OfferGetNextTargetedInPacket, error) {
	p := &OfferGetNextTargetedInPacket{}
	var err error
	if p.OfferId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetTargetedOfferIn uint16 = 2487

// OfferGetTargetedInPacket — Request the current targeted offer
type OfferGetTargetedInPacket struct {
}

func (p *OfferGetTargetedInPacket) HeaderID() uint16 { return HeaderGetTargetedOfferIn }

func (p *OfferGetTargetedInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeOfferGetTargetedIn(r *codec.Reader) (*OfferGetTargetedInPacket, error) {
	p := &OfferGetTargetedInPacket{}
	return p, nil
}

const HeaderSetTargettedOfferStateIn uint16 = 2041

// OfferSetTargetedStateInPacket — Update the state of a targeted offer for the current user
type OfferSetTargetedStateInPacket struct {
	OfferId int32
	State int32
}

func (p *OfferSetTargetedStateInPacket) HeaderID() uint16 { return HeaderSetTargettedOfferStateIn }

func (p *OfferSetTargetedStateInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OfferId)
	w.WriteInt32(p.State)
	return nil
}

func DecodeOfferSetTargetedStateIn(r *codec.Reader) (*OfferSetTargetedStateInPacket, error) {
	p := &OfferSetTargetedStateInPacket{}
	var err error
	if p.OfferId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.State, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderShopTargetedOfferViewedIn uint16 = 3483

// OfferTargetedViewedInPacket — Notify that a targeted offer was viewed in the shop
type OfferTargetedViewedInPacket struct {
	OfferId int32
	State int32
}

func (p *OfferTargetedViewedInPacket) HeaderID() uint16 { return HeaderShopTargetedOfferViewedIn }

func (p *OfferTargetedViewedInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OfferId)
	w.WriteInt32(p.State)
	return nil
}

func DecodeOfferTargetedViewedIn(r *codec.Reader) (*OfferTargetedViewedInPacket, error) {
	p := &OfferTargetedViewedInPacket{}
	var err error
	if p.OfferId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.State, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderOpenCampaignCalendarDoorIn uint16 = 2257

// CalendarOpenDoorInPacket — Open a campaign calendar door for the current day
type CalendarOpenDoorInPacket struct {
	CampaignName string
	DayNumber int32
}

func (p *CalendarOpenDoorInPacket) HeaderID() uint16 { return HeaderOpenCampaignCalendarDoorIn }

func (p *CalendarOpenDoorInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.CampaignName)
	w.WriteInt32(p.DayNumber)
	return nil
}

func DecodeCalendarOpenDoorIn(r *codec.Reader) (*CalendarOpenDoorInPacket, error) {
	p := &CalendarOpenDoorInPacket{}
	var err error
	if p.CampaignName, err = r.ReadString(); err != nil { return nil, err }
	if p.DayNumber, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderOpenCampaignCalendarDoorStaffIn uint16 = 3889

// CalendarOpenDoorStaffInPacket — Force-open a campaign calendar door as a staff member
type CalendarOpenDoorStaffInPacket struct {
	CampaignName string
	DayNumber int32
}

func (p *CalendarOpenDoorStaffInPacket) HeaderID() uint16 { return HeaderOpenCampaignCalendarDoorStaffIn }

func (p *CalendarOpenDoorStaffInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.CampaignName)
	w.WriteInt32(p.DayNumber)
	return nil
}

func DecodeCalendarOpenDoorStaffIn(r *codec.Reader) (*CalendarOpenDoorStaffInPacket, error) {
	p := &CalendarOpenDoorStaffInPacket{}
	var err error
	if p.CampaignName, err = r.ReadString(); err != nil { return nil, err }
	if p.DayNumber, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetSeasonalCalendarDailyOfferIn uint16 = 3257

// CalendarGetSeasonalDailyOfferInPacket — Request the current seasonal calendar daily offer
type CalendarGetSeasonalDailyOfferInPacket struct {
}

func (p *CalendarGetSeasonalDailyOfferInPacket) HeaderID() uint16 { return HeaderGetSeasonalCalendarDailyOfferIn }

func (p *CalendarGetSeasonalDailyOfferInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeCalendarGetSeasonalDailyOfferIn(r *codec.Reader) (*CalendarGetSeasonalDailyOfferInPacket, error) {
	p := &CalendarGetSeasonalDailyOfferInPacket{}
	return p, nil
}

const HeaderGetSecondsUntilIn uint16 = 271

// SubscriptionSecondsUntilInPacket — Get seconds until
type SubscriptionSecondsUntilInPacket struct {
}

func (p *SubscriptionSecondsUntilInPacket) HeaderID() uint16 { return HeaderGetSecondsUntilIn }

func (p *SubscriptionSecondsUntilInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSubscriptionSecondsUntilIn(r *codec.Reader) (*SubscriptionSecondsUntilInPacket, error) {
	p := &SubscriptionSecondsUntilInPacket{}
	return p, nil
}

const HeaderGetBonusRareInfoIn uint16 = 957

// SubscriptionBonusRareInfoInPacket — Get bonus rare info
type SubscriptionBonusRareInfoInPacket struct {
}

func (p *SubscriptionBonusRareInfoInPacket) HeaderID() uint16 { return HeaderGetBonusRareInfoIn }

func (p *SubscriptionBonusRareInfoInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSubscriptionBonusRareInfoIn(r *codec.Reader) (*SubscriptionBonusRareInfoInPacket, error) {
	p := &SubscriptionBonusRareInfoInPacket{}
	return p, nil
}

const HeaderStartCampaignIn uint16 = 1697

// SubscriptionStartCampaignInPacket — Start campaign
type SubscriptionStartCampaignInPacket struct {
}

func (p *SubscriptionStartCampaignInPacket) HeaderID() uint16 { return HeaderStartCampaignIn }

func (p *SubscriptionStartCampaignInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSubscriptionStartCampaignIn(r *codec.Reader) (*SubscriptionStartCampaignInPacket, error) {
	p := &SubscriptionStartCampaignInPacket{}
	return p, nil
}

const HeaderUserSubscriptionOut uint16 = 954

// UserSubscriptionOutPacket — Deliver Pixels Club subscription state
type UserSubscriptionOutPacket struct {
	ProductName string
	DaysToPeriodEnd int32
	MemberPeriods int32
	PeriodsSubscribedAhead int32
	ResponseType int32
	HasEverBeenMember bool
	IsVip bool
	PastClubDays int32
	PastVipDays int32
	MinutesUntilExpiration int32
	MinutesSinceLastModified int32
}

func (p *UserSubscriptionOutPacket) HeaderID() uint16 { return HeaderUserSubscriptionOut }

func (p *UserSubscriptionOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.ProductName)
	w.WriteInt32(p.DaysToPeriodEnd)
	w.WriteInt32(p.MemberPeriods)
	w.WriteInt32(p.PeriodsSubscribedAhead)
	w.WriteInt32(p.ResponseType)
	w.WriteBool(p.HasEverBeenMember)
	w.WriteBool(p.IsVip)
	w.WriteInt32(p.PastClubDays)
	w.WriteInt32(p.PastVipDays)
	w.WriteInt32(p.MinutesUntilExpiration)
	w.WriteInt32(p.MinutesSinceLastModified)
	return nil
}

func DecodeUserSubscriptionOut(r *codec.Reader) (*UserSubscriptionOutPacket, error) {
	p := &UserSubscriptionOutPacket{}
	var err error
	if p.ProductName, err = r.ReadString(); err != nil { return nil, err }
	if p.DaysToPeriodEnd, err = r.ReadInt32(); err != nil { return nil, err }
	if p.MemberPeriods, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PeriodsSubscribedAhead, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ResponseType, err = r.ReadInt32(); err != nil { return nil, err }
	if p.HasEverBeenMember, err = r.ReadBool(); err != nil { return nil, err }
	if p.IsVip, err = r.ReadBool(); err != nil { return nil, err }
	if p.PastClubDays, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PastVipDays, err = r.ReadInt32(); err != nil { return nil, err }
	if p.MinutesUntilExpiration, err = r.ReadInt32(); err != nil { return nil, err }
	if p.MinutesSinceLastModified, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderScrSendKickbackInfoOut uint16 = 3277

// UserKickbackInfoOutPacket — Deliver Habbo Club credit kickback and streak information
type UserKickbackInfoOutPacket struct {
	CurrentHcStreak int32
	FirstSubscriptionDate string
	KickbackPercentage float64
	TotalCreditsMissed int32
	TotalCreditsRewarded int32
	TotalCreditsSpent int32
	CreditRewardForStreakBonus int32
	CreditRewardForMonthlySpent int32
	TimeUntilPayday int32
}

func (p *UserKickbackInfoOutPacket) HeaderID() uint16 { return HeaderScrSendKickbackInfoOut }

func (p *UserKickbackInfoOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.CurrentHcStreak)
	w.WriteString(p.FirstSubscriptionDate)
	w.WriteFloat64(p.KickbackPercentage)
	w.WriteInt32(p.TotalCreditsMissed)
	w.WriteInt32(p.TotalCreditsRewarded)
	w.WriteInt32(p.TotalCreditsSpent)
	w.WriteInt32(p.CreditRewardForStreakBonus)
	w.WriteInt32(p.CreditRewardForMonthlySpent)
	w.WriteInt32(p.TimeUntilPayday)
	return nil
}

func DecodeUserKickbackInfoOut(r *codec.Reader) (*UserKickbackInfoOutPacket, error) {
	p := &UserKickbackInfoOutPacket{}
	var err error
	if p.CurrentHcStreak, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FirstSubscriptionDate, err = r.ReadString(); err != nil { return nil, err }
	if p.KickbackPercentage, err = r.ReadFloat64(); err != nil { return nil, err }
	if p.TotalCreditsMissed, err = r.ReadInt32(); err != nil { return nil, err }
	if p.TotalCreditsRewarded, err = r.ReadInt32(); err != nil { return nil, err }
	if p.TotalCreditsSpent, err = r.ReadInt32(); err != nil { return nil, err }
	if p.CreditRewardForStreakBonus, err = r.ReadInt32(); err != nil { return nil, err }
	if p.CreditRewardForMonthlySpent, err = r.ReadInt32(); err != nil { return nil, err }
	if p.TimeUntilPayday, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderRentableFurniRentOrBuyoutOfferOut uint16 = 35

// FurnitureRentableFurniOfferOutPacket — Deliver a rentable furniture rent or buyout offer
type FurnitureRentableFurniOfferOutPacket struct {
	ProductCode string
	DayPrice int32
	TotalPrice int32
	Extend bool
	Buyout bool
	ActAsOwner bool
}

func (p *FurnitureRentableFurniOfferOutPacket) HeaderID() uint16 { return HeaderRentableFurniRentOrBuyoutOfferOut }

func (p *FurnitureRentableFurniOfferOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.ProductCode)
	w.WriteInt32(p.DayPrice)
	w.WriteInt32(p.TotalPrice)
	w.WriteBool(p.Extend)
	w.WriteBool(p.Buyout)
	w.WriteBool(p.ActAsOwner)
	return nil
}

func DecodeFurnitureRentableFurniOfferOut(r *codec.Reader) (*FurnitureRentableFurniOfferOutPacket, error) {
	p := &FurnitureRentableFurniOfferOutPacket{}
	var err error
	if p.ProductCode, err = r.ReadString(); err != nil { return nil, err }
	if p.DayPrice, err = r.ReadInt32(); err != nil { return nil, err }
	if p.TotalPrice, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Extend, err = r.ReadBool(); err != nil { return nil, err }
	if p.Buyout, err = r.ReadBool(); err != nil { return nil, err }
	if p.ActAsOwner, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderClubOffersOut uint16 = 2405

// CatalogClubOffersOutPacket — Deliver available Habbo Club membership offers
type CatalogClubOffersOutPacket struct {
	OfferCount int32
	Offers []byte // TODO: hand-implement nested decode
}

func (p *CatalogClubOffersOutPacket) HeaderID() uint16 { return HeaderClubOffersOut }

func (p *CatalogClubOffersOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OfferCount)
	w.WriteBytes(p.Offers)
	return nil
}

func DecodeCatalogClubOffersOut(r *codec.Reader) (*CatalogClubOffersOutPacket, error) {
	p := &CatalogClubOffersOutPacket{}
	var err error
	if p.OfferCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Offers, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderClubGiftInfoOut uint16 = 619

// CatalogClubGiftInfoOutPacket — Deliver Habbo Club member gift information
type CatalogClubGiftInfoOutPacket struct {
	DaysUntilNextGift int32
	GiftCount int32
	Gifts []byte // TODO: hand-implement nested decode
}

func (p *CatalogClubGiftInfoOutPacket) HeaderID() uint16 { return HeaderClubGiftInfoOut }

func (p *CatalogClubGiftInfoOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.DaysUntilNextGift)
	w.WriteInt32(p.GiftCount)
	w.WriteBytes(p.Gifts)
	return nil
}

func DecodeCatalogClubGiftInfoOut(r *codec.Reader) (*CatalogClubGiftInfoOutPacket, error) {
	p := &CatalogClubGiftInfoOutPacket{}
	var err error
	if p.DaysUntilNextGift, err = r.ReadInt32(); err != nil { return nil, err }
	if p.GiftCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Gifts, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderProductOfferOut uint16 = 3388

// CatalogProductOfferOutPacket — Deliver details for a single product offer
type CatalogProductOfferOutPacket struct {
	Offer []byte // TODO: hand-implement nested decode
}

func (p *CatalogProductOfferOutPacket) HeaderID() uint16 { return HeaderProductOfferOut }

func (p *CatalogProductOfferOutPacket) Encode(w *codec.Writer) error {
	w.WriteBytes(p.Offer)
	return nil
}

func DecodeCatalogProductOfferOut(r *codec.Reader) (*CatalogProductOfferOutPacket, error) {
	p := &CatalogProductOfferOutPacket{}
	var err error
	if p.Offer, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderClubExtendedOfferOut uint16 = 3964

// CatalogClubExtendOfferOutPacket — Deliver a Club membership extension offer
type CatalogClubExtendOfferOutPacket struct {
	Offer []byte // TODO: hand-implement nested decode
}

func (p *CatalogClubExtendOfferOutPacket) HeaderID() uint16 { return HeaderClubExtendedOfferOut }

func (p *CatalogClubExtendOfferOutPacket) Encode(w *codec.Writer) error {
	w.WriteBytes(p.Offer)
	return nil
}

func DecodeCatalogClubExtendOfferOut(r *codec.Reader) (*CatalogClubExtendOfferOutPacket, error) {
	p := &CatalogClubExtendOfferOutPacket{}
	var err error
	if p.Offer, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderClubGiftSelectedOut uint16 = 659

// CatalogClubGiftSelectedOutPacket — Confirm a Club gift was claimed
type CatalogClubGiftSelectedOutPacket struct {
	ProductCode string
	Products []byte // TODO: hand-implement nested decode
}

func (p *CatalogClubGiftSelectedOutPacket) HeaderID() uint16 { return HeaderClubGiftSelectedOut }

func (p *CatalogClubGiftSelectedOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.ProductCode)
	w.WriteBytes(p.Products)
	return nil
}

func DecodeCatalogClubGiftSelectedOut(r *codec.Reader) (*CatalogClubGiftSelectedOutPacket, error) {
	p := &CatalogClubGiftSelectedOutPacket{}
	var err error
	if p.ProductCode, err = r.ReadString(); err != nil { return nil, err }
	if p.Products, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderBuildersClubExpiredOut uint16 = 1452

// CatalogBuildersClubSubscriptionOutPacket — Deliver Builders Club subscription status
type CatalogBuildersClubSubscriptionOutPacket struct {
	SecondsLeft int32
	FurniLimit int32
	MaxFurniLimit int32
	SecondsLeftWithGrace int32
}

func (p *CatalogBuildersClubSubscriptionOutPacket) HeaderID() uint16 { return HeaderBuildersClubExpiredOut }

func (p *CatalogBuildersClubSubscriptionOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.SecondsLeft)
	w.WriteInt32(p.FurniLimit)
	w.WriteInt32(p.MaxFurniLimit)
	w.WriteInt32(p.SecondsLeftWithGrace)
	return nil
}

func DecodeCatalogBuildersClubSubscriptionOut(r *codec.Reader) (*CatalogBuildersClubSubscriptionOutPacket, error) {
	p := &CatalogBuildersClubSubscriptionOutPacket{}
	var err error
	if p.SecondsLeft, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FurniLimit, err = r.ReadInt32(); err != nil { return nil, err }
	if p.MaxFurniLimit, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SecondsLeftWithGrace, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderBuildersClubFurniCountOut uint16 = 3828

// CatalogBuildersClubFurniCountOutPacket — Return the current Builders Club furniture count
type CatalogBuildersClubFurniCountOutPacket struct {
	FurniCount int32
}

func (p *CatalogBuildersClubFurniCountOutPacket) HeaderID() uint16 { return HeaderBuildersClubFurniCountOut }

func (p *CatalogBuildersClubFurniCountOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.FurniCount)
	return nil
}

func DecodeCatalogBuildersClubFurniCountOut(r *codec.Reader) (*CatalogBuildersClubFurniCountOutPacket, error) {
	p := &CatalogBuildersClubFurniCountOutPacket{}
	var err error
	if p.FurniCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderDirectSmsClubBuyOut uint16 = 195

// CatalogDirectSmsClubBuyOutPacket — Deliver direct SMS Club purchase availability
type CatalogDirectSmsClubBuyOutPacket struct {
	PricePointUrl string
	Market string
	LengthInDays int32
}

func (p *CatalogDirectSmsClubBuyOutPacket) HeaderID() uint16 { return HeaderDirectSmsClubBuyOut }

func (p *CatalogDirectSmsClubBuyOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.PricePointUrl)
	w.WriteString(p.Market)
	w.WriteInt32(p.LengthInDays)
	return nil
}

func DecodeCatalogDirectSmsClubBuyOut(r *codec.Reader) (*CatalogDirectSmsClubBuyOutPacket, error) {
	p := &CatalogDirectSmsClubBuyOutPacket{}
	var err error
	if p.PricePointUrl, err = r.ReadString(); err != nil { return nil, err }
	if p.Market, err = r.ReadString(); err != nil { return nil, err }
	if p.LengthInDays, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderNotEnoughBalanceOut uint16 = 3914

// CatalogNotEnoughBalanceOutPacket — Indicate insufficient balance for a purchase
type CatalogNotEnoughBalanceOutPacket struct {
	NotEnoughCredits bool
	NotEnoughActivityPoints bool
	ActivityPointType int32
}

func (p *CatalogNotEnoughBalanceOutPacket) HeaderID() uint16 { return HeaderNotEnoughBalanceOut }

func (p *CatalogNotEnoughBalanceOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.NotEnoughCredits)
	w.WriteBool(p.NotEnoughActivityPoints)
	w.WriteInt32(p.ActivityPointType)
	return nil
}

func DecodeCatalogNotEnoughBalanceOut(r *codec.Reader) (*CatalogNotEnoughBalanceOutPacket, error) {
	p := &CatalogNotEnoughBalanceOutPacket{}
	var err error
	if p.NotEnoughCredits, err = r.ReadBool(); err != nil { return nil, err }
	if p.NotEnoughActivityPoints, err = r.ReadBool(); err != nil { return nil, err }
	if p.ActivityPointType, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderIsOfferGiftableOut uint16 = 761

// CatalogIsOfferGiftableOutPacket — Indicate whether a catalog offer can be sent as a gift
type CatalogIsOfferGiftableOutPacket struct {
	OfferId int32
	IsGiftable bool
}

func (p *CatalogIsOfferGiftableOutPacket) HeaderID() uint16 { return HeaderIsOfferGiftableOut }

func (p *CatalogIsOfferGiftableOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OfferId)
	w.WriteBool(p.IsGiftable)
	return nil
}

func DecodeCatalogIsOfferGiftableOut(r *codec.Reader) (*CatalogIsOfferGiftableOutPacket, error) {
	p := &CatalogIsOfferGiftableOutPacket{}
	var err error
	if p.OfferId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.IsGiftable, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderLimitedOfferAppearingNextOut uint16 = 44

// CatalogLimitedOfferAppearingNextOutPacket — Announce the next limited offer appearance
type CatalogLimitedOfferAppearingNextOutPacket struct {
	AppearsInSeconds int32
	PageId int32
	OfferId int32
	ProductType string
}

func (p *CatalogLimitedOfferAppearingNextOutPacket) HeaderID() uint16 { return HeaderLimitedOfferAppearingNextOut }

func (p *CatalogLimitedOfferAppearingNextOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.AppearsInSeconds)
	w.WriteInt32(p.PageId)
	w.WriteInt32(p.OfferId)
	w.WriteString(p.ProductType)
	return nil
}

func DecodeCatalogLimitedOfferAppearingNextOut(r *codec.Reader) (*CatalogLimitedOfferAppearingNextOutPacket, error) {
	p := &CatalogLimitedOfferAppearingNextOutPacket{}
	var err error
	if p.AppearsInSeconds, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PageId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.OfferId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ProductType, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderCatalogPageExpirationOut uint16 = 2668

// CatalogPageExpirationOutPacket — Deliver a catalog page expiration timestamp
type CatalogPageExpirationOutPacket struct {
	PageId int32
	SecondsLeft int32
	PageName string
}

func (p *CatalogPageExpirationOutPacket) HeaderID() uint16 { return HeaderCatalogPageExpirationOut }

func (p *CatalogPageExpirationOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PageId)
	w.WriteInt32(p.SecondsLeft)
	w.WriteString(p.PageName)
	return nil
}

func DecodeCatalogPageExpirationOut(r *codec.Reader) (*CatalogPageExpirationOutPacket, error) {
	p := &CatalogPageExpirationOutPacket{}
	var err error
	if p.PageId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SecondsLeft, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PageName, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderCatalogEarliestExpiryOut uint16 = 2515

// CatalogEarliestExpiryOutPacket — Deliver the earliest catalog page expiration
type CatalogEarliestExpiryOutPacket struct {
	PageName string
	SecondsLeft int32
}

func (p *CatalogEarliestExpiryOutPacket) HeaderID() uint16 { return HeaderCatalogEarliestExpiryOut }

func (p *CatalogEarliestExpiryOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.PageName)
	w.WriteInt32(p.SecondsLeft)
	return nil
}

func DecodeCatalogEarliestExpiryOut(r *codec.Reader) (*CatalogEarliestExpiryOutPacket, error) {
	p := &CatalogEarliestExpiryOutPacket{}
	var err error
	if p.PageName, err = r.ReadString(); err != nil { return nil, err }
	if p.SecondsLeft, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderTargetOfferOut uint16 = 119

// OfferTargetedOutPacket — Deliver a targeted offer to the player
type OfferTargetedOutPacket struct {
	OfferId int32
	Identifier string
	ProductCode string
	PriceCredits int32
	PriceActivityPoints int32
	ActivityPointType int32
	PurchaseLimit int32
	ExpirationTime int32
	Title string
	Description string
	ImageUrl string
	IconImageUrl string
	Type int32
	SubProductCodes []string
}

func (p *OfferTargetedOutPacket) HeaderID() uint16 { return HeaderTargetOfferOut }

func (p *OfferTargetedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.OfferId)
	w.WriteString(p.Identifier)
	w.WriteString(p.ProductCode)
	w.WriteInt32(p.PriceCredits)
	w.WriteInt32(p.PriceActivityPoints)
	w.WriteInt32(p.ActivityPointType)
	w.WriteInt32(p.PurchaseLimit)
	w.WriteInt32(p.ExpirationTime)
	w.WriteString(p.Title)
	w.WriteString(p.Description)
	w.WriteString(p.ImageUrl)
	w.WriteString(p.IconImageUrl)
	w.WriteInt32(p.Type)
	w.WriteListString(p.SubProductCodes)
	return nil
}

func DecodeOfferTargetedOut(r *codec.Reader) (*OfferTargetedOutPacket, error) {
	p := &OfferTargetedOutPacket{}
	var err error
	if p.OfferId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Identifier, err = r.ReadString(); err != nil { return nil, err }
	if p.ProductCode, err = r.ReadString(); err != nil { return nil, err }
	if p.PriceCredits, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PriceActivityPoints, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ActivityPointType, err = r.ReadInt32(); err != nil { return nil, err }
	if p.PurchaseLimit, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ExpirationTime, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Title, err = r.ReadString(); err != nil { return nil, err }
	if p.Description, err = r.ReadString(); err != nil { return nil, err }
	if p.ImageUrl, err = r.ReadString(); err != nil { return nil, err }
	if p.IconImageUrl, err = r.ReadString(); err != nil { return nil, err }
	if p.Type, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SubProductCodes, err = r.ReadListString(); err != nil { return nil, err }
	return p, nil
}

const HeaderTargetOfferNotFoundOut uint16 = 1237

// OfferTargetedNotFoundOutPacket — Indicate no targeted offer is available
type OfferTargetedNotFoundOutPacket struct {
}

func (p *OfferTargetedNotFoundOutPacket) HeaderID() uint16 { return HeaderTargetOfferNotFoundOut }

func (p *OfferTargetedNotFoundOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeOfferTargetedNotFoundOut(r *codec.Reader) (*OfferTargetedNotFoundOutPacket, error) {
	p := &OfferTargetedNotFoundOutPacket{}
	return p, nil
}

const HeaderCampaignCalendarDataOut uint16 = 2531

// CalendarDataOutPacket — Deliver campaign calendar data
type CalendarDataOutPacket struct {
	CampaignName string
	CampaignImage string
	CurrentDay int32
	CampaignDays int32
	OpenedDays []int32
	MissedDays []int32
}

func (p *CalendarDataOutPacket) HeaderID() uint16 { return HeaderCampaignCalendarDataOut }

func (p *CalendarDataOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.CampaignName)
	w.WriteString(p.CampaignImage)
	w.WriteInt32(p.CurrentDay)
	w.WriteInt32(p.CampaignDays)
	w.WriteListInt32(p.OpenedDays)
	w.WriteListInt32(p.MissedDays)
	return nil
}

func DecodeCalendarDataOut(r *codec.Reader) (*CalendarDataOutPacket, error) {
	p := &CalendarDataOutPacket{}
	var err error
	if p.CampaignName, err = r.ReadString(); err != nil { return nil, err }
	if p.CampaignImage, err = r.ReadString(); err != nil { return nil, err }
	if p.CurrentDay, err = r.ReadInt32(); err != nil { return nil, err }
	if p.CampaignDays, err = r.ReadInt32(); err != nil { return nil, err }
	if p.OpenedDays, err = r.ReadListInt32(); err != nil { return nil, err }
	if p.MissedDays, err = r.ReadListInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderCampaignCalendarDoorOpenedOut uint16 = 2551

// CalendarDoorOpenedOutPacket — Confirm a calendar door was opened and deliver the reward
type CalendarDoorOpenedOutPacket struct {
	DoorOpened bool
	ProductName string
	CustomImage string
	FurnitureClassName string
}

func (p *CalendarDoorOpenedOutPacket) HeaderID() uint16 { return HeaderCampaignCalendarDoorOpenedOut }

func (p *CalendarDoorOpenedOutPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.DoorOpened)
	w.WriteString(p.ProductName)
	w.WriteString(p.CustomImage)
	w.WriteString(p.FurnitureClassName)
	return nil
}

func DecodeCalendarDoorOpenedOut(r *codec.Reader) (*CalendarDoorOpenedOutPacket, error) {
	p := &CalendarDoorOpenedOutPacket{}
	var err error
	if p.DoorOpened, err = r.ReadBool(); err != nil { return nil, err }
	if p.ProductName, err = r.ReadString(); err != nil { return nil, err }
	if p.CustomImage, err = r.ReadString(); err != nil { return nil, err }
	if p.FurnitureClassName, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderSeasonalCalendarOfferOut uint16 = 1889

// CalendarSeasonalDailyOfferOutPacket — Deliver the seasonal calendar daily offer
type CalendarSeasonalDailyOfferOutPacket struct {
	PageId int32
	Offer []byte // TODO: hand-implement nested decode
}

func (p *CalendarSeasonalDailyOfferOutPacket) HeaderID() uint16 { return HeaderSeasonalCalendarOfferOut }

func (p *CalendarSeasonalDailyOfferOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PageId)
	w.WriteBytes(p.Offer)
	return nil
}

func DecodeCalendarSeasonalDailyOfferOut(r *codec.Reader) (*CalendarSeasonalDailyOfferOutPacket, error) {
	p := &CalendarSeasonalDailyOfferOutPacket{}
	var err error
	if p.PageId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Offer, err = r.ReadBytes(); err != nil { return nil, err }
	return p, nil
}

const HeaderBonusRareInfoOut uint16 = 1533

// SubscriptionBonusRareInfoOutPacket — Bonus rare info
type SubscriptionBonusRareInfoOutPacket struct {
	Field1 string
	Field2 int32
	Field3 int32
	Field4 int32
}

func (p *SubscriptionBonusRareInfoOutPacket) HeaderID() uint16 { return HeaderBonusRareInfoOut }

func (p *SubscriptionBonusRareInfoOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Field1)
	w.WriteInt32(p.Field2)
	w.WriteInt32(p.Field3)
	w.WriteInt32(p.Field4)
	return nil
}

func DecodeSubscriptionBonusRareInfoOut(r *codec.Reader) (*SubscriptionBonusRareInfoOutPacket, error) {
	p := &SubscriptionBonusRareInfoOutPacket{}
	var err error
	if p.Field1, err = r.ReadString(); err != nil { return nil, err }
	if p.Field2, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field3, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Field4, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderNewUserExperienceGiftOfferOut uint16 = 3575

// SubscriptionNewUserExperienceGiftOfferOutPacket — New user experience gift offer
type SubscriptionNewUserExperienceGiftOfferOutPacket struct {
	Field1 int32
}

func (p *SubscriptionNewUserExperienceGiftOfferOutPacket) HeaderID() uint16 { return HeaderNewUserExperienceGiftOfferOut }

func (p *SubscriptionNewUserExperienceGiftOfferOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Field1)
	return nil
}

func DecodeSubscriptionNewUserExperienceGiftOfferOut(r *codec.Reader) (*SubscriptionNewUserExperienceGiftOfferOutPacket, error) {
	p := &SubscriptionNewUserExperienceGiftOfferOutPacket{}
	var err error
	if p.Field1, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderNewUserExperienceNotCompleteOut uint16 = 3639

// SubscriptionNewUserExperienceNotCompleteOutPacket — New user experience not complete
type SubscriptionNewUserExperienceNotCompleteOutPacket struct {
}

func (p *SubscriptionNewUserExperienceNotCompleteOutPacket) HeaderID() uint16 { return HeaderNewUserExperienceNotCompleteOut }

func (p *SubscriptionNewUserExperienceNotCompleteOutPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeSubscriptionNewUserExperienceNotCompleteOut(r *codec.Reader) (*SubscriptionNewUserExperienceNotCompleteOutPacket, error) {
	p := &SubscriptionNewUserExperienceNotCompleteOutPacket{}
	return p, nil
}

