// Code generated by protogen. DO NOT EDIT.

package protocol

import "pixel-server/pkg/core/codec"

const HeaderUserInfoIn uint16 = 357

// UserGetInfoInPacket — Request own user data from the server
type UserGetInfoInPacket struct {
}

func (p *UserGetInfoInPacket) HeaderID() uint16 { return HeaderUserInfoIn }

func (p *UserGetInfoInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserGetInfoIn(r *codec.Reader) (*UserGetInfoInPacket, error) {
	p := &UserGetInfoInPacket{}
	return p, nil
}

const HeaderUserProfileIn uint16 = 3265

// UserGetProfileInPacket — Request the public profile of a user by ID
type UserGetProfileInPacket struct {
	UserId int32
	OpenProfile bool
}

func (p *UserGetProfileInPacket) HeaderID() uint16 { return HeaderUserProfileIn }

func (p *UserGetProfileInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	w.WriteBool(p.OpenProfile)
	return nil
}

func DecodeUserGetProfileIn(r *codec.Reader) (*UserGetProfileInPacket, error) {
	p := &UserGetProfileInPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.OpenProfile, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserProfileByNameIn uint16 = 2249

// UserGetProfileByNameInPacket — Request the public profile of a user by username
type UserGetProfileByNameInPacket struct {
	Username string
}

func (p *UserGetProfileByNameInPacket) HeaderID() uint16 { return HeaderUserProfileByNameIn }

func (p *UserGetProfileByNameInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Username)
	return nil
}

func DecodeUserGetProfileByNameIn(r *codec.Reader) (*UserGetProfileByNameInPacket, error) {
	p := &UserGetProfileByNameInPacket{}
	var err error
	if p.Username, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerRelationshipsIn uint16 = 2138

// UserGetRelationshipStatusInPacket — Request the public relationship status entries for a user
type UserGetRelationshipStatusInPacket struct {
	UserId int32
}

func (p *UserGetRelationshipStatusInPacket) HeaderID() uint16 { return HeaderMessengerRelationshipsIn }

func (p *UserGetRelationshipStatusInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeUserGetRelationshipStatusIn(r *codec.Reader) (*UserGetRelationshipStatusInPacket, error) {
	p := &UserGetRelationshipStatusInPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderSetRelationshipStatusIn uint16 = 3768

// UserSetRelationshipStatusInPacket — Set or clear the relationship status toward a friend
type UserSetRelationshipStatusInPacket struct {
	FriendId int32
	RelationshipType int32
}

func (p *UserSetRelationshipStatusInPacket) HeaderID() uint16 { return HeaderSetRelationshipStatusIn }

func (p *UserSetRelationshipStatusInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.FriendId)
	w.WriteInt32(p.RelationshipType)
	return nil
}

func DecodeUserSetRelationshipStatusIn(r *codec.Reader) (*UserSetRelationshipStatusInPacket, error) {
	p := &UserSetRelationshipStatusInPacket{}
	var err error
	if p.FriendId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RelationshipType, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserTagsIn uint16 = 17

// UserGetTagsInPacket — Request the profile tags of a user currently in a room
type UserGetTagsInPacket struct {
	RoomUnitId int32
}

func (p *UserGetTagsInPacket) HeaderID() uint16 { return HeaderUserTagsIn }

func (p *UserGetTagsInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomUnitId)
	return nil
}

func DecodeUserGetTagsIn(r *codec.Reader) (*UserGetTagsInPacket, error) {
	p := &UserGetTagsInPacket{}
	var err error
	if p.RoomUnitId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserFigureIn uint16 = 2730

// UserUpdateFigureInPacket — Update the authenticated user's avatar figure and gender
type UserUpdateFigureInPacket struct {
	Gender string
	Figure string
}

func (p *UserUpdateFigureInPacket) HeaderID() uint16 { return HeaderUserFigureIn }

func (p *UserUpdateFigureInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Gender)
	w.WriteString(p.Figure)
	return nil
}

func DecodeUserUpdateFigureIn(r *codec.Reader) (*UserUpdateFigureInPacket, error) {
	p := &UserUpdateFigureInPacket{}
	var err error
	if p.Gender, err = r.ReadString(); err != nil { return nil, err }
	if p.Figure, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserMottoIn uint16 = 2228

// UserUpdateMottoInPacket — Update the authenticated user's motto
type UserUpdateMottoInPacket struct {
	Motto string
}

func (p *UserUpdateMottoInPacket) HeaderID() uint16 { return HeaderUserMottoIn }

func (p *UserUpdateMottoInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Motto)
	return nil
}

func DecodeUserUpdateMottoIn(r *codec.Reader) (*UserUpdateMottoInPacket, error) {
	p := &UserUpdateMottoInPacket{}
	var err error
	if p.Motto, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserRespectIn uint16 = 2694

// UserRespectInPacket — Send a respect point to another user
type UserRespectInPacket struct {
	UserId int32
}

func (p *UserRespectInPacket) HeaderID() uint16 { return HeaderUserRespectIn }

func (p *UserRespectInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeUserRespectIn(r *codec.Reader) (*UserRespectInPacket, error) {
	p := &UserRespectInPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserIgnoredIn uint16 = 3878

// UserGetIgnoredInPacket — Fetch the ignored-users list filtered by username prefix
type UserGetIgnoredInPacket struct {
	Username string
}

func (p *UserGetIgnoredInPacket) HeaderID() uint16 { return HeaderUserIgnoredIn }

func (p *UserGetIgnoredInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Username)
	return nil
}

func DecodeUserGetIgnoredIn(r *codec.Reader) (*UserGetIgnoredInPacket, error) {
	p := &UserGetIgnoredInPacket{}
	var err error
	if p.Username, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserIgnoreIn uint16 = 1117

// UserIgnoreInPacket — Add a user to the ignore list by username
type UserIgnoreInPacket struct {
	Username string
}

func (p *UserIgnoreInPacket) HeaderID() uint16 { return HeaderUserIgnoreIn }

func (p *UserIgnoreInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Username)
	return nil
}

func DecodeUserIgnoreIn(r *codec.Reader) (*UserIgnoreInPacket, error) {
	p := &UserIgnoreInPacket{}
	var err error
	if p.Username, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserIgnoreIdIn uint16 = 3314

// UserIgnoreIdInPacket — Add a user to the ignore list by user ID
type UserIgnoreIdInPacket struct {
	UserId int32
}

func (p *UserIgnoreIdInPacket) HeaderID() uint16 { return HeaderUserIgnoreIdIn }

func (p *UserIgnoreIdInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeUserIgnoreIdIn(r *codec.Reader) (*UserIgnoreIdInPacket, error) {
	p := &UserIgnoreIdInPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserUnignoreIn uint16 = 2061

// UserUnignoreInPacket — Remove a user from the ignore list
type UserUnignoreInPacket struct {
	Username string
}

func (p *UserUnignoreInPacket) HeaderID() uint16 { return HeaderUserUnignoreIn }

func (p *UserUnignoreInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Username)
	return nil
}

func DecodeUserUnignoreIn(r *codec.Reader) (*UserUnignoreInPacket, error) {
	p := &UserUnignoreInPacket{}
	var err error
	if p.Username, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserSettingsVolumeIn uint16 = 1367

// UserSettingsVolumeInPacket — Save audio volume preferences
type UserSettingsVolumeInPacket struct {
	VolumeSystem int32
	VolumeFurni int32
	VolumeTrax int32
}

func (p *UserSettingsVolumeInPacket) HeaderID() uint16 { return HeaderUserSettingsVolumeIn }

func (p *UserSettingsVolumeInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.VolumeSystem)
	w.WriteInt32(p.VolumeFurni)
	w.WriteInt32(p.VolumeTrax)
	return nil
}

func DecodeUserSettingsVolumeIn(r *codec.Reader) (*UserSettingsVolumeInPacket, error) {
	p := &UserSettingsVolumeInPacket{}
	var err error
	if p.VolumeSystem, err = r.ReadInt32(); err != nil { return nil, err }
	if p.VolumeFurni, err = r.ReadInt32(); err != nil { return nil, err }
	if p.VolumeTrax, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserSettingsOldChatIn uint16 = 1262

// UserSettingsOldChatInPacket — Toggle old-style chat bubble mode
type UserSettingsOldChatInPacket struct {
	OldChat bool
}

func (p *UserSettingsOldChatInPacket) HeaderID() uint16 { return HeaderUserSettingsOldChatIn }

func (p *UserSettingsOldChatInPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.OldChat)
	return nil
}

func DecodeUserSettingsOldChatIn(r *codec.Reader) (*UserSettingsOldChatInPacket, error) {
	p := &UserSettingsOldChatInPacket{}
	var err error
	if p.OldChat, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserSettingsInvitesIn uint16 = 1086

// UserSettingsRoomInvitesInPacket — Toggle room invitation acceptance
type UserSettingsRoomInvitesInPacket struct {
	RoomInvites bool
}

func (p *UserSettingsRoomInvitesInPacket) HeaderID() uint16 { return HeaderUserSettingsInvitesIn }

func (p *UserSettingsRoomInvitesInPacket) Encode(w *codec.Writer) error {
	w.WriteBool(p.RoomInvites)
	return nil
}

func DecodeUserSettingsRoomInvitesIn(r *codec.Reader) (*UserSettingsRoomInvitesInPacket, error) {
	p := &UserSettingsRoomInvitesInPacket{}
	var err error
	if p.RoomInvites, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserEffectEnableIn uint16 = 1752

// UserEffectEnableInPacket — Select or highlight an avatar effect in the inventory
type UserEffectEnableInPacket struct {
	Type int32
}

func (p *UserEffectEnableInPacket) HeaderID() uint16 { return HeaderUserEffectEnableIn }

func (p *UserEffectEnableInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Type)
	return nil
}

func DecodeUserEffectEnableIn(r *codec.Reader) (*UserEffectEnableInPacket, error) {
	p := &UserEffectEnableInPacket{}
	var err error
	if p.Type, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetWardrobeIn uint16 = 2742

// UserGetWardrobeInPacket — Request a page of saved wardrobe outfits
type UserGetWardrobeInPacket struct {
	PageId int32
}

func (p *UserGetWardrobeInPacket) HeaderID() uint16 { return HeaderGetWardrobeIn }

func (p *UserGetWardrobeInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PageId)
	return nil
}

func DecodeUserGetWardrobeIn(r *codec.Reader) (*UserGetWardrobeInPacket, error) {
	p := &UserGetWardrobeInPacket{}
	var err error
	if p.PageId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderSaveWardrobeOutfitIn uint16 = 800

// UserSaveWardrobeOutfitInPacket — Save an outfit to a wardrobe slot
type UserSaveWardrobeOutfitInPacket struct {
	SlotId int32
	Look string
	Gender string
}

func (p *UserSaveWardrobeOutfitInPacket) HeaderID() uint16 { return HeaderSaveWardrobeOutfitIn }

func (p *UserSaveWardrobeOutfitInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.SlotId)
	w.WriteString(p.Look)
	w.WriteString(p.Gender)
	return nil
}

func DecodeUserSaveWardrobeOutfitIn(r *codec.Reader) (*UserSaveWardrobeOutfitInPacket, error) {
	p := &UserSaveWardrobeOutfitInPacket{}
	var err error
	if p.SlotId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Look, err = r.ReadString(); err != nil { return nil, err }
	if p.Gender, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderChangeUsernameIn uint16 = 2977

// UserChangeNameInPacket — Submit a new display name for the authenticated user
type UserChangeNameInPacket struct {
	Name string
}

func (p *UserChangeNameInPacket) HeaderID() uint16 { return HeaderChangeUsernameIn }

func (p *UserChangeNameInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Name)
	return nil
}

func DecodeUserChangeNameIn(r *codec.Reader) (*UserChangeNameInPacket, error) {
	p := &UserChangeNameInPacket{}
	var err error
	if p.Name, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderCheckUsernameIn uint16 = 3950

// UserCheckNameInPacket — Validate a candidate display name before committing
type UserCheckNameInPacket struct {
	Name string
}

func (p *UserCheckNameInPacket) HeaderID() uint16 { return HeaderCheckUsernameIn }

func (p *UserCheckNameInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Name)
	return nil
}

func DecodeUserCheckNameIn(r *codec.Reader) (*UserCheckNameInPacket, error) {
	p := &UserCheckNameInPacket{}
	var err error
	if p.Name, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderApproveNameIn uint16 = 2109

// UserApproveNameInPacket — Submit a name string for server-side word screening
type UserApproveNameInPacket struct {
	Name string
	Type int32
}

func (p *UserApproveNameInPacket) HeaderID() uint16 { return HeaderApproveNameIn }

func (p *UserApproveNameInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Name)
	w.WriteInt32(p.Type)
	return nil
}

func DecodeUserApproveNameIn(r *codec.Reader) (*UserApproveNameInPacket, error) {
	p := &UserApproveNameInPacket{}
	var err error
	if p.Name, err = r.ReadString(); err != nil { return nil, err }
	if p.Type, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserHomeRoomIn uint16 = 1740

// UserSetHomeRoomInPacket — Set the user's home room
type UserSetHomeRoomInPacket struct {
	RoomId int32
}

func (p *UserSetHomeRoomInPacket) HeaderID() uint16 { return HeaderUserHomeRoomIn }

func (p *UserSetHomeRoomInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomId)
	return nil
}

func DecodeUserSetHomeRoomIn(r *codec.Reader) (*UserSetHomeRoomInPacket, error) {
	p := &UserSetHomeRoomInPacket{}
	var err error
	if p.RoomId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderEmailGetStatusIn uint16 = 2557

// UserGetEmailStatusInPacket — Request the account email address and verification status
type UserGetEmailStatusInPacket struct {
}

func (p *UserGetEmailStatusInPacket) HeaderID() uint16 { return HeaderEmailGetStatusIn }

func (p *UserGetEmailStatusInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserGetEmailStatusIn(r *codec.Reader) (*UserGetEmailStatusInPacket, error) {
	p := &UserGetEmailStatusInPacket{}
	return p, nil
}

const HeaderEmailChangeIn uint16 = 3965

// UserChangeEmailInPacket — Submit a new email address for the account
type UserChangeEmailInPacket struct {
	NewEmail string
}

func (p *UserChangeEmailInPacket) HeaderID() uint16 { return HeaderEmailChangeIn }

func (p *UserChangeEmailInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.NewEmail)
	return nil
}

func DecodeUserChangeEmailIn(r *codec.Reader) (*UserChangeEmailInPacket, error) {
	p := &UserChangeEmailInPacket{}
	var err error
	if p.NewEmail, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderWelcomeGiftChangeEmailIn uint16 = 66

// UserWelcomeGiftChangeEmailInPacket — Submit an email address update as part of the welcome-gift flow
type UserWelcomeGiftChangeEmailInPacket struct {
	NewEmail string
}

func (p *UserWelcomeGiftChangeEmailInPacket) HeaderID() uint16 { return HeaderWelcomeGiftChangeEmailIn }

func (p *UserWelcomeGiftChangeEmailInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.NewEmail)
	return nil
}

func DecodeUserWelcomeGiftChangeEmailIn(r *codec.Reader) (*UserWelcomeGiftChangeEmailInPacket, error) {
	p := &UserWelcomeGiftChangeEmailInPacket{}
	var err error
	if p.NewEmail, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderNewUserExperienceScriptProceedIn uint16 = 1299

// UserNuxProceedInPacket — Signal completion of the current new-user experience step
type UserNuxProceedInPacket struct {
}

func (p *UserNuxProceedInPacket) HeaderID() uint16 { return HeaderNewUserExperienceScriptProceedIn }

func (p *UserNuxProceedInPacket) Encode(w *codec.Writer) error {
	return nil
}

func DecodeUserNuxProceedIn(r *codec.Reader) (*UserNuxProceedInPacket, error) {
	p := &UserNuxProceedInPacket{}
	return p, nil
}

const HeaderNewUserExperienceGetGiftsIn uint16 = 1822

// UserNuxGetGiftsInPacket — Submit gift selections during the new-user experience
type UserNuxGetGiftsInPacket struct {
	SelectionCount int32
}

func (p *UserNuxGetGiftsInPacket) HeaderID() uint16 { return HeaderNewUserExperienceGetGiftsIn }

func (p *UserNuxGetGiftsInPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.SelectionCount)
	return nil
}

func DecodeUserNuxGetGiftsIn(r *codec.Reader) (*UserNuxGetGiftsInPacket, error) {
	p := &UserNuxGetGiftsInPacket{}
	var err error
	if p.SelectionCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserClassificationIn uint16 = 2285

// UserSetClassificationInPacket — Declare the user class type for the current session
type UserSetClassificationInPacket struct {
	UserClassType string
}

func (p *UserSetClassificationInPacket) HeaderID() uint16 { return HeaderUserClassificationIn }

func (p *UserSetClassificationInPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.UserClassType)
	return nil
}

func DecodeUserSetClassificationIn(r *codec.Reader) (*UserSetClassificationInPacket, error) {
	p := &UserSetClassificationInPacket{}
	var err error
	if p.UserClassType, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserInfoOut uint16 = 2725

// UserInfoOutPacket — Deliver the authenticated user's own identity and preference data
type UserInfoOutPacket struct {
	UserId int32
	Username string
	Figure string
	Gender string
	Motto string
	RealName string
	DirectMail bool
	RespectsReceived int32
	RespectsRemaining int32
	RespectsPetRemaining int32
	StreamPublishingAllowed bool
	LastAccessDate string
	CanChangeName bool
	SafetyLocked bool
}

func (p *UserInfoOutPacket) HeaderID() uint16 { return HeaderUserInfoOut }

func (p *UserInfoOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	w.WriteString(p.Username)
	w.WriteString(p.Figure)
	w.WriteString(p.Gender)
	w.WriteString(p.Motto)
	w.WriteString(p.RealName)
	w.WriteBool(p.DirectMail)
	w.WriteInt32(p.RespectsReceived)
	w.WriteInt32(p.RespectsRemaining)
	w.WriteInt32(p.RespectsPetRemaining)
	w.WriteBool(p.StreamPublishingAllowed)
	w.WriteString(p.LastAccessDate)
	w.WriteBool(p.CanChangeName)
	w.WriteBool(p.SafetyLocked)
	return nil
}

func DecodeUserInfoOut(r *codec.Reader) (*UserInfoOutPacket, error) {
	p := &UserInfoOutPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Username, err = r.ReadString(); err != nil { return nil, err }
	if p.Figure, err = r.ReadString(); err != nil { return nil, err }
	if p.Gender, err = r.ReadString(); err != nil { return nil, err }
	if p.Motto, err = r.ReadString(); err != nil { return nil, err }
	if p.RealName, err = r.ReadString(); err != nil { return nil, err }
	if p.DirectMail, err = r.ReadBool(); err != nil { return nil, err }
	if p.RespectsReceived, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RespectsRemaining, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RespectsPetRemaining, err = r.ReadInt32(); err != nil { return nil, err }
	if p.StreamPublishingAllowed, err = r.ReadBool(); err != nil { return nil, err }
	if p.LastAccessDate, err = r.ReadString(); err != nil { return nil, err }
	if p.CanChangeName, err = r.ReadBool(); err != nil { return nil, err }
	if p.SafetyLocked, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserProfileOut uint16 = 3898

// UserProfileOutPacket — Deliver a user's public profile card data
type UserProfileOutPacket struct {
	Id int32
	Username string
	Figure string
	Motto string
	Registration string
	AchievementPoints int32
	FriendsCount int32
	IsMyFriend bool
	RequestSent bool
	IsOnline bool
	GroupsCount int32
}

func (p *UserProfileOutPacket) HeaderID() uint16 { return HeaderUserProfileOut }

func (p *UserProfileOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Id)
	w.WriteString(p.Username)
	w.WriteString(p.Figure)
	w.WriteString(p.Motto)
	w.WriteString(p.Registration)
	w.WriteInt32(p.AchievementPoints)
	w.WriteInt32(p.FriendsCount)
	w.WriteBool(p.IsMyFriend)
	w.WriteBool(p.RequestSent)
	w.WriteBool(p.IsOnline)
	w.WriteInt32(p.GroupsCount)
	return nil
}

func DecodeUserProfileOut(r *codec.Reader) (*UserProfileOutPacket, error) {
	p := &UserProfileOutPacket{}
	var err error
	if p.Id, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Username, err = r.ReadString(); err != nil { return nil, err }
	if p.Figure, err = r.ReadString(); err != nil { return nil, err }
	if p.Motto, err = r.ReadString(); err != nil { return nil, err }
	if p.Registration, err = r.ReadString(); err != nil { return nil, err }
	if p.AchievementPoints, err = r.ReadInt32(); err != nil { return nil, err }
	if p.FriendsCount, err = r.ReadInt32(); err != nil { return nil, err }
	if p.IsMyFriend, err = r.ReadBool(); err != nil { return nil, err }
	if p.RequestSent, err = r.ReadBool(); err != nil { return nil, err }
	if p.IsOnline, err = r.ReadBool(); err != nil { return nil, err }
	if p.GroupsCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderMessengerRelationshipsOut uint16 = 2016

// UserRelationshipStatusOutPacket — Deliver a user's public relationship status entries
type UserRelationshipStatusOutPacket struct {
	UserId int32
	Count int32
}

func (p *UserRelationshipStatusOutPacket) HeaderID() uint16 { return HeaderMessengerRelationshipsOut }

func (p *UserRelationshipStatusOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	w.WriteInt32(p.Count)
	return nil
}

func DecodeUserRelationshipStatusOut(r *codec.Reader) (*UserRelationshipStatusOutPacket, error) {
	p := &UserRelationshipStatusOutPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserPermissionsOut uint16 = 411

// UserPermissionsOutPacket — Deliver the authenticated user's club level and security role
type UserPermissionsOutPacket struct {
	ClubLevel int32
	SecurityLevel int32
	IsAmbassador bool
}

func (p *UserPermissionsOutPacket) HeaderID() uint16 { return HeaderUserPermissionsOut }

func (p *UserPermissionsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ClubLevel)
	w.WriteInt32(p.SecurityLevel)
	w.WriteBool(p.IsAmbassador)
	return nil
}

func DecodeUserPermissionsOut(r *codec.Reader) (*UserPermissionsOutPacket, error) {
	p := &UserPermissionsOutPacket{}
	var err error
	if p.ClubLevel, err = r.ReadInt32(); err != nil { return nil, err }
	if p.SecurityLevel, err = r.ReadInt32(); err != nil { return nil, err }
	if p.IsAmbassador, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserFigureOut uint16 = 2429

// UserFigureOutPacket — Notify the client that its avatar figure has been updated
type UserFigureOutPacket struct {
	Figure string
	Gender string
}

func (p *UserFigureOutPacket) HeaderID() uint16 { return HeaderUserFigureOut }

func (p *UserFigureOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Figure)
	w.WriteString(p.Gender)
	return nil
}

func DecodeUserFigureOut(r *codec.Reader) (*UserFigureOutPacket, error) {
	p := &UserFigureOutPacket{}
	var err error
	if p.Figure, err = r.ReadString(); err != nil { return nil, err }
	if p.Gender, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderUnitChangeNameOut uint16 = 2182

// UserNameChangeOutPacket — Broadcast a user's display name change
type UserNameChangeOutPacket struct {
	WebId int32
	Id int32
	NewName string
}

func (p *UserNameChangeOutPacket) HeaderID() uint16 { return HeaderUnitChangeNameOut }

func (p *UserNameChangeOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.WebId)
	w.WriteInt32(p.Id)
	w.WriteString(p.NewName)
	return nil
}

func DecodeUserNameChangeOut(r *codec.Reader) (*UserNameChangeOutPacket, error) {
	p := &UserNameChangeOutPacket{}
	var err error
	if p.WebId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Id, err = r.ReadInt32(); err != nil { return nil, err }
	if p.NewName, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserSettingsOut uint16 = 513

// UserSettingsOutPacket — Deliver the authenticated user's persisted client settings
type UserSettingsOutPacket struct {
	VolumeSystem int32
	VolumeFurni int32
	VolumeTrax int32
	OldChat bool
	RoomInvites bool
	CameraFollow bool
	Flags int32
	ChatType int32
}

func (p *UserSettingsOutPacket) HeaderID() uint16 { return HeaderUserSettingsOut }

func (p *UserSettingsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.VolumeSystem)
	w.WriteInt32(p.VolumeFurni)
	w.WriteInt32(p.VolumeTrax)
	w.WriteBool(p.OldChat)
	w.WriteBool(p.RoomInvites)
	w.WriteBool(p.CameraFollow)
	w.WriteInt32(p.Flags)
	w.WriteInt32(p.ChatType)
	return nil
}

func DecodeUserSettingsOut(r *codec.Reader) (*UserSettingsOutPacket, error) {
	p := &UserSettingsOutPacket{}
	var err error
	if p.VolumeSystem, err = r.ReadInt32(); err != nil { return nil, err }
	if p.VolumeFurni, err = r.ReadInt32(); err != nil { return nil, err }
	if p.VolumeTrax, err = r.ReadInt32(); err != nil { return nil, err }
	if p.OldChat, err = r.ReadBool(); err != nil { return nil, err }
	if p.RoomInvites, err = r.ReadBool(); err != nil { return nil, err }
	if p.CameraFollow, err = r.ReadBool(); err != nil { return nil, err }
	if p.Flags, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ChatType, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderGetUserTagsOut uint16 = 1255

// UserTagsOutPacket — Deliver the profile tags of a user in a room
type UserTagsOutPacket struct {
	RoomUnitId int32
	Count int32
}

func (p *UserTagsOutPacket) HeaderID() uint16 { return HeaderGetUserTagsOut }

func (p *UserTagsOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.RoomUnitId)
	w.WriteInt32(p.Count)
	return nil
}

func DecodeUserTagsOut(r *codec.Reader) (*UserTagsOutPacket, error) {
	p := &UserTagsOutPacket{}
	var err error
	if p.RoomUnitId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserOutfitsOut uint16 = 3315

// UserWardrobePageOutPacket — Deliver a page of the user's saved wardrobe outfits
type UserWardrobePageOutPacket struct {
	PageIndex int32
	Count int32
}

func (p *UserWardrobePageOutPacket) HeaderID() uint16 { return HeaderUserOutfitsOut }

func (p *UserWardrobePageOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.PageIndex)
	w.WriteInt32(p.Count)
	return nil
}

func DecodeUserWardrobePageOut(r *codec.Reader) (*UserWardrobePageOutPacket, error) {
	p := &UserWardrobePageOutPacket{}
	var err error
	if p.PageIndex, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserRespectOut uint16 = 2815

// UserRespectReceivedOutPacket — Notify that a user has received a respect point
type UserRespectReceivedOutPacket struct {
	UserId int32
	RespectsReceived int32
}

func (p *UserRespectReceivedOutPacket) HeaderID() uint16 { return HeaderUserRespectOut }

func (p *UserRespectReceivedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	w.WriteInt32(p.RespectsReceived)
	return nil
}

func DecodeUserRespectReceivedOut(r *codec.Reader) (*UserRespectReceivedOutPacket, error) {
	p := &UserRespectReceivedOutPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RespectsReceived, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserIgnoredOut uint16 = 126

// UserIgnoredUsersOutPacket — Deliver the current session's ignore list
type UserIgnoredUsersOutPacket struct {
	Count int32
}

func (p *UserIgnoredUsersOutPacket) HeaderID() uint16 { return HeaderUserIgnoredOut }

func (p *UserIgnoredUsersOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Count)
	return nil
}

func DecodeUserIgnoredUsersOut(r *codec.Reader) (*UserIgnoredUsersOutPacket, error) {
	p := &UserIgnoredUsersOutPacket{}
	var err error
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserIgnoredResultOut uint16 = 207

// UserIgnoreResultOutPacket — Report the result of an ignore or unignore action
type UserIgnoreResultOutPacket struct {
	Result int32
	Name string
}

func (p *UserIgnoreResultOutPacket) HeaderID() uint16 { return HeaderUserIgnoredResultOut }

func (p *UserIgnoreResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Result)
	w.WriteString(p.Name)
	return nil
}

func DecodeUserIgnoreResultOut(r *codec.Reader) (*UserIgnoreResultOutPacket, error) {
	p := &UserIgnoreResultOutPacket{}
	var err error
	if p.Result, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Name, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderCheckUserNameOut uint16 = 563

// UserCheckNameResultOutPacket — Return validation result for a candidate display name
type UserCheckNameResultOutPacket struct {
	ResultCode int32
	Name string
	SuggestionCount int32
}

func (p *UserCheckNameResultOutPacket) HeaderID() uint16 { return HeaderCheckUserNameOut }

func (p *UserCheckNameResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ResultCode)
	w.WriteString(p.Name)
	w.WriteInt32(p.SuggestionCount)
	return nil
}

func DecodeUserCheckNameResultOut(r *codec.Reader) (*UserCheckNameResultOutPacket, error) {
	p := &UserCheckNameResultOutPacket{}
	var err error
	if p.ResultCode, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Name, err = r.ReadString(); err != nil { return nil, err }
	if p.SuggestionCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserChangeNameOut uint16 = 118

// UserChangeNameResultOutPacket — Return the result of a display name change request
type UserChangeNameResultOutPacket struct {
	ResultCode int32
	Name string
	SuggestionCount int32
}

func (p *UserChangeNameResultOutPacket) HeaderID() uint16 { return HeaderUserChangeNameOut }

func (p *UserChangeNameResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.ResultCode)
	w.WriteString(p.Name)
	w.WriteInt32(p.SuggestionCount)
	return nil
}

func DecodeUserChangeNameResultOut(r *codec.Reader) (*UserChangeNameResultOutPacket, error) {
	p := &UserChangeNameResultOutPacket{}
	var err error
	if p.ResultCode, err = r.ReadInt32(); err != nil { return nil, err }
	if p.Name, err = r.ReadString(); err != nil { return nil, err }
	if p.SuggestionCount, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderCatalogApproveNameResultOut uint16 = 1503

// UserApproveNameResultOutPacket — Return the approval result for a catalog or pet name
type UserApproveNameResultOutPacket struct {
	Result int32
	ValidationInfo string
}

func (p *UserApproveNameResultOutPacket) HeaderID() uint16 { return HeaderCatalogApproveNameResultOut }

func (p *UserApproveNameResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Result)
	w.WriteString(p.ValidationInfo)
	return nil
}

func DecodeUserApproveNameResultOut(r *codec.Reader) (*UserApproveNameResultOutPacket, error) {
	p := &UserApproveNameResultOutPacket{}
	var err error
	if p.Result, err = r.ReadInt32(); err != nil { return nil, err }
	if p.ValidationInfo, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderAccountSafetyLockStatusChangeOut uint16 = 1243

// UserSafetyLockStatusOutPacket — Notify the client of an account safety-lock state change
type UserSafetyLockStatusOutPacket struct {
	Status int32
}

func (p *UserSafetyLockStatusOutPacket) HeaderID() uint16 { return HeaderAccountSafetyLockStatusChangeOut }

func (p *UserSafetyLockStatusOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Status)
	return nil
}

func DecodeUserSafetyLockStatusOut(r *codec.Reader) (*UserSafetyLockStatusOutPacket, error) {
	p := &UserSafetyLockStatusOutPacket{}
	var err error
	if p.Status, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserPerksOut uint16 = 2586

// UserPerksOutPacket — Deliver the list of perk allowances for the authenticated user
type UserPerksOutPacket struct {
	Count int32
}

func (p *UserPerksOutPacket) HeaderID() uint16 { return HeaderUserPerksOut }

func (p *UserPerksOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Count)
	return nil
}

func DecodeUserPerksOut(r *codec.Reader) (*UserPerksOutPacket, error) {
	p := &UserPerksOutPacket{}
	var err error
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserClassificationOut uint16 = 966

// UserClassificationOutPacket — Deliver user ID, username, and class type for a set of users
type UserClassificationOutPacket struct {
	Count int32
}

func (p *UserClassificationOutPacket) HeaderID() uint16 { return HeaderUserClassificationOut }

func (p *UserClassificationOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Count)
	return nil
}

func DecodeUserClassificationOut(r *codec.Reader) (*UserClassificationOutPacket, error) {
	p := &UserClassificationOutPacket{}
	var err error
	if p.Count, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserHomeRoomOut uint16 = 2875

// UserHomeRoomOutPacket — Deliver the user's home room and room to enter on login
type UserHomeRoomOutPacket struct {
	HomeRoomId int32
	RoomIdToEnter int32
}

func (p *UserHomeRoomOutPacket) HeaderID() uint16 { return HeaderUserHomeRoomOut }

func (p *UserHomeRoomOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.HomeRoomId)
	w.WriteInt32(p.RoomIdToEnter)
	return nil
}

func DecodeUserHomeRoomOut(r *codec.Reader) (*UserHomeRoomOutPacket, error) {
	p := &UserHomeRoomOutPacket{}
	var err error
	if p.HomeRoomId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RoomIdToEnter, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderInClientLinkOut uint16 = 2023

// UserInClientLinkOutPacket — Deliver a link string for the client to dispatch as an event
type UserInClientLinkOutPacket struct {
	Link string
}

func (p *UserInClientLinkOutPacket) HeaderID() uint16 { return HeaderInClientLinkOut }

func (p *UserInClientLinkOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Link)
	return nil
}

func DecodeUserInClientLinkOut(r *codec.Reader) (*UserInClientLinkOutPacket, error) {
	p := &UserInClientLinkOutPacket{}
	var err error
	if p.Link, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

const HeaderNoobnessLevelOut uint16 = 3738

// UserNoobnessLevelOutPacket — Deliver the account identity level that gates NUX features
type UserNoobnessLevelOutPacket struct {
	NoobnessLevel int32
}

func (p *UserNoobnessLevelOutPacket) HeaderID() uint16 { return HeaderNoobnessLevelOut }

func (p *UserNoobnessLevelOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.NoobnessLevel)
	return nil
}

func DecodeUserNoobnessLevelOut(r *codec.Reader) (*UserNoobnessLevelOutPacket, error) {
	p := &UserNoobnessLevelOutPacket{}
	var err error
	if p.NoobnessLevel, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderExtendedProfileChangedOut uint16 = 876

// UserExtendedProfileChangedOutPacket — Notify that another user's extended profile data has changed
type UserExtendedProfileChangedOutPacket struct {
	UserId int32
}

func (p *UserExtendedProfileChangedOutPacket) HeaderID() uint16 { return HeaderExtendedProfileChangedOut }

func (p *UserExtendedProfileChangedOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.UserId)
	return nil
}

func DecodeUserExtendedProfileChangedOut(r *codec.Reader) (*UserExtendedProfileChangedOutPacket, error) {
	p := &UserExtendedProfileChangedOutPacket{}
	var err error
	if p.UserId, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderEmailStatusOut uint16 = 612

// UserEmailStatusOutPacket — Deliver the account email address and verification status
type UserEmailStatusOutPacket struct {
	Email string
	IsVerified bool
	AllowChange bool
}

func (p *UserEmailStatusOutPacket) HeaderID() uint16 { return HeaderEmailStatusOut }

func (p *UserEmailStatusOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Email)
	w.WriteBool(p.IsVerified)
	w.WriteBool(p.AllowChange)
	return nil
}

func DecodeUserEmailStatusOut(r *codec.Reader) (*UserEmailStatusOutPacket, error) {
	p := &UserEmailStatusOutPacket{}
	var err error
	if p.Email, err = r.ReadString(); err != nil { return nil, err }
	if p.IsVerified, err = r.ReadBool(); err != nil { return nil, err }
	if p.AllowChange, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderChangeEmailResultOut uint16 = 1815

// UserChangeEmailResultOutPacket — Report the result of an email address change request
type UserChangeEmailResultOutPacket struct {
	Result int32
}

func (p *UserChangeEmailResultOutPacket) HeaderID() uint16 { return HeaderChangeEmailResultOut }

func (p *UserChangeEmailResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Result)
	return nil
}

func DecodeUserChangeEmailResultOut(r *codec.Reader) (*UserChangeEmailResultOutPacket, error) {
	p := &UserChangeEmailResultOutPacket{}
	var err error
	if p.Result, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderWelcomeGiftStatusOut uint16 = 2707

// UserWelcomeGiftStatusOutPacket — Deliver welcome-gift email status and furni eligibility
type UserWelcomeGiftStatusOutPacket struct {
	Email string
	IsVerified bool
	AllowChange bool
	FurniId int32
	RequestedByUser bool
}

func (p *UserWelcomeGiftStatusOutPacket) HeaderID() uint16 { return HeaderWelcomeGiftStatusOut }

func (p *UserWelcomeGiftStatusOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Email)
	w.WriteBool(p.IsVerified)
	w.WriteBool(p.AllowChange)
	w.WriteInt32(p.FurniId)
	w.WriteBool(p.RequestedByUser)
	return nil
}

func DecodeUserWelcomeGiftStatusOut(r *codec.Reader) (*UserWelcomeGiftStatusOutPacket, error) {
	p := &UserWelcomeGiftStatusOutPacket{}
	var err error
	if p.Email, err = r.ReadString(); err != nil { return nil, err }
	if p.IsVerified, err = r.ReadBool(); err != nil { return nil, err }
	if p.AllowChange, err = r.ReadBool(); err != nil { return nil, err }
	if p.FurniId, err = r.ReadInt32(); err != nil { return nil, err }
	if p.RequestedByUser, err = r.ReadBool(); err != nil { return nil, err }
	return p, nil
}

const HeaderWelcomeGiftChangeEmailResultOut uint16 = 2293

// UserWelcomeGiftChangeEmailResultOutPacket — Report the result of a welcome-gift email update
type UserWelcomeGiftChangeEmailResultOutPacket struct {
	Result int32
}

func (p *UserWelcomeGiftChangeEmailResultOutPacket) HeaderID() uint16 { return HeaderWelcomeGiftChangeEmailResultOut }

func (p *UserWelcomeGiftChangeEmailResultOutPacket) Encode(w *codec.Writer) error {
	w.WriteInt32(p.Result)
	return nil
}

func DecodeUserWelcomeGiftChangeEmailResultOut(r *codec.Reader) (*UserWelcomeGiftChangeEmailResultOutPacket, error) {
	p := &UserWelcomeGiftChangeEmailResultOutPacket{}
	var err error
	if p.Result, err = r.ReadInt32(); err != nil { return nil, err }
	return p, nil
}

const HeaderUserBannedOut uint16 = 1683

// UserBannedOutPacket — Notify the client that the user has been banned
type UserBannedOutPacket struct {
	Message string
}

func (p *UserBannedOutPacket) HeaderID() uint16 { return HeaderUserBannedOut }

func (p *UserBannedOutPacket) Encode(w *codec.Writer) error {
	w.WriteString(p.Message)
	return nil
}

func DecodeUserBannedOut(r *codec.Reader) (*UserBannedOutPacket, error) {
	p := &UserBannedOutPacket{}
	var err error
	if p.Message, err = r.ReadString(); err != nil { return nil, err }
	return p, nil
}

