package main

import (
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
)

// Config contains CLI parameters for the protocol generator.
type Config struct {
	// SpecPath points to the protocol YAML source.
	SpecPath string

	// OutDir is the destination directory for generated Go code.
	OutDir string

	// PackageName is the Go package name used in generated files.
	PackageName string
}

// parseFlags parses command-line flags into Config.
func parseFlags() Config {
	var cfg Config
	flag.StringVar(&cfg.SpecPath, "spec", "", "Path to protocol.yaml")
	flag.StringVar(&cfg.OutDir, "out", "", "Output directory for generated Go files")
	flag.StringVar(&cfg.PackageName, "package", "protocol", "Go package name")
	flag.Parse()
	return cfg
}

// validate checks required configuration values.
func (c Config) validate() error {
	if c.SpecPath == "" {
		return errors.New("-spec is required")
	}
	if c.OutDir == "" {
		return errors.New("-out is required")
	}
	if c.PackageName == "" {
		return errors.New("-package is required")
	}
	return nil
}

// run executes protocol generation.
func run(cfg Config) error {
	rawSpec, err := os.ReadFile(cfg.SpecPath)
	if err != nil {
		return fmt.Errorf("read spec: %w", err)
	}

	spec, err := LoadSpec(rawSpec)
	if err != nil {
		return fmt.Errorf("parse spec: %w", err)
	}

	if err := os.MkdirAll(cfg.OutDir, 0o755); err != nil {
		return fmt.Errorf("mkdir output dir: %w", err)
	}

	if err := writeRealmFiles(cfg, spec); err != nil {
		return err
	}
	if err := writeRouterFile(cfg, spec); err != nil {
		return err
	}
	if err := writeDocFile(cfg); err != nil {
		return err
	}

	log.Printf("done: %d c2s + %d s2c = %d packets", len(spec.Packets.C2S), len(spec.Packets.S2C), len(spec.Packets.C2S)+len(spec.Packets.S2C))
	return nil
}

// writeRealmFiles writes one generated file per packet realm.
func writeRealmFiles(cfg Config, spec *Spec) error {
	realmC2S := groupByRealm(spec.Packets.C2S)
	realmS2C := groupByRealm(spec.Packets.S2C)

	for _, realm := range mergeRealmKeys(realmC2S, realmS2C) {
		filename := realmToFilename(realm) + ".go"
		path := filepath.Join(cfg.OutDir, filename)
		code := GenerateRealmFile(cfg.PackageName, realm, realmC2S[realm], realmS2C[realm])
		if err := os.WriteFile(path, []byte(code), 0o644); err != nil {
			return fmt.Errorf("write realm file %s: %w", path, err)
		}
		log.Printf("wrote %s (%d c2s, %d s2c)", filename, len(realmC2S[realm]), len(realmS2C[realm]))
	}
	return nil
}

// writeRouterFile writes packet header maps and decode dispatchers.
func writeRouterFile(cfg Config, spec *Spec) error {
	path := filepath.Join(cfg.OutDir, "router.go")
	code := GenerateRouter(cfg.PackageName, spec.Packets.C2S, spec.Packets.S2C)
	if err := os.WriteFile(path, []byte(code), 0o644); err != nil {
		return fmt.Errorf("write router.go: %w", err)
	}
	log.Printf("wrote %s", filepath.Base(path))
	return nil
}

// writeDocFile writes package-level generation documentation.
func writeDocFile(cfg Config) error {
	path := filepath.Join(cfg.OutDir, "doc.go")
	code := fmt.Sprintf("//go:generate go run ../../tools/protogen -spec ../../vendor/pixel-protocol/spec/protocol.yaml -out .\n\n// Package %s contains generated packet structs and codec methods.\n// Code generated by protogen. DO NOT EDIT.\npackage %s\n", cfg.PackageName, cfg.PackageName)
	if err := os.WriteFile(path, []byte(code), 0o644); err != nil {
		return fmt.Errorf("write doc.go: %w", err)
	}
	log.Printf("wrote %s", filepath.Base(path))
	return nil
}

// groupByRealm groups packet definitions by their realm name.
func groupByRealm(pkts []PacketDef) map[string][]PacketDef {
	out := make(map[string][]PacketDef)
	for _, packet := range pkts {
		out[packet.Realm] = append(out[packet.Realm], packet)
	}
	return out
}

// mergeRealmKeys merges map keys from c2s and s2c realm maps into one list.
func mergeRealmKeys(a, b map[string][]PacketDef) []string {
	seen := make(map[string]bool)
	out := make([]string, 0, len(a)+len(b))
	for key := range a {
		if !seen[key] {
			seen[key] = true
			out = append(out, key)
		}
	}
	for key := range b {
		if !seen[key] {
			seen[key] = true
			out = append(out, key)
		}
	}
	return out
}

func main() {
	log.SetFlags(0)
	cfg := parseFlags()
	if err := cfg.validate(); err != nil {
		log.Printf("invalid configuration: %v", err)
		flag.Usage()
		os.Exit(1)
	}
	if err := run(cfg); err != nil {
		log.Fatalf("protogen failed: %v", err)
	}
}
