package main

import (
	"bytes"
	"fmt"
	"strings"
)

// renderPackets emits generated packet structs and codec methods.
func renderPackets(packets []packetSpec, direction string) ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	_, _ = buf.WriteString("// Code generated by tools/protogen. DO NOT EDIT.\n")
	_, _ = buf.WriteString("package protocol\n\n")
	_, _ = buf.WriteString("import \"pixelsv/pkg/codec\"\n\n")
	for _, packet := range packets {
		if err := writePacket(buf, packet, direction); err != nil {
			return nil, err
		}
	}
	return buf.Bytes(), nil
}

// writePacket emits one packet struct and its encode/decode implementation.
func writePacket(buf *bytes.Buffer, packet packetSpec, direction string) error {
	typeName := typeNameFor(packet.Name)
	constName := "Header" + typeName
	_, _ = fmt.Fprintf(buf, "const %s uint16 = %d\n\n", constName, packet.ID)
	_, _ = fmt.Fprintf(buf, "type %s struct {\n", typeName)
	for _, field := range packet.Fields {
		goType, err := goTypeFor(field)
		if err != nil {
			return err
		}
		_, _ = fmt.Fprintf(buf, "\t%s %s\n", fieldName(field.Name), goType)
	}
	_, _ = buf.WriteString("}\n\n")
	_, _ = fmt.Fprintf(buf, "func (p *%s) HeaderID() uint16 { return %s }\n\n", typeName, constName)
	_, _ = fmt.Fprintf(buf, "func (p *%s) PacketName() string { return %q }\n\n", typeName, packet.Name)
	_, _ = fmt.Fprintf(buf, "func (p *%s) Realm() string { return %q }\n\n", typeName, packet.Realm)
	_, _ = fmt.Fprintf(buf, "func (p *%s) Encode(writer *codec.Writer) error {\n", typeName)
	for _, field := range packet.Fields {
		line, err := encodeLine(field)
		if err != nil {
			return err
		}
		_, _ = fmt.Fprintf(buf, "\t%s\n", line)
	}
	_, _ = buf.WriteString("\treturn nil\n}\n\n")
	decodeName := "decode" + typeName
	_, _ = fmt.Fprintf(buf, "func %s(reader *codec.Reader) (Packet, error) {\n", decodeName)
	_, _ = fmt.Fprintf(buf, "\tpacket := &%s{}\n", typeName)
	if len(packet.Fields) > 0 {
		_, _ = buf.WriteString("\tvar err error\n")
	}
	for _, field := range packet.Fields {
		line, err := decodeLine(field)
		if err != nil {
			return err
		}
		_, _ = fmt.Fprintf(buf, "\t%s\n", line)
	}
	_, _ = buf.WriteString("\treturn packet, nil\n}\n\n")
	regLine := registerLine(direction, constName, packet, decodeName)
	_, _ = fmt.Fprintf(buf, "func init() { %s }\n\n", regLine)
	return nil
}

// registerLine emits registry initialization for one packet definition.
func registerLine(direction string, constName string, packet packetSpec, decodeName string) string {
	if direction == "s2c" {
		return "_ = " + constName
	}
	return fmt.Sprintf(
		"registerC2S(Definition{ID: %s, Name: %q, Realm: %q, Summary: %q, Decode: %s})",
		constName,
		packet.Name,
		packet.Realm,
		packet.Summary,
		decodeName,
	)
}

// typeNameFor converts protocol packet names into Go type identifiers.
func typeNameFor(value string) string {
	replacer := strings.NewReplacer(".", "_", "-", "_", " ", "_")
	parts := strings.Split(replacer.Replace(value), "_")
	names := make([]string, 0, len(parts)+1)
	for _, part := range parts {
		if part != "" {
			names = append(names, strings.ToUpper(part[:1])+part[1:])
		}
	}
	names = append(names, "Packet")
	return strings.Join(names, "")
}

// fieldName converts field names into exported Go identifiers.
func fieldName(value string) string {
	if value == "" {
		return "Field"
	}
	return strings.ToUpper(value[:1]) + value[1:]
}
